- docs/user_guide/remote_processing.rst
Had to add this for ZeroSoC to work.
> Document that 'eda', ... 'variable' is legal for remote

- .readthedocs.yaml
- docs/_ext/dynamicgen.py
- docs/conf.py
- setup.py
* Fix .readthedocs.yaml
* Skip leflib build on RTD
* Mock up leflib import/skip sc_floorplan for now
* Fix a sneaky typo in setup.py that caused pip-licenses not to get installed
I want to look into cleaner ways to handle some of these things going forward, but I think this should be good for now!
> Fix ReadTheDocs build

- docs/user_guide/installation.rst
Just walked through the signup process again, and I think I found a small typo near the top of the installation instructions.
> Fix a small typo in user_guide/installation

- siliconcompiler/core.py
- siliconcompiler/tools/klayout/klayout.py
- siliconcompiler/tools/klayout/klayout_show.py
- tests/core/test_show.py
This fixes a couple of issues that we encountered running 'sc-show' on Windows:
* Windows does not add KLayout's install location to the $PATH environment variable, and the app has a different name from Linux/MacOS.
* If the tool was installed via pip, submodules such as the PDK files are not included. So we shouldn't try to load layer information if it does not exist on the user's system.
* Noah fixed the existing `sc-show` test and added a new one in the [noah/klayout](https://github.com/siliconcompiler/siliconcompiler/commit/72f681e52d868c3e9001dc39608f8e3e3405ecd4) branch, so I pulled that in. We should probably talk about the new test's logic, but I tested the 'no PDK' logic on Windows and it appears to work.
> Fix the 'sc-show' command on Windows

- docs/user_guide/examples/heartbeat.py
This is necessary to avoid a multiprocessing bug on Windows. 
See: https://github.com/siliconcompiler/siliconcompiler/discussions/681#discussioncomment-1779957
> Update heartbeat.py to check __name__ == '__main__'

- .github/workflows/wheels.yml
- MANIFEST.in
This PR adds logic to our wheels CI workflow to automatically build and upload the wheels to PyPI whenever we publish a new Github Release.
> Augment wheels workflow to automate PyPI release

- .github/workflows/wheels.yml
This PR adjusts our wheels build script to automatically build wheels for newer Arm-based Macs.
> Build wheels for Arm-based M1 Macs

- siliconcompiler/tools/klayout/klayout.py
I think I messed up and let these back in when I rebased my previous KLayout PR #796. 
Note: this PR does delete some TODOs that were supposed to be fixed when switching the Python script to read the config directly, but I'm not exactly sure how to implement these. Let me know if they're still valid/need to be implemented!
> Don't emit useless CLI options on KLayout export

- tests/tools/data/test_preproc.v
- tests/tools/test_surelog.py
I noticed that the Surelog submodule version accidentally got decreased at some point, so our wheels bundle a version with this bug: https://github.com/chipsalliance/Surelog/issues/2176.
This PR brings Surelog back to a working version, and also adds a regression test for this bug that should prevent this from happening again.
> Bump Surelog Version

- siliconcompiler/core.py
- siliconcompiler/tools/klayout/def2stream.py
- siliconcompiler/tools/openroad/sc_apr.tcl
- siliconcompiler/tools/yosys/sc_lec.tcl
- tests/flows/test_tool_option.py
- tests/tools/test_klayout.py
- tests/tools/test_yosys.py
This PR implements the change we discussed to append a hash to collected filenames to make sure they can be unambiguously identified after being placed in a single directory. The actual changes to the core logic are fairly minimal, although this did reveal a few bugs elsewhere that needed fixing.
> Handle duplicate file basenames

- docs/index.rst
- docs/tutorials/examples/migen_heartbeat.py
- docs/tutorials/frontends.rst
- docs/tutorials/migen.rst
This PR adds a short example of how to use Migen with SC to a new page in the tutorials section. I figure we can fill this page out as SC gets support for additional frontends.
> Add Migen tutorial

- setup/rhel7-install-openroad.sh
This change adds a setup script for the OpenROAD tools on Red Hat 7.
If the `RHEL7_OPENROAD_INSTALL_DEVTOOLS` environment variable is set, recent versions of a few core tools will be built from source. Otherwise, the script assumes that the user has already installed a GNU toolchain with support for the c++17 standard, recent versions of cmake and boost, and Python 3.6+ with development libraries.
> RHEL7 OpenROAD setup script

- README.md
Very teeny detail, but I noticed that our logo doesn't load on our PyPI package page:
This PR should fix this whenever we deploy our next release: https://stackoverflow.com/questions/41983209/how-do-i-add-images-to-a-pypi-readme-that-works-on-github/46875147, and will make the page a little prettier.
> Use external link for SC logo in README

- siliconcompiler/tools/klayout/klayout.py
After the v0.3.0 changes, we need to override the KLayout executable name which `sc-show` loads out of the post-export manifest step. Without this change, the script tries to run `klayout` instead of `klayout_app.exe` on Windows platforms.
> Fix sc-show on Windows after recent schema changes

- siliconcompiler/core.py
I factored out this small error check from the big file checking PR since it's completely independent.
Before:
```
>>> chip.get('fake', 'keypath')
File "<stdin>", line 1, in <module>
File "/home/noah/zeroasic/siliconcompiler/siliconcompiler/core.py", line 757, in get
return self._search(cfg, keypathstr, *keypath, field=field, mode='get')
File "/home/noah/zeroasic/siliconcompiler/siliconcompiler/core.py", line 1112, in _search
cfg[param] = copy.deepcopy(cfg['default'])
KeyError: 'default'
```
After:
```
>>> chip.get('fake', 'keypath')
| ERROR   | job0    | ---          | -   | Get keypath [fake,keypath] does not exist.
```
> Cleaner error message when attempting to get() invalid multi-entry keypaths

- .github/workflows/bin/install_klayout_win.bat
- .github/workflows/wheels.yml
- siliconcompiler/tools/klayout/klayout.py
- tests/core/test_show.py
This PR adds support for testing `show()` functionality after building Windows wheels on our CI system. 
I verified this with a manual wheel build run: https://github.com/siliconcompiler/siliconcompiler/actions/runs/1616295030, although I've since rebased this to catch up to main.
> Test show() on Windows CI

- siliconcompiler/core.py
- siliconcompiler/schema.py
- siliconcompiler/tools/klayout/klayout.py
- siliconcompiler/tools/surelog/surelog.py
This PR implements the 'eda', ..., 'path' parameter and uses it to refactor the $PATH hacks we added for Surelog and KLayout. This seems like a slightly cleaner way to handle these hacks: for example, now the user can check the manifest to see where the executables are being found. 
I tested that the changes to these hacks work on all platforms by rebasing this PR on PR #823 and manually running a wheel build/test: https://github.com/siliconcompiler/siliconcompiler/actions/runs/1650785417.
> Implement 'eda', ..., 'path' parameter

- requirements.txt
- setup.py
This will prevent us from having to specify dependencies twice going forward.
> Use requirements.txt as a single-source of truth

- .github/workflows/bin/setup_wheel_env_linux.sh
- .github/workflows/bin/setup_wheel_env_macos.sh
- .github/workflows/bin/setup_wheel_env_win.bat
- .github/workflows/daily_tests.yml
- .github/workflows/docs_test.yml
- .github/workflows/on_push_tests.yml
- .github/workflows/wheels.yml
- setup.py
- tests/conftest.py
- tests/core/test_archive.py
- tests/designs/test_picorv32.py
- tests/flows/test_doe.py
- tests/tools/test_icarus.py
- tests/tools/test_verilator.py
This PR might seem a little random, but it was a refactor I started before the holidays related to a test I was thinking of adding then scrapped. I kind of like this cleanup though, so figured I'd suggest it anyways. Long description from commit message:
This automates clones of design/tool submodules by coupling them to the
places where the submodules are actually needed. This prevents us from
having to do a fine-grained selection of which submodules are needed in
CI scripts, while still avoiding a complete download of our many
submodules.
The most intricate part are the new test fixtures: these will clone
design submodules as needed by tests and return a path to the submodule.
If the submodule is already cloned there will be no effect, and the
fixture will not attempt to clone the …
> Automate most submodule management

- siliconcompiler/core.py
- siliconcompiler/schema.py
- tests/core/test_create_cmdline.py
This PR adds supports for the -I flag. 
I actually think we don't yet have any parameters with two switches (example from discussion earlier was `ydir`, but that only supports `-y`, not `-ydir`). This might be a bit much, but I decided to mock up a solution that makes the switch parameter an optional list. I'm not sure if this is worth it for the small, finite number of cases where we might want to do this, but the code change ended up being pretty minimal so I'm curious to get thoughts on this approach. 
Closes #632
> Add support for -I flag

- siliconcompiler/core.py
- siliconcompiler/tools/yosys/yosys.py
- tests/core/test_check_manifest.py
This check ensures that as long as the tool spec is written correctly, we should never fail during TCL execution due to a filepath being resolved to None.
> Dynamically check that all required file/dir-type parameters resolve correctly in check_manifest()

- siliconcompiler/_metadata.py
- siliconcompiler/tools/yosys/yosys.py
This PR is a quick fix to the Yosys requirements specification - this new check accidentally broke the ZeroSoC top-level build. I figure we can put out a patch with this at some point soon.
> Fix Yosys requirements specification

- tests/core/test_env_schema.py
This PR skips a failing test on macOS and Windows to get the wheels CI back to green. Verified here: https://github.com/siliconcompiler/siliconcompiler/actions/runs/1685871529. 
These platforms use the multiprocessing "spawn" start method by default, which doesn't propagate the mocked _runtask(), breaking this test. I manually verified that the environment gets set in _runtask() in macOS. Going forward, it might be a good idea to find another way to write this test to ensure we don't have regressions on these platforms.
There was also a different issue with the wheel builds last night, related to https://github.com/chipsalliance/Surelog/pull/2422. Resolving it requires updating Surelog, but the issue (which was related to a Github security setting) seems to have resolved itself. I'll …
> Skip test_env on macOS/Windows

- siliconcompiler/apps/sc_show.py
- tests/apps/test_sc_show.py
Our recent schema changes may have introduced a small bug in how `sc-show` parses its command-line options. I started following [the ZeroSoC tutorial](https://docs.siliconcompiler.com/en/latest/tutorials/zerosoc.html) to get a feel for the Python floorplanning API, and I got the following error when I tried to view the first .def file:
$ sc-show -read_def "show 0 asic_core.def" -cfg core_manifest.json
[...]
| ERROR   | job0    | ---          | -   | Exactly one of -read_gds, -read_def, or -design must be provided.
It looks like the `sc-show` app expects that the `-design` parameter could only have been set from command line arguments [at the point where this error is thrown](https://github.com/siliconcompiler/siliconcompiler/blob/ced8e2b35127ae8f22efa2d8499fd451d5a13a51/siliconcompiler/app …
> Update the `-read_def/gds` sc-show options to work with `-cfg`

- siliconcompiler/core.py
- siliconcompiler/utils.py
This PR adds a wrapper around the hashlib md5 function that adds the `usedforsecurity=False` keyword argument when supported. Since using MD5 to deduplicate filenames isn't security related, this is safe.
Closes #845.
> Fix collected filename mangling on FIPS compliant systems

- docs/_ext/installgen.py
- setup/docker/Dockerfile
- setup/docker/README.md
- setup/docker/container_init.py
This PR adds a simple Dockerfile for an Ubuntu 20.04 image with sc and the core open-source EDA tools installed.
Next steps: X11 forwarding isn't set up for GUI apps like KLayout yet, and it might be a good idea to add instructions for mounting local directories in the container.
> Add an initial Dockerfile and setup script

- siliconcompiler/tools/openroad/sc_apr.tcl
> Fix typo in sc_apr.tcl

- siliconcompiler/floorplan.py
Now that we've split up PDK tech information by tool, this parameter lets a designer specify which tool will consume the floorplan, so that the floorplan is generated using the correctly-associated tech information. The default is OpenROAD, maintaining backwards compatibility with the previous API.
> Add 'tool' parameter to floorplan constructor

- siliconcompiler/core.py
- siliconcompiler/schema.py
- siliconcompiler/tools/klayout/klayout.py
This change updates the schema's `vswitch` parameter to allow multiple command-line options for version checks.
Some tools (such as KLayout) require more than one CLI flag to produce output without trying to open GUI windows. Like we discussed earlier, `vswitch` is conceptually similar to the generic CLI `option` parameter, so it makes sense to store it as a list of strings.
> First pass at allowing multiple 'version switch' parameters for tools

- examples/gcd/run.sh
- siliconcompiler/core.py
- siliconcompiler/schema.py
- siliconcompiler/tools/openroad/openroad.py
- siliconcompiler/tools/yosys/yosys.py
- tests/core/data/place.log
- tests/core/test_check_logfile.py
New logfile grep feature: 
-  It's doubtful there has been a digital tapeout done in the last 30 years that didn't rely on some kind of grep check to make sure the log files were clean.
- This feature tries to replicate that grep approach within the schema.
- Instead of keeping little one line shell scripts around in a tar ball, we embed patterns in the schema for safe keeping.
- Support for a selection of grep switches in conjunction with pipe enables generalized and/or/not pattern search.
Also:
- Enable running complete flow as nop, which is useful when testing new flows and new tools. If the tool is missing in the path, the version check would fail.
- Changing the write manifest message from info to debug to reduce noise. It wasn't really adding value to the casual user.
> Adding grep like regex parameter to schema

- siliconcompiler/client.py
- siliconcompiler/core.py
- tests/core/test_check_manifest.py
Steplist defvalue is [], so we shouldn't compare to None to check if it's unset.
This change uncovered a few other hidden bugs which I've fixed:
1. Need to set the steplist in test_check_manifest(): since we're only setting up two steps here, we need to set the steplist accordingly.
2. Setting a steplist before calling the local _runtask() in remote_preprocess() - this one's a bit more complex. From the commit message body:
Another bug hidden by the check_manifest() steplist issue. In this case,
only the local step is set up before remote_preprocess() calls
_runtask(), so we need to override the steplist to force it to only
check the local step. This feels a bit hacky, but it shouldn't be
dangerous since we already overwrite the steplist for the remote run
immediately after.
I also snuck …
> Fix steplist bug in check_manifest()

- siliconcompiler/apps/sc.py
- siliconcompiler/core.py
- siliconcompiler/tools/bambu/bambu.py
- siliconcompiler/tools/bluespec/bluespec.py
- siliconcompiler/tools/ghdl/ghdl.py
- siliconcompiler/tools/icarus/icarus.py
- siliconcompiler/tools/surelog/surelog.py
- siliconcompiler/tools/verilator/verilator.py
- tests/core/test_env_schema.py
This PR makes it so providing sources is no longer a hard requirement when using the CLI. Instead, individual tools that ingest sources are responsible for marking it as a tool-specific requirement. I also had to add a bit of logic to sc.py to gracefully handle an error that occurs if we try to infer 'design' when no sources are provided. I think the error messages for these invalid invocations are pretty clear:
```
$ sc
| INFO    | job0    | ---          | -   | Setting commandline arguments
| ERROR   | job0    | ---          | -   | Invalid arguments: either specify -design or provide sources.
```
```
$ sc -design gcd
| INFO    | job0    | ---          | -   | Setting commandline arguments
| INFO    | job0    | ---          | -   | Loading target 'asicflow_freepdk45'
| INFO    | job0 …
```
> Get rid of hard requirement to provide sources on CLI

- docs/reference_manual/core_api.rst
- docs/user_guide/tools.rst
- siliconcompiler/core.py
- tests/tools/test_ghdl.py
- tests/tools/test_icarus.py
- tests/tools/test_klayout.py
- tests/tools/test_openroad.py
- tests/tools/test_surelog.py
- tests/tools/test_verilator.py
- tests/tools/test_yosys.py
This PR builds on top of #862 and fixes its failing tests. The main change is adjusting the way that standalone tool runs are set up. It gets rid of `load_tool()` -- we don't need this function since each tool's `setup()` function is called automatically inside of `run()`, and giving the user the ability to call it earlier can be problematic since it introduces ordering issues.
I chose overriding the 'flow' schema parameter as the new way to specify a standalone tool run. Now, if the user specifies a flow that doesn't have a configured flowgraph, `run()` will automatically set up a basic flowgraph to run that tool. I considered making a separate helper function for loading a standalone tool, but I realized using a schema parameter is necessary to support running tools in standalone mode …
> Use 'flow' parameter to specify standalone tool run

- siliconcompiler/tools/klayout/klayout_show.py
- tests/core/test_show.py
This change allows us to use either `.lyt` or `.lyp` files to configure display properties in `sc-show`.
The `.lyp` file contains layer display properties such as color/pattern/etc, and we currently read its location from the `.lyt` file which is passed into the `klayout_show.py` script. This change allows us to specify either a `.lyp` or `.lyt` file in the `['pdk']['layermap']['klayout'][...]` parameter.
> Add support for KLayout .lyp files to sc-show

- siliconcompiler/scheduler.py
We need `__init__.py` files in the `targets/` and `libs/` directories so that Python treats the files in those directories as modules. There's also a missing `chip.get('flow')` key in `scheduler.py`.
> Small fixes for the new v0.6 schema

- siliconcompiler/pdks/asap7.py
- siliconcompiler/pdks/freepdk45.py
- siliconcompiler/pdks/skywater130.py
- siliconcompiler/schema.py
- siliconcompiler/tools/openroad/openroad.py
This PR removes the tech-specific variable default values from openroad.py. It now drives the defaults through the PDK. 
Also included some misc cleanup of the file.
> Clean up tech-specific variables in OpenROAD

- siliconcompiler/core.py
This PR fixes a subtle bug with the way the 'jobinput' parameter is handled. For any task that has a 'jobinput' set, the `job` variable gets overwritten with the name of the input job, but this `job` variable is also used to determine where records get stored when 'track' is set to True (see [core.py line 3413](https://github.com/siliconcompiler/siliconcompiler/blob/e724bcfb290a846710a6f44368b72a97e9b0c0d9/siliconcompiler/core.py#L3413)). 
Changing the variable name fixes this problem and should make thing safer from bugs in the future, since the new name is a bit more explicit.
> Fix jobinput/record bug

- docs/_ext/installgen.py
- tests/flows/test_tool_option.py
- Fix installgen: `os.listdir()` doesn't give full path, so the `os.path.isfile` check always fails. Turns out the list of setup scripts has been missing from the docs for a while!
- Fix skipped test_tool_option: Problem was that with the new target scheme the test was hacking invalid changes into asicflow, so we needed to set up a test flow in its own "lane".
> Two small fixes

- siliconcompiler/core.py
A few changes I had in my local branch:
- Docstring fix
- Fix bug in `_check_flowgraph_io()` that would occasionally cause checks to fail when using 'jobinput'
- Remove return value from `read_manifest()`. This is a very small change but might be the most controversial - however, I don't think we rely on the return value of this function anywhere (it's not even documented), and it can be annoying when using the interactive Python shell. The problem is that the REPL prints out the return value of any function when it's not assigned to something, so if you do `chip.read_manifest(...)` it will print out a massive dictionary that obscures previous command history.
> Some small cleanup things in core.py

- setup/install-klayout.sh
The old URLs are dead. The new ones point to the current 0.26.XX version.
> Update klayout version in install-klayout.sh

- docs/_ext/common.py
- docs/_ext/dynamicgen.py
- Use Sphinx refs for linking between dynamic modules so that the links work for custom modules/within a PDF
- Display list-type schema values as bulleted list
- Add 'nobuiltins' option for dynamic module autogen -- causes them to
only document stuff on SCPATH (off by default)
- Reorder lists in targets docs
- Bugfix: make flowgraph image generation more robust to odd build directories
- Bugfix: make skip_zero_weight work again (broke due to schema update
> Some documentation enhancements

- siliconcompiler/core.py
I ran into a weird bug with a Slurm-based run using NFS to host the shared build directory. The main `run()` thread consistently failed to find the final results file, even though manual inspection after the completed run showed that it exists.
I did some digging around, and it seems likely that it's related to some sort of NFS cache coherency issue. This person had a very similar scenario: https://stackoverflow.com/questions/21292365/python-os-path-exists-failing-for-nfs-mounted-directory-file-that-exists. 
One of the answers suggested that using an `os.system('ls')` call fixes the issue by forcing a cache flush, and I found that the Python `listdir()` method seems to have the same effect (which I actually noticed by accident while using it to debug).
I figure we can merge this since …
> Add no-op lisdir to fix network filesystem issue

- siliconcompiler/core.py
- siliconcompiler/schema.py
Since we clobber [arg, index] when running the tool setup loop, using it
later to determine whether or not to only run a single index for a step
doesn't work. Precomputing a per-step indexlist avoids this problem and
also makes the code cleaner.
This also fixes an additional uncaught bug where the indexlist parameter
wouldn't be respected by run().
> Fix bug causing [arg, index] to not be respected

- siliconcompiler/core.py
- siliconcompiler/schema.py
The `environment` schema parameter is stored as an array, not a string. So it probably makes sense to use `':'.join` with these values, even though there's usually only one value for each environment variable.
> Account for `environment` parameters being stored as an array

- siliconcompiler/scheduler.py
Slurm seems to have a bit of trouble writing log files to non-existant or newly-created directories.
I've been writing the slurm log files to the build's root directory and relocating them in the server's `get_results` call as a workaround; it seems like we should formalize that change since it's been in effect for a couple of releases.
> Simplify scheduler log output

- siliconcompiler/tools/magic/sc_drc.tcl
- siliconcompiler/tools/magic/sc_extspice.tcl
Another fix I think we'll want for 0.7.
> Add missing $sc_stackup keys to Magic scripts

- siliconcompiler/core.py
The report generation logic relies on some schema parameters which get removed by the server sanitizer, so we need a bit of logic to make that part of the `summary()` function fault-tolerant, and to generate a final report locally after a remote run.
> Fix report generation for remote runs.

- siliconcompiler/core.py
- siliconcompiler/schema.py
- tests/core/data/gcd.pkg.json
- tests/core/test_check_manifest.py
- tests/core/test_nop.py
- Necessary to enable selection between different output formats
- gds vs oasis is one example
- gerber vs ipc2581 is another
> Adding oformat parameter to schema.

- examples/gcd/run.sh
- siliconcompiler/core.py
- siliconcompiler/schema.py
- tests/core/test_write_manifest.py
Greatly simplifies the TCL drivers, since we don't have to check for the existence of a key. Removes a lot of annoying if/else statements.
> Fixing print_tcl to output all schema values (not just non-empty)

- siliconcompiler/tools/openroad/sc_apr.tcl
- siliconcompiler/tools/openroad/sc_cts.tcl
- siliconcompiler/tools/openroad/sc_route.tcl
- siliconcompiler/tools/yosys/yosys.py
- tests/flows/test_gcd_infer_diesize.py
- tests/flows/test_gcd_skywater.py
This PR updates our OpenROAD-flow-scripts submodule to the latest version, and ensures that all the scripts still work.
There was actually only one small breaking API change, but the process revealed a bug in how we were handling placement padding. From the commit notes:
- We should use the $openroad_pad_detail_place value instead of the
$openroad_pad_global_place in sc_cts.tcl, since we are doing a
detailed placement here. This is consistent with ORFS.
- This makes the global call to set_placement_padding in sc_apr.tcl
problematic, because it sets the placement padding value to the global
value and then runs a placement check. However, the default detailed
placement padding for Sky130 is smaller than the global placement
padding, so this check can then fail overlap checks.
- This bug …
> Update OpenROAD to latest 

- siliconcompiler/core.py
- siliconcompiler/leflib/__init__.py
- siliconcompiler/leflib/_leflib.pyx
- tests/core/test_read_lef.py
This PR implements a helper function for reading 'pdk', 'grid' data out of a tech LEF. This should be useful for simplifying PDK setup files.
Implementation ended up being pretty straightforward. Main thing that might warrant discussion is interface -- I decided to make it take in a path/stackup explicitly to avoid any sort of schema setup ordering requirements, but we could also consider reading these out of the schema directly.
> Add read_lef helper for simplifying PDK bringup

- docs/_ext/dynamicgen.py
- siliconcompiler/core.py
- siliconcompiler/flows/asicflow.py
- siliconcompiler/flows/asictopflow.py
- siliconcompiler/flows/signoffflow.py
- siliconcompiler/targets/freepdk45_demo.py
- siliconcompiler/targets/skywater130_demo.py
- siliconcompiler/tools/magic/magic.py
- siliconcompiler/tools/magic/sc_drc.tcl
- siliconcompiler/tools/magic/sc_extspice.tcl
- siliconcompiler/tools/magic/sc_magic.tcl
- siliconcompiler/tools/netgen/netgen.py
- siliconcompiler/tools/netgen/sc_lvs.tcl
- tests/flows/test_gcd_skywater.py
This PR creates two new flows:
- signoffflow: this is the optional verification component of asicflow, split into its own. It has been added to the Skywater target.
- asictopflow: this is the "physflow" that is currently hardcoded into the ZeroSoC build script. It takes in a DEF and just does a GDS stream out with any configured libraries, and also generates a netlist for passing into future LVS steps.
This sets us up nicely to begin thinking about how we want to stitch flows together. Right now, I've settled on using the 'read' schema coupled with '`chip.find_result(...)` to implement the hand-off from one to another (see changes to test_gcd_skywater.py as an example), but I think there are certainly ways this could be improved.
> Create distinct asictopflow and signoffflow

- .github/workflows/wheels.yml
- setup.py
This checks out the older version of OpenROAD in the wheels CI script to ensure that we can still build them until the fundamental problem is solved.
> Hack to fix wheels

- siliconcompiler/core.py
- siliconcompiler/schema.py
- tests/core/data/defaults.json
- tests/tools/test_surelog.py
This PR fixes tweaks 3 things surrounding replay script generation:
- Fix issue where grouped parameters would become unquoted (i.e. `-param "a b c"` would become `-param a b c` in script, now it stays the same).
- Add code to set environment variables in script
- Add Windows support: .bat instead of .sh, no `#!/bin/bash` header, set env variables appropriately for each platform
I haven't yet tested the Windows support, but I did add a replay test based on Surelog (so that it catches all platforms), and I can kick off a wheel build to try it out.
> Tweaks to replay script generation

- .github/workflows/wheels.yml
- docs/user_guide/installation.rst
This PR adds code to package up SC wheels and their dependencies into a single tarball in CI. This can then be installed like so:
```
tar -xzvf scdeps-<pyversion>.tar.gz
pip install siliconcompiler --no-index --find-links scdeps
```
I've also added these instructions to the docs.
> Build offline installation bundles in CI

- docs/_ext/dynamicgen.py
- docs/_ext/schemagen.py
- siliconcompiler/core.py
- siliconcompiler/schema.py
- siliconcompiler/utils.py
- tests/core/data/defaults.json
- tests/core/test_scparam.py
This PR:
- Implements the TODO in _search() mentioned in code review
- Fixes up RST parsing of schema help strings
For the latter, I decided move to processing schelp using the Python standard "trim()" function for preprocessing docstrings that we were already using for the flows/pdks/libs/etc. documentation. The previous regex approach was stripping away newlines, which made it impossible to do fancier RST formatting, such as lists.
The new approach strips off a calculated amount of leading spaces to preserve additional indentation (for inserting things like codeblocks), and preserves newlines. A consequence of this change is that there will be newlines in the help string, but I think this is a worthwhile tradeoff, since it makes the actual docs look much nicer:
> Post-schema refactor fixes

- .github/workflows/on_push_tests.yml
This PR adds a workaround for https://github.com/actions/virtual-environments/issues/5237, based on https://github.com/PerlAlien/Alien-SWIG4/commit/7b175c0379638a0cd8c0019f59c3a73046abaace. Will revert once the main issue is fixed, but this should get us back to green in the meantime.
> Github Actions issue workaround

- siliconcompiler/core.py
This PR updates the 'record' keypaths being used by _make_record().
It's interesting to me that this didn't cause any failures, 'track' is on in examples/gcd/gcd.py and it produces ERROR logs without being fatal:
`pytest tests/examples/test_gcd::test_py -s`
```
| INFO    | job0    | import       | 0   | Copying /home/noah/code/siliconcompiler/examples/gcd/gcd.sdc to 'inputs' directory
| INFO    | job0    | import       | 0   | Checking executable. Tool 'surelog' found with version '1.25'
| INFO    | job0    | import       | 0   | Running in /tmp/pytest-of-noah/pytest-22/test_py0/build/gcd/job0/import/0
| INFO    | job0    | import       | 0   | surelog -parse /tmp/pytest-of-noah/pytest-22/test_py0/build/gcd/job0/import/0/outputs/gcd_0a998a746037a840df8d7f2133c57f4846e3405f.v -top gcd …
```
> Fix _make_record() for schema changes

- siliconcompiler/tools/yosys/syn_asic.tcl
This change fixes the `syn` branch of `asictopflow`, by making .lib files optional for components. Some macros, such as the core GDS/DEF outputs from an `asicflow` job, may not have associated liberty files.
> Allow yosys to skip libraries if they are expected but not present in the schema

- setup/install-klayout.sh
- setup/install-openroad-rhel7.sh
- setup/install-openroad.sh
I encountered a few issues using the setup scripts in my fresh Ubuntu 20.04 VM, so I would like to share my fixes. I see that using conda is the most convenient solution, but these scripts can still be useful to someone who prefers a traditional approach.
> Small fixes to setup scripts

- docs/tutorials/zerosoc.rst
- siliconcompiler/tools/surelog/surelog.py
This PR adds some fixes that came up when I was getting ZeroSoC DRC/LVS clean again.
1) Adding `+libext+v`  as a Surelog option breaks the ZeroSoC build since it overrides the previous `+libext` flag. Proper syntax is to specify both extensions after one flag like so: `+libext+sv+v`.
2) Updated tutorial to account for floorplan changes needed to fix DRC/LVS violations.
> Surelog fix and ZeroSoC docs update

- docs/user_guide/tools.rst
- requirements.txt
- setup/install-ice40.sh
- siliconcompiler/core.py
- siliconcompiler/schema.py
- siliconcompiler/tools/bambu/bambu.py
- siliconcompiler/tools/bluespec/bluespec.py
- siliconcompiler/tools/chisel/chisel.py
- siliconcompiler/tools/ghdl/ghdl.py
- siliconcompiler/tools/icarus/icarus.py
- siliconcompiler/tools/klayout/klayout.py
- siliconcompiler/tools/magic/magic.py
- siliconcompiler/tools/netgen/netgen.py
- siliconcompiler/tools/nextpnr/nextpnr.py
- siliconcompiler/tools/openfpga/openfpga.py
- siliconcompiler/tools/openfpgaloader/openfpgaloader.py
- siliconcompiler/tools/openroad/openroad.py
- siliconcompiler/tools/surelog/surelog.py
- siliconcompiler/tools/sv2v/sv2v.py
- siliconcompiler/tools/verilator/verilator.py
- siliconcompiler/tools/yosys/yosys.py
- tests/core/data/defaults.json
This PR implements a proposal for flexible version checking that allows for comparisons. I've implemented this as a baseline for discussion before I go ahead and modify more tool drivers (although I implemented it in a way that somewhat maintains backwards compatibility).
Here is the approach:
- `parse_version()` stays the same
- Tools may define a new function, `normalize_version()`. This is intended to take in a version string produced by `parse_version()`, and return a comparable value such that if `ver_a` is newer than `ver_b`, `normalize_version(ver_a) > normalize_version(ver_b)`
- As a methodology thing, I think it makes the most sense for tools to return tuples of int. The way tuple comparison is implemented lets us do semantic versioning-style comparisons easily. For example, `(2, …
> Implement flexible version checking and make 'vercheck' default to True

- siliconcompiler/client.py
- siliconcompiler/core.py
- siliconcompiler/flows/fpgaflow.py
- siliconcompiler/tools/verilator/verilator.py
- tests/core/test_target.py
- tests/flows/test_tool_option.py
This change replaces most of our `sys.exit` calls with Python exceptions, because we want to make it easy to catch build errors within custom Python flows.
I left one `sys.exit` call in the `_haltstep` method, because the `_runtask` calls which it interrupts are typically run within a `multiprocessing.Process`. Raising exceptions in `_haltstep` would also make the command-line errors more verbose and less helpful, by printing an identical stack trace for every failed task in the flow.
> Raise exceptions instead of calling 'sys.exit', to facilitate using siliconcompiler as a Python library

- siliconcompiler/core.py
Some changes to the logger to make it look nicer and be more intuitive. This takes care of a couple cleanup tasks.
- Don't include job/step/index until we're in "run()". This prevents us
from display the default job name ("job0") when the user is eventually
going to set something else.
- Loop through all steps/indices in the current flowgraph so we size the
step and index columns appropriately. This prevents the columns from
being broken by long step names.
**Before**
```
| INFO    | job0    | ---          | -   | Pre-run log
| INFO    | job0    | ---          | -   | Checking manifest before running.
| INFO    | myjob   | import       | 0   | Waiting for inputs...
| INFO    | myjob   | reallyreallyreallylongstep | 0   | Waiting for inputs...
| INFO    | myjob   | import       | 0   | …
```
> Prettify logging

- requirements.txt
- siliconcompiler/core.py
We want to record peak memory usage as part of the metrics collected for each task.
The built-in [resource](https://docs.python.org/3/library/resource.html) library looked like a promising solution, but there were a couple of issues:
* It is not included in Windows installations of Python.
* It looks like the most detailed statistic that it  can provide is the maximum "Resident Set Size". That includes shared memory such as libraries which may be used by several processes without actually "belonging" to the process whose memory usage we are interested in.
The [`psutil`](https://pypi.org/project/psutil/) module can provide more comprehensive information about processes, and it appears to be fairly widely-used. It can report the "Unique Set Size" for a process and its children, which only …
> Record each task's maximum memory usage in metrics

- .github/workflows/wheels.yml
- docs/user_guide/installation.rst
Some versions of Python use an unsuitably old version of Pip, so we need
to provide a wheel to bootstrap the version on a disconnected machine.
> Add pip wheel to offline install bundle

- examples/aes/aes.sdc
- examples/benchmark/benchmark.py
- siliconcompiler/core.py
- siliconcompiler/pdks/asap7.py
- siliconcompiler/schema.py
- siliconcompiler/tools/openroad/openroad.py
- tests/core/data/defaults.json
- The runtask was not behaving nicely for large N. The min function was taking a tone of time due to the read_manifest step. During the runtask we don't need the heave checking that is available in the API, we can just access the dictionary directly. 
- Normalizing runtask sleep to not waste resources when tons of threads are running (hundreds).
- Removing read_manifest for critical merge steps in favor of dict copy.
- Normalizing openroad thread count based on task level parallelism
NOTE: Some of this work will get replaced by Noah's new run scheduler, but we should still merge the optimization method as a place holder. No need for read_manifest when we can just copy the dict.
> Optimizing runtask  

- examples/gcd/run_asap7.sh
- tests/flows/test_failure.py
- tests/flows/test_gcd_server_auth.py
- tests/flows/test_timeout.py
This change should fix the recent daily test failures.
Most of them were caused by my recent change to move from `sys.exit` to Python exceptions - sorry that I only checked the quick tests for that PR.
I believe that the ASAP7 GCD test was failing because of a missing 'wafersize' parameter, which is newly required for the 'asic' mode.
[I started an extra test run on this branch](https://github.com/siliconcompiler/siliconcompiler/actions/runs/2060655730) to verify that this will fix the daily test suite.
> Fix recent daily test failures

- siliconcompiler/pdks/skywater130.py
- siliconcompiler/schema.py
- siliconcompiler/tools/magic/sc.magicrc
- siliconcompiler/tools/netgen/sc_lvs.tcl
- tests/core/data/defaults.json
- We cannot assume that there is only one major runset file for modern nodes.
- While we had a list of files, there that really wasn't enough.
- We need to be able to refer to named runsets
- Note that the names used are tightly coupled with the tool and the flow, thus the pass through non-standardized runset names.
- The drc/lvs/erc are general enough classes to be standardized.
> Adding named runset feature to schema

- setup/install-openroad-rhel7.sh
A small fix needed to build recent versions of OpenROAD in RHEL7.
A lot of Boost's functionality is header-only, but OpenROAD has a new library dependency, so we need to build the whole project instead of just copying its headers.
> Fix Boost build in RHEL7 OpenROAD setup script

- examples/benchmark/scalability.py
- siliconcompiler/client.py
- siliconcompiler/core.py
- siliconcompiler/scheduler.py
- siliconcompiler/schema.py
- siliconcompiler/tools/echo/echo.py
- tests/core/data/defaults.json
- tests/core/test_env_schema.py
- tests/core/test_minmax.py
- tests/flows/test_tool_option.py
This PR implements an idea I had to refactor our parallelism/task management code. It is meant to take care of a couple things on our to-do list in one sweep, and I think it simplifies our code overall. The main thing it addresses is to make the scheduler graph-based rather than flooding the system with nodes that block until ready.
The proposed algorithm for launching tasks in `run()` is as follows:
- Create a dict `tasks_to_run` that maps each task to a list of its task dependencies
- Create an empty list `tasks_running` that lists each task that is currently active
- While either one of these lists is not empty:
- Iterate through `tasks_to_run`
- If any of them have any empty dependency list, launch the task, remove it from `tasks_to_run` and add it to `tasks_running`.
- Iterate …
> Proposal to refactor task management

- siliconcompiler/core.py
- siliconcompiler/schema.py
- tests/core/data/defaults.json
For backwards compatibility, this PR makes it so any version specifier that's missing an operator defaults to a '==' specifier.
> Make '==' default version spec operation

- examples/benchmark/scalability.py
- siliconcompiler/core.py
This PR tweaks the `read_manifest()` replacement from PR #954 by moving back to `read_manifest()`, with a 'partial' option that causes it to only merge the keys we care about.
It turns out the previous approach has a few functionality issues:
- It doesn't read data from steps/indices prior to a tasks immediate inputs, so the manifests don't store metrics cumulatively. 
- Since the json manifest has "default" keypaths pruned, doing a full copy in of an entry from this dictionary breaks the ability to go back and create more groups underneath dynamic keys. 
This new approach of doing a "partial" read_manifest() gets most of the performance benefit without the correctness pitfalls. The following data is collected by running `python examples/benchmarks/scalability.py parallel`. It constructs …
> Replace direct cfg merge w/ partial read_manifest

- siliconcompiler/core.py
- siliconcompiler/schema.py
- tests/core/data/defaults.json
- tests/flows/test_flowstatus.py
This PR fixes issue #651, the flowstatus issue that has been around for a while.
This PR makes two changes:
- Doesn't store flowstatus "pending" values in the manifest. Storing an explicit value for "pending" meant that our `_read_manifest()` calls wouldn't overwrite these values since they are called with clobber=False.
- Added a code block to write out the `status` dict into the schema on success. This takes care of a few edge cases where we have steps that don't merge into one.
I also added a test based on my reproduction code from the original issue. It runs a handful of graphs with 2 parallel place steps, where one fails and one succeeds. In each test case, it ensures that the flowstatuses for these place steps are recorded correctly.
It tests this graph with 3 steplists:
- …
> Fix flowstatus bug

- siliconcompiler/schema.py
- tests/core/test_scparam.py
This PR fixes a little bug I noticed where defvalues for list items are updated as the value is, since the value is pointing to the same object.
> Prevent defvalue lists from getting overwritten

- siliconcompiler/tools/klayout/klayout.py
- siliconcompiler/tools/magic/magic.py
- siliconcompiler/tools/netgen/netgen.py
- siliconcompiler/tools/openroad/openroad.py
- siliconcompiler/tools/surelog/surelog.py
- siliconcompiler/tools/yosys/yosys.py
- tests/examples/test_gcd.py
RE: https://github.com/siliconcompiler/siliconcompiler/pull/954#discussion_r837860771, this PR moves all the EDA report setup from post_process() to each tool driver's setup() function. This is more consistent with the input/output schema, and it is necessary now that we don't persist any mid-run changes to schema other than metrics/record/flowstatus.
> Move EDA report setup to tool setup() functions

- siliconcompiler/core.py
- siliconcompiler/templates/report/sc_report.j2
- tests/core/data/gcd.pkg.json
- tests/core/test_summary.py
- tests/flows/test_flowstatus.py
- tests/flows/test_tool_option.py
This PR fixes:
- "ERR" when running summary() on a chip with steplist. We changed this in #777 but I can't remember why, and I think we should probably go back.
- Missing report key (issue #932). This extra check might not be necessary once we swap report pointers to always be done in setup(), but it won't hurt for now.
- Display "(failed)" under metrics for tasks that error out, since they won't have metric values filled in (was causing KeyError).
I inserted some summary() calls into tests with weird steplists to try and catch these issues in CI.
> Fix summary/report generation issues

- siliconcompiler/core.py
RE: #969, this adds code to the top of _runtask() to clear out potentially stale record entries. Now we reset the records, metrics, and flowstatus, so I think we should be okay to close that issue.
> Clear record schema in _runtask()

- setup/docker/Dockerfile
- setup/install-surelog.sh
It looks like GitHub recently changed its security policy to block some methods of cloning git:// addresses. One of Surelog's dependencies includes a 'git clone' call that points to such a repository, so our surelog install script has started to fail.
It looks like the solution is to force Git to use https:// instead of git://. It's a little tricky to force that setting without modifying the system's Git configuration, but I think the easiest approach is to override the default `~/.gitconfig` search path in `install-surelog.sh`.
> Fix Surelog install script

- siliconcompiler/core.py
- siliconcompiler/schema.py
- tests/core/data/defaults.json
- tests/core/data/gcd.pkg.json
- Optional field in each parameter.
- Previously this informationw as embedded in the help of each parameter.
- Embedding the unit inside the parameter avoids the risk of unit contention.
- Future proofs settings by decoupling the units of each parameter from all others.
> Adding units to schema parameters as appropriate

- siliconcompiler/core.py
Small bug I ran into: even if the directory exists, we still want to set a task to pending if it is in our step/index list.
> Fix bug in flowstatus reset

- siliconcompiler/core.py
- siliconcompiler/server.py
Was going through the optimize runtask PR to make sure I didn't miss anything that needed to be handled in the scheduler PR. I didn't find anything like that, but I am curious if we can undo the 'flowstatus' change with a TODO on it? Doesn't seem necessary to me, and tests pass without it (not sure if they weren't before).
Also bundled in some other small non-controversial cleanup commits.
> Some minor cleanup

- siliconcompiler/core.py
- tests/flows/test_steplist.py
This PR implements a `check_manifest()` check for ensuring that a steplist is valid. This will print a clean error early on if you try to run a flowgraph with a steplist that doesn't work, e.g.
```python
...
chip.set('steplist', ['syn'])
chip.run()
```
Gives you:
```
| INFO    | job0  | --         | -  | Checking manifest before running.
| ERROR   | job0  | --         | -  | syn0 relies on import0, but this task has not been run and is not in the current steplist.
| ERROR   | job0  | --         | -  | Check failed. See previous errors.
```
> Insert valid steplist check

- siliconcompiler/schema.py
- tests/core/data/defaults.json
Looks like tests broke after the fix-daily-tests got merged, since there was a new metric 'totaltime' added, and we need to get rid of `require` for metrics now. This commit should fix things up!
> Remove requirement for totaltime metric

- examples/benchmark/scalability.py
- siliconcompiler/core.py
- siliconcompiler/tools/echo/echo.py
- tests/core/test_summary.py
- tests/flows/test_performance.py
This PR fixes a performance bottleneck in `check_manifest()`. From the commit:
This fixes a performance problem where each task has to incur the
overhead of checking an entire flowgraph for really large graphs. Since
those sorts of things are static, they only need to be checked once in
run(), and the check_manifest() calls inside _runtask() can focus on
dynamic checks.
I also started simplifying the benchmark code I was using and added it to CI. Now that our code is faster I think we can probably get rid of a lot of the complexity in the monitored subprocess approach, but I'm planning on handling that later. For now, I think it'll be nice to have some tests running to flag major performance regressions.
Also, an unrelated test that was meant for a different PR ended up in here (for …
> Fix check_manifest() performance bottleneck and add performance tests to CI

- MANIFEST.in
- examples/gcd/gcd_skywater.py
- setup.py
- siliconcompiler/checklists/oh_tapeout/oh_tapeout.py
- siliconcompiler/core.py
- siliconcompiler/schema.py
- siliconcompiler/targets/skywater130_demo.py
- siliconcompiler/tools/magic/magic.py
- siliconcompiler/tools/netgen/netgen.py
- tests/core/data/defaults.json
- tests/core/test_checklist.py
- tests/core/test_setget.py
- tests/examples/test_gcd.py
This PR implements checklist functionality. Main changes:
- Add `load_checklist()` function to dynamically load checklist modules
- Re-implement `check_checklist()` based on the algorithm we discussed offline
- Items that can be automatically checked must meet criteria for all associated tasks (unless waivers exist), and EDA reports must exist for all criteria
- Items that are not automatically checked must have at least one report (manually added)
- If `check_ok` is True, items must also have 'ok' parameter checked
- Re-architect the 'checklist' schema slightly to enable automatic checks of multiple tasks
- I also got rid of the 'metric' subkey under 'report' to simplify things a bit, since we seemed okay with it being a catch-all bucket. However, I can add that back if you don't think …
> Implement checklists

- siliconcompiler/core.py
This PR fixes `read_manifest()` so that it will update the history of the current chip object if the manifest contains history information.
Previously, calling `read_manifest()` on a manifest with something in the history would return a whole bunch of errors:
```
| ERROR   | Get keypath [history,job0,steplist] does not exist.
| ERROR   | Get keypath [history,job0,steplist] does not exist.
| ERROR   | Get keypath [history,job0,steplist] does not exist.
| ERROR   | Get keypath [history,job0,steplist] does not exist.
| ERROR   | Get keypath [history,job0,target] does not exist.
| ERROR   | Get keypath [history,job0,target] does not exist.
| ERROR   | Get keypath [history,job0,target] does not exist.
| ERROR   | Get keypath [history,job0,target] does not exist.
```
and would not populate the …
> Update history in read_manifest()

- tests/flows/test_performance.py
I think these caused the daily tests to start failing. Seems like they're much slower on the test runner, so we'd need to bump the timeout/adjust the thresholds in the assert statements. We should probably skip these to get back to green in the meantime.
> Skip performance tests in CI for now

- siliconcompiler/tools/openroad/openroad.py
It looks like we can update our version of OpenROAD to include some recent power grid generation improvements without changing our tcl scripts.
I tested the newer version on Ubuntu 20.04 and RHEL7.9 with our heartbeat and ZeroSoC examples, and everything completed successfully.
I've also installed the newer version on our CI runner so that the tests pass, but we can revert that if problems crop up.
> Update openroad version

- docs/_ext/dynamicgen.py
This change should fix the failing docs build in `pacman` branch. The AppGen extension expected app help output to be all ASCII, but 'sup' uses unicode characters for representing the directory structure.
> Decode non-ASCII stdout output in AppGen

- siliconcompiler/core.py
- tests/core/test_sup.py
This change adds an `upstream` parameter to track prior dependencies in sup's recursive `_find_deps` function. It should catch circular imports by throwing an error if the system encounters a dependency which is currently being processed.
There's also a unit test to verify that it works in a simple "A depends on B, B depends on A" situation.
This should be applied to #997 if it looks good; I think merging it into the `pacman` branch should accomplish that.
> Add a sup error for circular imports

- docs/_ext/common.py
- docs/_ext/dynamicgen.py
- docs/_ext/schemagen.py
- docs/user_guide/records.rst
- docs/user_guide/tools.rst
- siliconcompiler/core.py
This PR makes a few enhancements to our documentation, all related to linking to the schema reference manual.
This is the simplest change. Added this due to feedback that if you just look at the API reference for these functions, it's unclear what valid arguments would be.
Now, the entries in the "Keypath" column of the tables in the tools/pdks/flows/targets/libs directory pages are clickable links that take you to the relevant entry in the schema docs.
E.g. Clicking here:
takes you here:
Following on the previous change, I also added a new inline command (or "role" as Sphinx calls them) that lets you easily insert links to the schema reference manual in prose. I haven't gone through and changed everything to use this yet, but I included a few examples in this PR.
For example, if you …
> Enable linking to schema reference manual throughout docs

- siliconcompiler/core.py
- siliconcompiler/schema.py
- tests/core/data/defaults.json
- tests/tools/test_ghdl.py
- tests/tools/test_icarus.py
- tests/tools/test_klayout.py
- tests/tools/test_openroad.py
- tests/tools/test_surelog.py
- tests/tools/test_verilator.py
- tests/tools/test_yosys.py
This PR removes the single-step flow logic from the top of `run()`, one of our cleanup backlog items. I replaced it with a helper function to take care of some of the boilerplate required when creating a single-step graph (import no-op, default metric weights).
A consequence of this change, however, is that we will no longer be able to concisely run a single tool step through the CLI. Before, we supported:
`sc foo.vhdl -flow icarus -arg_step compile`
Now, we'd have to do something very verbose like:
```bash
sc foo.v \
-flow icarus \
-flowgraph_tool "icarus compile 0 icarus" \ 
-flowgraph_tool "icarus import 0 nop"  \
-flowgraph_input "icarus compile 0 (import, 0)" \
-flowgraph_weight "icarus compile 0 errors 0 " \
etc...
```
I wanted to get thoughts on this before finalizing this change. …
> Remove single-step flow logic from run()

- siliconcompiler/leflib/__init__.py
This prevents it from being captured in docs when processing app help strings.
> Print leflib warning to stderr

- examples/gcd/run.sh
- siliconcompiler/core.py
- siliconcompiler/schema.py
- tests/core/data/defaults.json
- tests/tools/test_surelog.py
This PR updates the ['eda', tool, 'path'] behavior to prepend the provided path to the system path and perform a search, rather than always hardcoding the provided path to the executable name.
In addition to this change, I made two tweaks to facilitate review of which executable is running:
- Logging the directory used to run the exe alongside the version
- Adding an entry to 'record' that stores the full path to the exe
Before:
```
| INFO    | job0  | syn        | 0  | Checking executable. Tool 'yosys' found with version '0.13+15'
| INFO    | job0  | syn        | 0  | Running in /home/noah/code/siliconcompiler/build/gcd/job0/syn/0
| INFO    | job0  | syn        | 0  | yosys -c /home/noah/code/siliconcompiler/siliconcompiler/tools/yosys/sc_syn.tcl
| INFO    | job0  | syn        | 0  | …
```
> Fix 'path' parameter behavior

- siliconcompiler/core.py
- tests/designs/test_picorv32.py
This PR fixes some of our nightly tests I broke yesterday.
- In PR #1003 I switched a line in the `replay.sh` generation logic to use `shlex.join()`, since I incorrectly thought that the reason I didn't use `shlex.join()` originally is that it doesn't work for Windows. Turns out the fundamental problem was that it's actually only in Python >=3.8. I reverted to the old version of this line to be safe.
- I missed updating a test (picorv32) in PR #1001 that used the old single-step flow interface.
> Fix failing daily & wheel tests

- docs/_ext/common.py
- docs/_ext/dynamicgen.py
- docs/_ext/requirements.py
- docs/conf.py
This PR makes a couple changes to fix up some issues we had with long autogenerated table contents overflowing table cells.
> Prevent text from overflowing tables in PDF docs

- siliconcompiler/core.py
- siliconcompiler/schema.py
- tests/core/data/defaults.json
- tests/flows/test_resume.py
This PR implements a 'resume' option that allows you to re-run a job starting with the last failing step. One key decision was to make a step be considered failing (and be re-run) only if all its indices fail. This simplifies handling some edge cases, and if a user needs a different behavior, they can always manually re-run things using the steplist.
> Implement 'resume' option

- siliconcompiler/core.py
Add back is_posix to shlex.split() calls in _makecmd
I got a little too aggressive when clearing out the multi-platform
replay script code. We need to properly handle different platforms for
actually creating the command itself!
Verified back to green: https://github.com/siliconcompiler/siliconcompiler/actions/runs/2265960443
> Fix wheels tests

- siliconcompiler/schema.py
This PR adds a fix for issue #976 into the schema_rearchitect branch. This is another thing that I figure is worth fixing if we're going to refactor everything.
As stated in that issue, I don't think it makes sense to set up metric goals inside the metric schema itself now that we have multiple flows. It seems more consistent to set up the goals alongside the weights. I think this could also lets us get rid of the "group" free key in the metric keypath, since I'm not sure what other categories we'd want to put there besides "goal" and "real".
I am still going back and forth on whether the "flowgraph" metirc-related keypaths should be:
```
'flowgraph', flow, step, index, 'weight', metric
'flowgraph', flow, step, index, 'goal', metric
```
or
```
'flowgraph', flow, step, index, metric, …
```
> Specify metric goals in flowgraph

- docs/user_guide/examples/flowgraph_doe.py
- docs/user_guide/faq.rst
- examples/heartbeat_padring/build.py
- examples/heartbeat_padring/floorplan_build.py
- examples/oh_experiments/feedback_loop.py
- siliconcompiler/client.py
- siliconcompiler/core.py
- siliconcompiler/pdks/asap7.py
- siliconcompiler/pdks/freepdk45.py
- siliconcompiler/pdks/skywater130.py
- siliconcompiler/scheduler.py
- siliconcompiler/schema.py
- siliconcompiler/server.py
- siliconcompiler/tools/template/template.py
- tests/flows/test_flowstatus.py
- tests/flows/test_resume.py
- tests/flows/test_steplist.py
- tests/flows/test_tool_option.py
- tests/tools/test_klayout.py
This PR adds some of the small schema tweaks from our backlog into the schema_rearchitect branch. I figure now is a good time to knock these out of the way since we're refactoring the entire thing anyway. Let me know if you don't want to do any of these changes anymore and I can remove it from the PR:
- Rename `'variable'` to `'var'` (in `['pdk', ...]`, `['tool', ...]`, and `['asic', ...]`)
- Rename `['option', 'dir']` to `['option', 'build']`
- (my 2 cents on this one is I think a rename is good, but not 100% sure about 'build'. Maybe 'builddir' or 'outdir'?)
- Remove `<job>` from `['jobinput', ...]`
> Implement schema changes from todo list in schema_rearchitect

- tests/examples/test_microwatt.py
I noticed our daily CI tests started timing out after #961 got merged (which adds synthesis). It takes ~35 minutes on my machine to run. I'd say we should skip it for now to get these tests back to green, and perhaps switch over to just running the Verilog we get out of GHDL through a linter or something (since we run synthesis mainly to check that it's OK).
> Skip Microwatt test: it causes CI to time out

- siliconcompiler/scheduler.py
A few parameters in scheduler.py need updating to work with the new schema. We can also remove the active/error tracking bits now that each task's status is tracked in the schema.
> Update scheduler.py to account for recent schema changes.

- .github/workflows/wheels.yml
This is what made the Wheels CI turn red. Tests are passing, it just failed because it was trying to run a test that doesn't exist (test got moved)!
> Update path to test_show.py in Wheels CI

- siliconcompiler/core.py
- siliconcompiler/schema.py
- tests/core/data/defaults.json
- tests/core/test_create_cmdline.py
~I think this default value is not legal, based on the docs there should be no 'O' prefix.~
Update: per our discussion this morning, seems like the intended behavior is for the optmode to be stored with an 'O' prefix. I added a special case to the `create_cmdline()` function to handle this, updated the docs to reflect the intended behavior, and added a test case.
> Change CLI behavior to store optmode with 'O' prefix

- siliconcompiler/apps/sc_run.py
- siliconcompiler/apps/sc_show.py
- siliconcompiler/core.py
- siliconcompiler/schema.py
- tests/core/data/defaults.json
- tests/core/test_create_cmdline.py
In preparation for adding filetype inference to create_cmdline() in a future PR, I took a refactor pass to fix some of our backlog CLI items.
**Improvements**
1: Simplified code by constructing argparse 'dest' key directly from keypath. This eliminated the need for `switchmap` and the logic for constructing `dest`.
2: Made `switchlist` based on actual switches. The docstring said that switchlist should match switches without the '-', but the existing behavior didn't match this. I also tweaked the spec to require the '-', since treating the hyphen specially seems inconsistent given we have keys without hyphens (e.g. `+libext+`).
3: Fixed #996: if a keypath has N 'default' keys, the logic now splits out only the first N words from the value provided on the command line, and treats the …
> Refactor create_cmdline()

- examples/blinky/run.sh
- examples/fibone/run.sh
- examples/gcd/run.sh
- examples/gcd/run_asap7.sh
- examples/gcd_chisel/run.sh
- examples/gcd_hls/run.sh
- examples/heartbeat/run.sh
- siliconcompiler/apps/sc.py
- siliconcompiler/apps/sc_show.py
- siliconcompiler/core.py
- tests/core/test_create_cmdline.py
This PR adds a parameter to `create_cmdline()` that allows for configurable filetype inference of positional source arguments. This gives `sc` a CLI more similar to pre-0.9, where sources can be provided directly without having to prefix them with a flag. In fact, the interface is even cleaner now, since we have a mechanism to provide things like SDCs, DEFs, etc. directly as well!
The configurable `input_map` allows apps to set up mappings in a context-dependent manner. For example, `sc` maps all filetypes accepted by the asicflow and fpgaflow, whereas `sc-show` maps filetypes that are displayable in KLayout.
> Add filetype inference to command line apps

- docs/_ext/schemagen.py
- docs/reference_manual/schema.rst
- docs/user_guide/libraries.rst
- docs/user_guide/quickstart.rst
- siliconcompiler/schema.py
- tests/core/data/defaults.json
This PR fixes up some issues with the docs.
- Follow-up tasks from 0.9 upgrade
- Get rid of "root" in Schema reference manual: all top-level items are now directly under "1.3 Parameters". 
- Get rid of empty "history" and "library" sections, and replace with a new prose section describing these two keypaths.
- Document min/typical/max for parameters that use this format under datasheet schema
- Tasks from public issues
- #1022: specify that user must clone repo/set up SCPATH to run quickstart locally (thanks @arlted!)
- #1035: fix errors in library user guide (thanks @ValeriiPlumerai!)
> Docs fixups

- siliconcompiler/targets/asap7_demo.py
- siliconcompiler/targets/freepdk45_demo.py
- siliconcompiler/targets/skywater130_demo.py
Small cleanup thing: use `clobber=False` when setting ['option', 'flow'] for targets with more than one option, since a user might set it before `load_target()` is called.
I think we can skip `clobber=False` for targets that only have once choice.
> Standardize clobber=False for flows in targets

- siliconcompiler/core.py
- siliconcompiler/tools/openroad/sc_constraints.sdc
- siliconcompiler/tools/openroad/sc_floorplan.tcl
- tests/core/test_write_manifest.py
This PR makes a couple changes to how TCL code is generated by `write_manifest()`. It addresses a few problems:
**Escaping strings**
We weren't escaping any special characters in strings besides semicolons. This became problematic when I had a multi-line value for a field. This caused a tool to error out after sourcing the sc_manifest.tcl file, because SC generated invalid TCL like this:
```tcl
[dict set $sc_cfg package description [list Description line 1
Description line 2]]
```
Along with this, spaces and special characters like '$' would have resulted in issues. The best solution I found was to wrap the entire string in quotes, and escape a few special characters, based on  https://stackoverflow.com/a/70082148 (and verified by looking at the TCL spec).
**Dump tuple as list**
We were …
> Enhance TCL manifest generation

- siliconcompiler/core.py
- tests/core/test_write_manifest.py
This PR fixes up CSV manifest export. The existing implementation was in pretty good shape, but the output was missing newlines. I decided it might be best to refactor the function to use the built-in CSV library though, since that has configurable logic for switching delimiters, quoting values that contain special characters, etc.. For now, I'm just using the default options, which seem to work well in both LibreOffice and Google Sheets.
> Fix up CSV manifest export

- siliconcompiler/apps/sc_show.py
We have 'job0' hardcoded in the sc-show app, which prevents it from working if the job name is overridden.
> Use jobname parameter instead of 'job0' in sc-show

- siliconcompiler/core.py
- siliconcompiler/templates/report/sc_report.j2
This PR makes SC's generated HTML report a self-contained file that will look the same even if it is copied elsewhere in the filesystem (or sent to someone else).
This required two changes:
- Embedding the bootstrap CSS/JSS
- Embedding the layout preview as a base64 encoded image
I think this is a nice change, the main downside is that this makes the file a bit heavier. However, it looks like the size of the HTML dump of the entire manifest (for the tree viewer) dominates the size - these changes only result in an increase from 3.5MB->3.9MB for the GCD example.
> Make report self-contained

- siliconcompiler/core.py
Just a small API tweak that I think is convenient -- make chip.archive() return the full path to the generated tarball (useful for scripts that call chip.archive() and then want to do something with the result).
> Return filepath from chip.archive()

- siliconcompiler/core.py
- siliconcompiler/schema.py
- tests/core/data/defaults.json
I realized we should probably be recording the final set of CLI arguments used to drive a tool for provenance purposes. The options parameter in the tool schema isn't complete, since we generate arguments on the fly using `runtime_options()`.
> Add final tool CLI options to record schema

- siliconcompiler/tools/verilator/verilator.py
- tests/flows/data/heartbeat_tb.cpp
- tests/flows/test_verilator_sim.py
This PR fixes up the Verilator "compile" step, working towards supporting a Verilator-based simulation flow. Thanks to @sgherbst for trying out this functionality and providing feedback!
One design decision I wanted to highlight was making the input to "compile" an already preprocessed and pickled Verilog file, rather than reading input/include dirs/defines from the schema. This might seem odd given that Verilator can handle the preprocessing itself, but I did this for a few reasons:
1) We have standardized on Surelog for input preprocessing and elaboration, so a simulation pipeline that goes Surelog --> Verilator ensures any Surelog-related quirks that would be present in the implementation RTL will also be present in the simulation RTL. The Verilator driver still supports being used for …
> Fix Verilator compile support, clean up driver

- siliconcompiler/core.py
- siliconcompiler/flows/asicflow.py
- siliconcompiler/tools/openroad/openroad.py
This PR contains a few changes to support customized SiliconCompiler flows which use OpenROAD.
It moves some logic behind `if flow == 'asicflow'` checks, fixes a couple of small metric-parsing issues, and fetches the output DEF filepath from the schema.
I'm open to suggestions on the flow name checks; it may not be unreasonable to expect flows to use a specific naming convention for files used with certain tools.
> Update OpenROAD tool file to better support non-default flows

- Changes
A couple extra things are going to be caught in 0.9.1 since we didn't release last week. @aolofsson can we merge this before the other open PRs? Then I can push the button on the release.
> Update 0.9.1 changelog

- siliconcompiler/core.py
- siliconcompiler/tools/openroad/openroad.py
- tests/core/test_check_manifest.py
This PR modifies the flowgraph I/O checker to allow tool tasks to have more than one input. As far as I can tell, the logic in `_runtask()` supports this (it works intuitively -- the outputs of each input task are combined into the inputs of the task at hand). However, the checker did not, and would output a nonfatal error.
I've updated the checker to no longer consider this an error, and also properly check the inputs (so it will throw an error if there are  duplicate input files, and it will throw an error if the sum total of all inputs does not provide all the files a task needs). I added tests for these cases.
I also bundled a small tweak to the OR post_process function that checks that the [... 'output' ...] keypath is valid. This cleans up the other nonfatal error we're seeing in …
> Allow tool tasks to have more than one input

- siliconcompiler/client.py
- siliconcompiler/core.py
- siliconcompiler/schema.py
- siliconcompiler/tools/bambu/bambu.py
- siliconcompiler/tools/bluespec/bluespec.py
- siliconcompiler/tools/chisel/chisel.py
- siliconcompiler/tools/echo/echo.py
- siliconcompiler/tools/ghdl/ghdl.py
- siliconcompiler/tools/icarus/icarus.py
- siliconcompiler/tools/icepack/icepack.py
- siliconcompiler/tools/klayout/klayout.py
- siliconcompiler/tools/magic/magic.py
- siliconcompiler/tools/netgen/netgen.py
- siliconcompiler/tools/nextpnr/nextpnr.py
- siliconcompiler/tools/openfpgaloader/openfpgaloader.py
- siliconcompiler/tools/openroad/openroad.py
- siliconcompiler/tools/surelog/surelog.py
- siliconcompiler/tools/sv2v/sv2v.py
- siliconcompiler/tools/template/template.py
- siliconcompiler/tools/verilator/verilator.py
- siliconcompiler/tools/vivado/vivado.py
- siliconcompiler/tools/vpr/vpr.py
- siliconcompiler/tools/xyce/xyce.py
- siliconcompiler/tools/yosys/yosys.py
- tests/core/data/defaults.json
- tests/examples/test_gcd.py
- tests/tools/test_yosys.py
I think the current behavior of `['tool', <tool> ,'continue']` is unideal. It's necessary in some cases because your tool produces nonfatal errors, but even in these cases I think you don't want the flow to continue running if the tool errors out with a nonzero status, since in that case future steps are probably pretty likely to fail.
This PR proposes the simplest possible change, which is to always kill the flow if the tool exits with a nonzero status. Another proposal that I'd be happy to implement would be to make 'continue' take a few possible values, something like:
- "never": always quit on any error condition
- "nonfatal": only quit on fatal errors (always continue if tool quits successfully)
- "always": flow always continues
> Adjust behavior of ['tool', <tool>, 'continue'] to always fail on fatal error

- siliconcompiler/tools/klayout/klayout.py
- siliconcompiler/tools/yosys/yosys.py
This change relaxes a couple of checks in the yosys and klayout tool drivers, for custom flows such as the ORFS scripts. It is similar to #1049.
One downside of using the step name to set KLayout's default I/O values is that `sc-show` looks in `export/` for the final GDS file. So if we use a custom step name for the final GDS-streaming step, we need to symlink that task directory to `[job_dir]/export/` in order to support the simplified `sc-show -design [...]` syntax.
> Make the yosys and klayout tool drivers less strict, to accommodate custom flows.

- siliconcompiler/tools/yosys/yosys.py
Our yosys tool driver erroneously reports synthesis errors for the tinyRocket OpenROAD-flow-scripts example. It turns out the errors are stemming from our error-checking regex flagging some bus signals called "TSError" in the synthesis logs.
"^ERROR" seems like a better pattern for the yosys logs; it may not be universal, but when I tried inducing a simple error in a yosys tcl script, I got the following output:
`ERROR: Option -top requires an additional argument!`
> Update yosys error regex

- examples/heartbeat_padring/build.py
- examples/heartbeat_padring/floorplan_build.py
This PR fixes the new daily test failures. It turns out there was a nonfatal KLayout error in the heartbeat_padring builds:
```
[ERROR] LEF Cell 'sky130_fd_pr__gendlring__example_559591418081' has no matching GDS/OAS cell. Cell will be empty
```
With the change to make error regexes meaningful metrics-wise, this caused the flow to stop prematurely. I fixed this by making SC continue despite the error by adding `chip.set('option', 'flowcontinue', True)`. 
Note: I haven't re-run daily tests to avoid bogging down the runner, but this fixes the test for me locally. Github is also being a little odd for me this morning, and for some reason it's only run one of the tests (looks like Github actions is having service issues: https://www.githubstatus.com/).
> Set 'flowcontinue' on heartbeat_padring top level

- Changes
- docs/user_guide/examples/heartbeat.v
- siliconcompiler/_metadata.py
- siliconcompiler/apps/sc.py
- siliconcompiler/targets/skywater130_demo.py
- siliconcompiler/tools/klayout/klayout_show.py
A bit of a hodge-podge PR, with all the small things we discussed today:
- Change `sc` app to use Skywater as default target
- Also made the default coremargin smaller, since it was particularly large compared to the small heartbeat die
- Made `sc-show` use a dark background for KLayout
- Reverted the copy of heartbeat.v in the user guide directory back to a real file from a symlink, in order to fix our business cards...
- Release notes and version bump to prep for a 0.9.2 release
> Prepare for 0.9.2 release

- siliconcompiler/core.py
There's a non-ASCII character (emdash) in the Bootstrap CSS file that gets inlined into our HTML report: https://github.com/siliconcompiler/siliconcompiler/blob/main/siliconcompiler/templates/report/bootstrap.min.css. 
On systems where the default encoding is UTF-8, this isn't a problem. However, when the default encoding is something else, the `wf.write(...)` call may raise a `UnicodeEncodeError`. Hardcoding the encoding to UTF-8 should fix this problem.
Thanks to @arlpetergadfort for reporting and finding the root cause of this issue! Closes #1072.
> Hardcode UTF-8 encoding for HTML report

- examples/heartbeat_caravel_wrapper/build.py
Small issue I noticed when I went to run this myself - I think the steplist needs "import" added.
> Fix missing 'import' in Caravel example steplist

- .github/workflows/wheels.yml
Looks like something must have changed on the MacOS Github environment that makes this directory already exist (causing the lack of `-p` flag to cause the `mkdir` command to fail).
This PR fixes the breakage. Manual run to verify: https://github.com/siliconcompiler/siliconcompiler/actions/runs/2680480664 (I think the error here is transient)
> Fix wheels build

- siliconcompiler/core.py
- tests/core/test_check_manifest.py
This PR fixes a `check_manifest()` bug when checking a run that uses a steplist to re-run a task that joins 2+ other tasks. The logic that checks what inputs the task will receive needs to filter out the manifest (since this isn't copied forward), otherwise the checker complains that the task will receive a manifest from both.
Also a couple other small changes I noticed:
- Helpful error message when you forget ['option', 'flow']
- We don't need to quit early with a steplist length 1, it's still useful to check that a single node receives the required inputs
Closes #1077
> Filter out manifests when checking flowgraph I/O

- setup/install-surelog.sh
@jessimd pointed out a couple problems with the Surelog install script:
- Requires running from SC root
- Missing sudo on `make install`
install-openroad.sh script has a little trick to make sure the script is runnable from any location, and most of the scripts explicitly include sudo when run. These changes makes Surelog consistent with other scripts.
> Make Surelog install script consistent w/ OpenROAD

- siliconcompiler/core.py
This PR fixes a daily test regression caused by #1093.
Eliminating the `len(steplist) < 2:` check in `_check_flowgraph_io()` revealed that this function doesn't check that an input tasks' directory actually exists.
> Fix regression in check_manifest()

- siliconcompiler/core.py
Sometimes it is necessary to use different versions of the same tool for different tasks. Our current `replay.sh` scripts will not work in that case, unless we include the value of the `$PATH` variable from when the task was originally run.
> Set PATH env var in the replay script even if 'path' parameter is not defined.

- siliconcompiler/server.py
I noticed these lines while trying to debug a test failure in my last PR. They weren't relevant, but they gave me pause - I don't think they're needed anymore. The inputs will be automatically resolved to the right directory by `find_files()` anyways.
Seem ok to delete?
> Don't overwrite ['input', 'verilog'] on remote

- siliconcompiler/core.py
- tests/core/test_setget.py
I've run into a few situations where it has been difficult to debug the source of an error, because a generic exception is thrown at [this line](https://github.com/siliconcompiler/siliconcompiler/blob/fcbf3f7f75b786f0577311fc0714d27db0b1faa5/siliconcompiler/core.py#L796) in a `chip.get` or `chip.getkeys` call:
keypathstr = ','.join(keypath)
The errors typically come from a `None` value in the keypath which gets passed into the method, along the lines of:
TypeError: sequence item 1: expected str instance, NoneType found
Usually, this happens because a previous `chip.get` call received a value of `None` when the build script was expecting a valid string. The easiest way to observe this kind of error is:
import siliconcompiler
siliconcompiler.Chip('my_design').run()
Tracking down the …
> Improve error handling for some kinds of chip.get / chip.getkeys failures.

- docs/user_guide/tools.rst
- examples/heartbeat_caravel_wrapper/build.py
- examples/heartbeat_caravel_wrapper/flows/mpwflow.py
- examples/heartbeat_caravel_wrapper/tools/addvias/addvias.py
- examples/heartbeat_caravel_wrapper/tools/fixdef/fixdef.py
- siliconcompiler/core.py
This PR implements support for pure-Python tools, a feature we talked about a while back when discussing how to more cleanly port other flows into SC. With both the ORFS and Caravel flows, we've noticed cases where we need to do some intermediate processing on files being passed around the flow. The existing options we explored each have flaws:
- Modify `pre_process()` or `post_process()` in a tool driver
- This isn't great since we want to keep these functions as flow-agnostic as possible, so that we can reuse the tool drivers broadly. Forking the tool drivers per-flow isn't a great solution either, since this results in lots of code duplication.
- Break the run into multiple `run()` calls that each use a partial steplist, with Python logic in between
- This is what the Caravel example …
> Implement basic support for pure-Python tools

- siliconcompiler/core.py
- siliconcompiler/tools/chisel/chisel.py
- tests/core/test_check_manifest.py
This PR is a simple proposal to fix issue #1063. 
It makes two changes:
- Only collect files for remote runs
- Don't copy collected files from `import/0/inputs/` to `import/0/outputs/`
This was a pretty easy change, since `find_files()` automatically falls back to searching the original file path for any copied file that's not in the file collection directory.
Here are the before and after results.
**Before**
```console
$ ls build/gcd/job0/import/0/inputs/
gcd_0a998a746037a840df8d7f2133c57f4846e3405f.v  gcd_9fb1319e7d576ade53f9b17ec8e05417afa27bca.sdc
$ ls build/gcd/job0/import/0/outputs/
gcd_0a998a746037a840df8d7f2133c57f4846e3405f.v    gcd.pkg.json
gcd_9fb1319e7d576ade53f9b17ec8e05417afa27bca.sdc  gcd.v
$ cat build/gcd/job0/import/0/replay.sh
#!/bin/bash
surelog -parse …
```
> Simplify collection of input files

- siliconcompiler/tools/klayout/klayout_export.py
The file collection change introduced a regression in the heartbeat padring example. Turns out KLayout's default behavior is to automatically try to read any LEF files that are next to the input DEF. Now that the input isn't being read from imports, KLayout is reading the LEF files next to it in the original source directory and throwing an error due to duplicate macros when it reads in the LEFs we pass explicitly.
The solution is to disable this behavior, since we always pass in LEFs explicitly.
> klayout: don't automatically read LEFs next to DEF

- siliconcompiler/core.py
- siliconcompiler/schema.py
- tests/core/data/defaults.json
- tests/core/test_jobincr.py
This PR fixes up some issues with ['option', 'jobincr'] and adds a test for it.
Changes:
- No more blanket `try... except` wrapper. This was hiding the fact that this block was writing to a keypath that no longer exists :). Inserted more specific error checking logic instead.
- Run before `_init_logger()`, otherwise pre-runtask logs use old jobname in messages
- Strip off any digits from existing jobname to handle case where the existing name includes digits already (`job0`) or not (`job`)
The behavior now matches the existing schema help string, including appending "1" if the existing build directory does not end in any digits.
> Fix ['option', 'jobincr']

- siliconcompiler/core.py
This PR implements an old TODO to merge in manifests from all "leaf" tasks at the end of run() (i.e. any task that doesn't have any further dependencies).
This is important to:
a) make the summary nice
b) capture all final metrics in one manifest
Even though we have had an informal requirement that all flows should merge into a final 'export' task, this has only been loosely followed, and it also doesn't help if someone runs a steplist that doesn't include the final export task. 
We already have the relevant helper function implemented from a previous fix to summary(), so this was a pretty easy change.
Demo of the difference this makes -
Example flow:
Summary before:
```
import0        syn0       syn1     floorplan0
errors               0            0         ERR           0    
warnings …
```
> Merge in manifests from all leaf tasks

- siliconcompiler/templates/report/sc_report.j2
This change builds on the tree-view manifest visualization which @nmoroze recently added to our auto-generated HTML reports. It adds a way for users to edit signoff checklist items, including checkboxes for the boolean "ok" parameters, and free-form text entry for the "report" parameters.
The "report" checklist parameters are currently intended as a list of files which are associated with a given signoff item, but it seems like we should have a way for users to enter arbitrary metadata for each item. I can think of two easy ways to address that:
* Change the `report` parameter type from `[file]` to `[str]`, or
* Add a new checklist parameter for free-text input.
> HTML report: add basic editing functionality for signoff checklists.

- Changes
- siliconcompiler/_metadata.py
- Bump version number
- Add change notes
Note: this Changelog assumes PR #1107 is merged for this release, but I can update these if that is no longer the plan.
> Prepare for 0.9.3 release

- siliconcompiler/schema.py
- siliconcompiler/tools/openroad/sc_apr.tcl
- siliconcompiler/tools/yosys/syn_asic.tcl
- tests/core/data/defaults.json
- Address the scenario of having multiple different corners applied to a single scecnario, which is needed in cases like multi-voltage IO. For example, we might have multiple IO models, one for 0.9V internal and 1.8V external, or 0.9V internal and 1.72V external. With a large number of IO standardards and on chip voltages, we need a way to group these library corners together within a single scenario.
> Making libcorner a list

- examples/heartbeat_caravel_wrapper/build.py
- siliconcompiler/tools/klayout/klayout_export.py
- siliconcompiler/tools/openroad/sc_floorplan.tcl
This PR fixes two issues with our Caravel wrapper example:
* While merging the heartbeat/Caravel example into main, I deleted a line in `sc_floorplan.tcl` which set custom pin sizes. The default sizes ended up triggering some metal grid offset DRCs in the MPW precheck scripts, so I added a way to set I/O signal sizes from the schema and added a fix to the example build script.
* When I was inspecting the final GDS results, I noticed that the top-level build was only adding vias between the PDN grid and standard cell rails outside of the core macro area. This did not cause DRC or LVS failures because the power signals were technically connected to the correct nets, but I would imagine that the voltage drop caused by the missing power vias would cause problems in a real chip. Fortunately, …
> Fix pin sizes and PDN vias in Caravel wrapper example

- docs/_ext/schemagen.py
- siliconcompiler/core.py
- siliconcompiler/sphinx_ext/dynamicgen.py
This PR contains a slew of changes that I think should be in the next release. It got a bit more varied than I originally intended, let me know if you want me to break it up.
Summary:
- Fix `find_files()` behavior with job argument (fixes #1122)
- Was passing along `job` args to each `set()`/`get()` call internally, but was also passing in a `cfg` arg that was hardcoded to `self.cfg`, and that always takes precedence over the job.
-  I have a longer-term fix in the works that will refactor basic schema access into a separate class (which we discussed a while back), and that will let us remove the `cfg` arguments and make bugs like this less likely to occur in the future
- Adds reports/final manifest to `chip.archive()`
- Export custom Sphinx `:keypath:` directive 
- Could be useful for …
> Fix `find_files()` job argument + more

- siliconcompiler/schema.py
- tests/core/data/defaults.json
This PR adds back dedicated pre/post scripts, as well as a free file entry.
I was thinking another way to do this could be to add a free key after 'script', and standardize on values "entry", "pre", "post", and then allow free keys otherwise. This is a bit painful for backwards compatibility though.
> Add more file entries to tool schema

- siliconcompiler/tools/klayout/klayout_show.py
- Current logic just picks the first stackup of all possible, instead we should be taking the user-selected stackup.
- Tweak settings to always display macro/cell geometry from LEFs when viewing DEF, even if FOREIGN statement is set in LEF
> KLayout show fixups

- pyproject.toml
The latest version of setuptools breaks our editable install, due to this issue in scikit-build: https://github.com/scikit-build/scikit-build/issues/740. Until this issue is fixed (or we change how the leflib build works), we need to pin setuptools to an older version.
> Pin setuptools version to fix editable install

- siliconcompiler/core.py
The checker logic was still assuming that input files are always collected locally, but that only happens for remote runs now.
> Fix bug in flowgraph I/O checking

- siliconcompiler/core.py
- tests/flows/test_steplist.py
This PR fixes a bug where tool setup gets lost when a partially run flow is continued using the steplist. This means things like the tool report mappings are no longer fully captured when a flow is executed over multiple runs. 
That immediate problem is caused by the fact that the tool setup functions are executed at runtime, and only for the steps currently in the steplist for that run. Therefore, setup for tools from the steps that have already been run don't end up in the chip configuration.
One way to fix this could be to re-run setup() for all steps every time, but I think it would make more sense to capture the setup that was used to run those particular steps, in case the user changes something between re-runs. 
One cause of this problem was introducing the partial read_manifest …
> Read in manifests from previously completed tasks before running

- siliconcompiler/tools/surelog/surelog.py
- tests/tools/test_surelog.py
One more small change, to address #1135.
If the same Verilog file is added to a Chip object twice, Surelog will duplicate its content in the pickled output, which causes synthesis failures with Yosys.
Like the reporter suggested, we can de-duplicate the inputs when we are assembling the import step's Surelog command, and print a warning if any duplicate files are found.
> Deduplicate Surelog file inputs

- siliconcompiler/client.py
In preparation for some SCServer updates, this change lets the client print a bit more information about an ongoing remote job run.
It will print the current step and a tail of the task's log if the server provides that information. If not, it will continue printing the generic "Job is still running" message for compatibility with old (and current) versions of the server.
> SC client messaging update

- tests/core/test_cwd.py
Windows throws `PermissionError: [WinError 32]` if you try to delete a directory which a process is using, so the test for nonexistent working directories fails on that platform.
It seems like that makes it less likely for the "no current directory" bug to occur, so we can probably skip the test on Windows platforms.
> Skip "no working directory" test on Windows

- siliconcompiler/core.py
This PR fixes #1167. There is no log file when running a pure Python tool, so we need to handle this case and print out an error message without a path to the log.
> Fix crash when pure-Python tool returns error

- .github/workflows/on_push_tests.yml
- siliconcompiler/tools/surelog/surelog.py
This PR implements some Surelog driver tweaks:
- Disable UHDM output
- Implement warningoff
I also included a fix to our Github Actions workflow to fix a breakage due to recent changes on Github's part - their 22.04 Ubuntu runners don't support Python 3.6, so we have to run those tests on a fixed version.
> Surelog driver tweaks/fix Github Actions

- setup/install-surelog.sh
Since Noah has updated the version of Surelog that we are using, I don't think we need this workaround in the install script anymore.
We added it because Surelog's `antlr4` submodule used a `git://` URL for the repository, and GitHub stopped supporting anonymous pulls from some SSH endpoints. Newer versions of Surelog use an `https://` URL, so we don't need to explicitly specify that anymore.
> Remove setup workaround for old Surelog git repo URL

- siliconcompiler/core.py
- tests/flows/test_steplist.py
This commit takes a lighter approach to fixing the immediate bug that we attempted to fix with #1145, which is to ensure that tool setup persists across re-runs using steplist. Reading in the entire manifest before a run overwrites boolean options (such as resume), which can lead to unintuitive behavior. For example,
```python
...
chip.set('option', 'resume', True)
chip.run()
chip.set('option', 'resume', False)
chip.set('option', 'steplist', ['export'])
chip.run() # won't rerun export, behaves as if resume is still True
```
I still think there are better fixes down the road, but this seems like a better fix to go with in the meantime.
> Fix bug introduced by #1145

- siliconcompiler/apps/sc_ping.py
- siliconcompiler/client.py
- siliconcompiler/core.py
- siliconcompiler/floorplan.py
- siliconcompiler/leflib/__init__.py
- siliconcompiler/schema/schema_obj.py
- siliconcompiler/server.py
- siliconcompiler/tools/klayout/klayout_show.py
- tests/flows/test_server.py
"except:" will catch e.g. KeyboardInterruptException, which can result in unintended effects like ctrl-c not working.
Instead use "except Exception:".
The code could be further refined to catch narrower exceptions than all exceptions, such as dealing with file not found differently than problems parsing a .yaml file, but that's for another pull request.
https://docs.python.org/3/library/exceptions.html
> python: don't catch BaseException, such as KeyboardInterruptException

- tests/flows/test_steplist.py
This PR fixes a regression in our daily tests caused by #1147. `Schema.copy()` performs a deep-copy, so this should be equivalent.
> Fix test_steplist_keep_reports

- siliconcompiler/scheduler.py
This PR contains a handful of changes that came out of our recent infrastructure explorations.
* Cluster partitions can be overridden on a per-step basis.
* Support implementations which do not require slurmdbd accounting.
* Support extra job statuses used by implementations which use power-save scripts for elastic scaling.
> Update the scheduler module to work with Slurm power-save scripts

- docs/user_guide/targets.rst
- siliconcompiler/core.py
- tests/core/test_find_file.py
1. Change order of resolution
2. Only bypass resolution if value is truly an absolute path, otherwise the code will return the path itself relative to the CWD when `_find_sc_file()` is called
Closes #1178
> Tweaks to file path resolution

- examples/blinky/run.sh
- examples/blinky/run_vivado.sh
- siliconcompiler/tools/vivado/compile.tcl
- siliconcompiler/tools/vivado/vivado.py
- siliconcompiler/utils.py
This PR contains another grab bag of tweaks related to Vivado/FPGA flows.
- Make it optional to supply an XDC file to the Vivado flow
- Suggested by @petergrossmann21, this will make it easy to stand up quick tests to estimate the area of a design.
- Verified working by manually removing constraint from Blinky example and running
- Add FPGA constraint files to the I/O map so we can supply them directly to `sc`
- Add warnings/errors regexes to Vivado driver
> More Vivado/FPGA enhancements

- .github/workflows/bin/install_klayout_win.bat
- .github/workflows/bin/setup_wheel_env_linux.sh
- .github/workflows/daily_tests.yml
- .github/workflows/on_push_tests.yml
- .github/workflows/wheels.yml
A lot of our Actions dependencies were pinned to old versions that use deprecated features. Updating them should silence the warnings we see in our workflow summary pages.
> Update GH Actions workflow dependencies

- siliconcompiler/schema/schema_cfg.py
- tests/core/data/defaults.json
- A footprint is a a must have parameter for all physical designs and it is a datasheet level parameter. (ie would be in the PDF).  https://www.jedec.org/category/technology-focus-area/jc-10/registered-outlines-jep95
- The parameter is currently embedded in the asic group which is too limited.
- This should be able to serve the need of the 'asic' 'footprint' as well...
> Adding footprint parameter to datasheet schema

- .github/workflows/daily_tests.yml
- siliconcompiler/tools/verilator/verilator.py
- tests/examples/test_heartbeat_padring.py
- tests/flows/test_verilator_sim.py
They take a bit longer than 20 minutes now, and it looks like the Verilator `compile` runtime options need to include input Verilog files.
> Fix daily CI tests

- examples/gcd/gcd_skywater.py
- siliconcompiler/core.py
- siliconcompiler/flows/asicflow.py
- siliconcompiler/flows/asictopflow.py
- siliconcompiler/flows/fpgaflow.py
- siliconcompiler/flows/lintflow.py
- siliconcompiler/flows/showflow.py
- siliconcompiler/flows/signoffflow.py
- tests/core/test_check_flowgraph_io.py
- tests/core/test_check_manifest.py
- tests/core/test_jobincr.py
- tests/flows/test_flowstatus.py
- tests/flows/test_tool_option.py
- tests/tools/test_icarus.py
- tests/tools/test_openroad.py
- tests/tools/test_yosys.py
Fixes:
- Updates left over references to steps to be specific to tasks instead.
Changes:
- Changes names of builtin tasks to be a tool name of `builtin` with the associated task and adds `import` as a task which behaves like a `nop` but is needed for flow validation.
> update core to use tasks instead of step names

- siliconcompiler/core.py
- siliconcompiler/templates/report/sc_report.j2
- tests/core/test_summary.py
This PR cleans up the `summary()`/HTML report logic a bit in preparation for step/index-related changes. 
The primary change is to reduce the HTML report template's reliance on direct access to the schema so that we can abstract away the step/index-related schema changes. The Python logic in `summary()` is now responsible for directly passing relevant values to the template in a more concise form. 
Unfortunately we can't fully abstract away the manifest from the HTML report, since it also has functionality for viewing the entire tree/modifying checklist values and re-exporting the manifest. Eventually at least some of this logic will need to be updated for our new step/index abstraction scheme, but this is lower priority since it doesn't block switching over to the new scheme.
As part of …
> Clean up `summary()`/HTML report logic

- examples/aes/aes.py
- examples/benchmark/benchmark.py
- examples/blinky/blinky.py
- examples/fibone/fibone.py
- examples/gcd/gcd.py
- examples/gcd/gcd_multiflow.py
- examples/gcd/gcd_skywater.py
- examples/gcd_chisel/gcd_chisel.py
- examples/gcd_hls/gcd_hls.py
- examples/ghdl_fsynopsys/build.py
- examples/heartbeat/heartbeat.py
- examples/heartbeat/parallel.py
- examples/heartbeat_caravel_wrapper/build.py
- examples/heartbeat_migen/heartbeat_migen.py
- examples/heartbeat_padring/build.py
- examples/heartbeat_padring/floorplan_build.py
- examples/microwatt/build.py
- examples/oh_experiments/adder_sweep.py
- examples/oh_experiments/check_area.py
- examples/oh_experiments/parallel_adder_sweep.py
- examples/picorv32/picorv32.py
- siliconcompiler/core.py
- tests/core/test_target.py
- tests/core/test_write_flowgraph.py
Changes:
- since `load_target` will not use `.use`, this returns all instances of it back to the previous method
> return to load_target

- siliconcompiler/pdks/skywater130.py
- siliconcompiler/tools/klayout/klayout_show.py
- siliconcompiler/tools/klayout/screenshot.py
- siliconcompiler/tools/klayout/show.py
I'm not a marketer, but I think that our auto-generated Skywater130 design screenshots would look better if the details weren't obscured by blocks of bright magenta. I could see an argument for only applying this to the `screenshot` task, and not `show`, but users can override the default visibility settings in the KLayout GUI.
Before (`picorv32`/`sky130hd`, all open-source):
After:
> Add an option to hide layers by default in show and screenshot tasks

- siliconcompiler/client.py
- siliconcompiler/core.py
- tests/flows/test_server.py
A few small SiliconCompiler updates which are needed to get the minimal `heartbeat` example running remotely with our recent `Chip`/`Schema` updates.
I like the new `Schema.unset` method - it's more clear than overwriting the value to `None` or `[]`.
There might be a couple more PRs like this as I move on to testing the server-side scheduler functionality.
> Early fixes for post-refactor remote client

- docs/user_guide/flows.rst
- docs/user_guide/pdks.rst
- docs/user_guide/programming_model.rst
- siliconcompiler/__init__.py
- siliconcompiler/checklists/oh_tapeout/oh_tapeout.py
- siliconcompiler/core.py
- siliconcompiler/flows/asicflow.py
- siliconcompiler/flows/asictopflow.py
- siliconcompiler/flows/dvflow.py
- siliconcompiler/flows/fpgaflow.py
- siliconcompiler/flows/lintflow.py
- siliconcompiler/flows/showflow.py
- siliconcompiler/flows/signoffflow.py
- siliconcompiler/libs/asap7sc7p5t.py
- siliconcompiler/libs/nangate45.py
- siliconcompiler/libs/sky130hd.py
- siliconcompiler/libs/sky130io.py
- siliconcompiler/pdks/asap7.py
- siliconcompiler/pdks/freepdk45.py
- siliconcompiler/pdks/skywater130.py
- siliconcompiler/schema/schema_cfg.py
- siliconcompiler/sphinx_ext/dynamicgen.py
- siliconcompiler/targets/asap7_demo.py
- siliconcompiler/targets/freepdk45_demo.py
- siliconcompiler/targets/skywater130_demo.py
- siliconcompiler/use.py
- tests/core/data/defaults.json
- tests/core/test_create_cmdline.py
- tests/core/test_write_flowgraph.py
- tests/flows/test_tool_option.py
Changes:
- Implements .use() for PDKs/Libraries/Flows/Checklists
- both `.use` and `.load_target` can take a `**kwargs` to pass long parameters needed to configure flows, etc
- removal of ['arg', 'flow'/'pdk'] from schema'
- Updates docs to build with the new return types
Notes:
- many of the files in flows/, libs/ pdks/, targets/, and checklists/ are mostly modified to account for the change in use model, but should not have any functional changes.
> Implementation of .use()

- docs/_ext/schemagen.py
- siliconcompiler/sphinx_ext/dynamicgen.py
- siliconcompiler/sphinx_ext/utils.py
- siliconcompiler/tools/surelog/surelog.py
Adds:
- initial support for loading the tasks into the documentation. This simply adds a subsection to each tool with one section per task.
The tasks are currently not well documented, so next we need to fix the doc strings there.
> Add tasks to documentation

- siliconcompiler/client.py
- siliconcompiler/core.py
- tests/flows/test_server.py
Like @nmoroze suggested in #1261, there's not much reason to exclude custom `steplist` parameters from the remote flow. It may not be useful for generic ASIC / bitstream builds, but it could help with design exploration, and the functionality is already built into `Chip.run` if we pass it through.
This could also work with a `from` / `to` specification, if we implement that.
> Support partial steplists in remote flow.

- siliconcompiler/core.py
- tests/core/test_check_manifest.py
Looks like this got flipped during the switch to builtins: https://github.com/siliconcompiler/siliconcompiler/commit/cab52cdce87490637d643b727c15d72a3a46951c#diff-0a7b686d579b6f3a831a79a61fda4755be2fc2f5cfefc0d848da015810cb3f54L1453
Didn't get caught due to another bug in the test, but it should be captured by tests now.
> Fix polarity on builtin check

- siliconcompiler/apps/sc_configure.py
- siliconcompiler/client.py
- tests/apps/test_sc_configure.py
* Adds a simple one-line configuration for public servers (`sc-configure https://...`)
* Omits the `username` and `password` fields in `client.py` if either one is an empty string.
* Adds some tests for the `sc-configure` app.
> Update `sc-configure`, and add tests

- siliconcompiler/core.py
- siliconcompiler/schema/schema_cfg.py
- tests/core/data/defaults.json
- tests/core/test_create_cmdline.py
This PR adds support for providing step/index for per-node parameters via the CLI. 
The syntax is to add the step and index name prior to the value. These must always be included for "required" pernode parameters:
- `sc -record_distro 'import 0 ubuntu'` (good)
- `sc -record_distro ubuntu` (error)
You are still allowed to supply string values with spaces for required pernode parameters, as before:
- `sc -record_distro 'import 0 my distro name'` -> stores "my distro name" in [record, distro]
For optional parameters, you can omit the step and index, provide a step only, or provide a step and an index:
- `sc -asic_logiclib mylib`
- `sc -asic_logiclib 'syn synlib'`
- `sc -asic_logiclib 'syn 1 syn1lib'`
Values with spaces for optional parameters must be wrapped in quotes now:
- `sc …
> Support step/index overrides in command line

- setup/install-yosys.sh
Currently, the yosys setup script requires you to enter 'y' in response to the apt-get install command. This is a bit inconvenient for headless install methods.
> Remove stdin requirement from yosys setup script

- siliconcompiler/schema/schema_cfg.py
I noticed that the relative import required for our new KLayout scheme breaks the generate_defaults script - this PR fixes that.
> schema_cfg: add import fallback for generate_defaults

- siliconcompiler/schema/schema_obj.py
- tests/core/test_write_manifest.py
This wasn't on my formal todo list, but I had the code for this already so I figured we might as well get it in (was going to be bundled with TCL manifest changes we're punting).
This PR adds some logic to the `write_csv` method to dump per-node values as well as the global values. Previous behavior was that per-node values get ignored.
Example:
```python
chip.add('asic', 'logiclib', 'mainlib')
chip.add('asic', 'logiclib', 'synlib', step='syn')
chip.add('asic', 'logiclib', 'syn1lib', step='syn', index=1)
```
> schema_obj: update write_csv to handle per-node values

- siliconcompiler/core.py
- siliconcompiler/scheduler.py
- siliconcompiler/schema/schema_cfg.py
- tests/core/data/defaults.json
* Use the top-level 'scheduler' keypath in scheduler.py
* Run tasks on compute nodes using Python build scripts, instead of the `sc` command line.
Unfortunately, we don't have a way to un-set an enum Schema value from the command line. I can report that edge case bug, but it's probably not a priority to fix it right this moment, so for now we can use the Python API's `Chip.unset()` call to mark when a task has reached the node that it should run on.
This is probably a good change to make anyways, as it will give us more flexibility going forward.
> Fix and update scheduler.py

- siliconcompiler/apps/sc.py
- tests/apps/test_sc.py
It looks like we broke this functionality when adding the extra layer of nesting to the 'input' keypath. Added a test for it to prevent regressions in the future.
Also switched from using `get()` to `_getvals()` to make this compatible with PR #1289
> sc: fix inference of design name from sources

- .github/workflows/daily_tests.yml
- .github/workflows/on_push_tests.yml
- examples/oh_experiments/check_area.py
- examples/oh_experiments/feedback_loop.py
- pyproject.toml
- tests/conftest.py
- tests/examples/test_fibone.py
- tests/examples/test_gcd.py
- tests/examples/test_gcd_chisel.py
- tests/examples/test_gcd_hls.py
- tests/examples/test_heartbeat.py
- tests/examples/test_heartbeat_padring.py
- tests/examples/test_oh_experiments.py
- tests/flows/test_entrypoint.py
- tests/flows/test_resume.py
Changes:
- Restores daily CI to passing
- Adds a default timeout of 60s for all tests to ensure the CI finishes
- Adds special timeouts for tests requiring more than 60 seconds
- Extends the overall timeout to 60mins
> Fix daily CI

- siliconcompiler/templates/report/sc_report.j2
This PR updates the HTML report to display all pernode values that may be associated with a parameter, rather than just the global one. Here's a before/after comparison with one of the record fields expanded to show what this looks like:
| Before  | After |
| ------------- | ------------- |
|![before](https://user-images.githubusercontent.com/4412459/221044674-14ca56b0-d302-4116-9db1-6254973d884a.png)   | ![now for real](https://user-images.githubusercontent.com/4412459/221044698-d0f54c6b-427a-4e33-843d-6fce0d20f05e.png)  |
> core: update HTML report to display all pernode values

- siliconcompiler/sphinx_ext/dynamicgen.py
These sections are based on the `display_config_recursive()` method, which was accessing the JSON dictionary directly. This PR fixes them by refactoring it to use the Schema object, which makes them a bit cleaner/should make them more robust going forward.
> docs: fix blank Libraries/PDKs sections

- siliconcompiler/tools/openroad/export.py
- siliconcompiler/tools/openroad/openroad.py
Fixes:
- incorrect check if a value was set
Changes:
- disable write_cdl by default for now as the PDKs only have partial support for this (mainly the macros and IOs). Once those are updated we can reenable.
> openroad fixes

- setup/install-surelog.sh
I tested out in a new VM (to avoid conflating dependencies from previous installs) and it looks like the orderedmultidict package is also needed in the venv packages area for the surelog install.
> Add pip install for orderedmultidict back in for surelog install script since needed for venv

- docs/reference_manual/core_api.rst
- docs/user_guide/libraries.rst
I've rendered this and checked that the links work. When we have a "large" integration app note which contains a hard macro block, we might want to link to it here as a more concrete example than the basic `'mydesign'` code block.
This also adds the the `siliconcompiler.use` classes to the "Core API" section of the reference manual. Should we do more to indicate that those classes inherit the Chip/Schema's `get`/`set`/`add`/etc methods?
> Initial refresh of the Libraries documentation

- docs/user_guide/installation.rst
- docs/user_guide/installation/installation_prep_path.rst
- docs/user_guide/quickstart.rst
Per discussion with @gadfort, I added the release version to the `git clone` commands. Also a minor update to developer install instructions to be consistent with other install instructions
> add release version to git clone commands

- docs/tutorials/slurmsetup.rst
Like we discussed offline, there would probably be too many scenarios to cover in a Slurm troubleshooting section. There is a link to the official Slurm docs page at the top of the section, and that's probably the best resource for the topic.
> Remove slurm troubleshooting section

- .github/workflows/bin/install_surelog_macos.sh
This change was verified by a manual workflow run: https://github.com/siliconcompiler/siliconcompiler/actions/runs/4309851810.
The manual run was performed on a branch with these changes + caching removed and #1340 merged in. The package_offline part failed because of how I hacked up the actions script, but I downloaded the generated wheels, extracted the Surelog binary, and verified that it runs on an Intel-based Mac and an ARM-based Mac.
> Fix Surelog build for Apple Silicon

- siliconcompiler/core.py
Quick follow-up which lets the PDF results returned from the remote server be opened automatically on Windows machines after a successful run. The `$DISPLAY` check that I added in #1342  turned out to be unnecessary, and not applicable to Windows.
> Remove recently-added DISPLAY check, and an extraneous file path def

- docs/user_guide/faq.rst
On the FAQ question page before, some of the questions were bolded and some were not. These spacing changes makes them consistent.
> fix question bolding inconsistency

- siliconcompiler/client.py
- siliconcompiler/core.py
Fixes:
- imported files getting found multiple times by surelog with include paths. Since import always runs locally, we do not need to run this until after the import step has completed.
> move _collect call to after import to prevent multiple local files from getting sourced in surelog

- siliconcompiler/client.py
Like we discussed offline, it would be nice to have a final message pointing to where the results are located after a remote run finishes, in case the build script does not include a call to `chip.summary()`.
If the full build results are being returned, it can take a bit of time to retrieve and unzip the results, so I also added a quick mention of that call. The delay probably won't be noticeable when only the core reports are returned, though.
> Add a bit more exposition to the client-side messages

- siliconcompiler/core.py
Fixes:
- server fails to generate HTML report correctly because its already generated in an earlier step.
> allow overwriting the HTML report, while preventing repeat generating the result png

- siliconcompiler/client.py
This updates the client to print relevant error messaging when the server doesn't return any results. I tested it by asking for the wrong job ID, but the behavior should be the same when the server encounters expected failures such as refusing to return over-sized results:
```
| INFO    | job0  | import     | 0  | Remote job run completed! Fetching results...
| WARNING | job0  | import     | 0  | Error fetching results: Job not found.
File "sc_env/bin/sc", line 33, in <module>
sys.exit(load_entry_point('siliconcompiler', 'console_scripts', 'sc')())
File "siliconcompiler/apps/sc.py", line 77, in main
chip.run()
File "siliconcompiler/core.py", line 4293, in run
fetch_results(self)
File "siliconcompiler/client.py", line 341, in fetch_results …
```
> Improve error messaging when results cannot be fetched.

- docs/tutorials/picorv32_ram.rst
Added `chip.summary()` to examples so that users will get png and reports generated if they run the tutorial
> Update picorv32 examples to include chip.summary

- siliconcompiler/core.py
- tests/core/test_runtime_exception.py
Changes:
- Adds a try/except block around calls to external code to help enable better error messaging.
- Check return code for --version checks to ensure failures are caught.
> Add try/except to external calls

- .github/workflows/bin/clean_surelog_build.py
- .github/workflows/bin/install_surelog_linux.sh
- .github/workflows/bin/install_surelog_macos.sh
- .github/workflows/bin/install_surelog_win.bat
- .github/workflows/bin/setup_wheel_env_linux.sh
- .github/workflows/on_push_tests.yml
- .github/workflows/wheels.yml
- tests/core/test_create_cmdline.py
- tests/core/test_runtime_exception.py
- tests/core/test_sup.py
This PR adds support for Linux+ARM64 [SC-214/SC-219] wheels and addresses a few other issues in the process:
- Adds Surelog build caching for Linux builds
- Fix Windows cache blank key [SC-200]
- Upload created wheels even when job fails (although wheels that fail tests still don't get uploaded, because it seems like cibuildwheel doesn't copy them to the final wheelhouse/ location until they pass)
- Clean up extraneous Surelog build artifacts
- The Surelog build creates a bunch of extra artifacts that aren't necessary to run. The cache was previously acting like a filter since it's only applied to a few paths, but this meant that Linux wheels used to be consistently bloated, and macOS/Windows wheels would occasionally be large for the first build of a new Surelog version. Now the wheels …
> Build Linux + ARM64 wheels with caching for all platforms

- .github/workflows/bin/install_klayout_win.bat
- .github/workflows/bin/install_surelog_macos.sh
- .github/workflows/bin/install_surelog_win.bat
- .github/workflows/bin/setup_wheel_env_linux.sh
- setup/_tools.json
- setup/install-klayout.sh
- setup/install-surelog.sh
- siliconcompiler/tools/surelog/surelog.py
Changes:
- update surelog to 1.51 and set required version accordingly to ensure we get bug fixes
- Fix version of klayout to use _tools.json for wheels build
Wheels: https://github.com/siliconcompiler/siliconcompiler/actions/runs/4547388989
> Update surelog version

- siliconcompiler/core.py
This change fixes an immediate symptom of the following problem, but the root cause probably merits a deeper investigation.
We use tuple data structures in some areas of the Schema, but it turns out that tuples are not serializable as JSON; they get silently converted to lists.
I'm a little bit surprised that this hasn't caused some sort of problem already, but tuples and lists can be accessed in very similar ways, and Python is not statically typed. In this case, the bug only surfaced because we add a Schema keypath directly to a set, which requires hashing the object. Tuples can be hashed, but lists cannot, so when we call `chip.run()` after loading in a JSON-based Schema, this part of the code would raise a `TypeError`.
For now, we can convert the `[step, index]` lists from the …
> Fix a bug caused by tuples not being serializable in JSON

- siliconcompiler/scheduler.py
Small typo in the scheduler script - hopefully we can re-enable the Slurm CI tests in the future.
> Fix incorrect Chip reference in scheduler.py

- siliconcompiler/client.py
This change fixes a breakage in the remote flow introduced by the large change to modularize tool/task setup.
> Fix remote_preprocess method

- siliconcompiler/flows/showflow.py
- siliconcompiler/sphinx_ext/dynamicgen.py
Fixes:
- during the tool/task merges the docs started to fail in to build some tools. This corrects it by ensuring the right setting are available.
> Fix docs build

- siliconcompiler/schema/schema_cfg.py
- tests/core/data/defaults.json
- tests/core/test_hash_files.py
This change is inspired by a hallway conversation with @mithro.
It has become clear that I have not spent nearly enough time studying the existing the state of practice in the software domain.
There is no point inventing a new format/standard, when a perfectly good one exists.
This PR is adding an SBOM to the executable as a fist class parameter.
https://spdx.dev/
https://github.com/opensbom-generator/spdx-sbom-generator
https://github.com/spdx/spdx-examples
Next PR will explore removing the package information and replacing that section of the scema with an SBOM. This change goes along with our general philosophy to only put the minimal of information in the schema. Whenever there is an undisputed open standard, we prefer using that standard. In the case of the SBOM, it does create one …
> Adding SBOM feature

- siliconcompiler/apps/sc_show.py
- siliconcompiler/core.py
- tests/apps/test_sc_show.py
Changes:
- show doesn't work when an entry point is used, this corrects for that by ensuring the json manifest can be found
- removes a few hardcoded 'export' and file extension values
> Fix show with entrypoints and hard coded values

- requirements.txt
- siliconcompiler/apps/sc_issue.py
- siliconcompiler/core.py
- tests/apps/test_sc_issue.py
Adds:
- sc-issue as a cli app to be able to generate and run testcases
Fixes:
- keypaths and file handling when files are sometimes not Found
`sc-issue -generate -cfg ...` will make a `sc_issue.tar.gz` which can be shared and run using `sc-issue -run`
Closes: #1466
This is an initial version, which can be improved upon, @maliberty FYI
> Add sc-issue to generate runnable testcases

- siliconcompiler/tools/klayout/klayout.py
Our KLayout tool driver should not try to open GUI windows on a headless machine. Like OpenROAD, KLayout uses QT for its user interface, and we should be able to ask it to render graphical components to a virtual framebuffer by setting `$QT_QPA_PLATFORM = "offscreen"`.
The OpenROAD tool driver already contains this logic, and adding it to the KLayout driver will let us remove some logic which ensures that this environment variable is set elsewhere.
> Set 'QT_QPA_PLATFORM' env var in KLayout if nodisplay option is set

- siliconcompiler/apps/sc_configure.py
- siliconcompiler/apps/sc_server.py
- siliconcompiler/server.py
- tests/server/test_server.py
Changes:
- fix sc-configure to allow for port to be entered
- removed calls to mkdir via subprocess and instead use builtin makedirs
- removed unused code from sc-server
- added local server tests to CI and updated to sc-server to function again.
This is a step towards getting all server tests with slurm enabled as well.
> Cleanup sc-server round 1

- siliconcompiler/schema/schema_obj.py
- tests/schema/test_schema.py
Needed to reorder this check to ensure error messages are clear:
Before:
```
>>> chip.add('input', 'verilog', 'foo.v')
File "<stdin>", line 1, in <module>
File "/home/noah/code/siliconcompiler/siliconcompiler/core.py", line 1064, in add
if not self.schema.add(*args, field=field, step=step, index=index):
File "/home/noah/code/siliconcompiler/siliconcompiler/schema/schema_obj.py", line 197, in add
err = Schema._validate_step_index(cfg['pernode'], field, step, index)
KeyError: 'pernode'
```
After:
```
File "<stdin>", line 1, in <module>
File "/home/noah/code/siliconcompiler/siliconcompiler/core.py", line 1070, in add
self.error(str(e))
File "/home/noah/code/siliconcompiler/siliconcompiler/core.py", line 4985, in error …
```
> Fix error for add() invalid keypath

- siliconcompiler/core.py
- siliconcompiler/schema/schema_obj.py
- tests/core/tools/fake/bar.py
- tests/core/tools/fake/baz.py
- tests/core/tools/fake/foo.py
- tests/flows/test_multiple_tools.py
- tests/schema/test_schema.py
This PR fixes a bug in the Schema._is_empty() function that caused it to always return False. It also includes a few other fixes of issues that were masked by this bug:
- Need to add a `run()` function to the fake tools - each tool needs either a `run()` or the exe param defined, but the check wasn't working previously
- No more pruning of manifests dumped for tools - with is_empty fixed the pruning becomes a lot more aggressive, which makes a lot of keypaths no longer exist in the Schema in the KL driver
> Fix Schema._is_empty() [SC-330]

- siliconcompiler/client.py
- siliconcompiler/core.py
- siliconcompiler/server.py
Changes:
- Removes subprocess calls to tar infavor of using tarfile
- Plus minor code formatting
- Adding nfs_mount to Server object  (real solution is probably to cleanup its schema accesses)
> Remove subprocess from server code + minor cleanup

- siliconcompiler/core.py
When a relative path is provided to the credentials, which contains no directory, the isdir returns false. This ensures the path used is an abs path do the directory component will have something and can fail out correctly.
> fix server credentials finding

- siliconcompiler/apps/sc_configure.py
Fixes:
- when running sc-configure localhost:8080 it should detect that this is missing the scheme and therefore needs a dummy one pre-pended to parse the hostname correctly.
> fix incorrect detection of invalid url

- siliconcompiler/core.py
- siliconcompiler/schema/schema_obj.py
Changes:
- Schema passes all values through `set` to ensure they are normalized to their values.
Fixes:
- issue of tuples getting converted to lists in json and not getting converted back to tuples on restore
> Ensure all values in the schema pass though the set to make sure lists and tuples are restored correctly

- siliconcompiler/tools/openroad/floorplan.py
- siliconcompiler/tools/openroad/openroad.py
- siliconcompiler/tools/openroad/sc_floorplan.tcl
Changes:
- implements missing functionality in OpenROAD driver to place macros on grid
> implement x/y location snapping to OpenROAD driver to ensure ongrid placement of macros

- siliconcompiler/tools/yosys/syn_asic.py
@techstuds this should fix the bad error message, but doesn't address the setup issues you may have had.
> check if dff_liberty_file returns a file before setting

- .github/workflows/daily_ci.yml
- .github/workflows/lint.yml
- .github/workflows/python_ci.yml
- .github/workflows/tools_ci.yml
- README.md
- docs/user_guide/installation.rst
@aulihant this solves the issue of the lint on 3.6 with the new docs build. It also makes it a little easier to install since before we asked for two install steps and now can just do one
> Avoid using -r requirements for installs

- CMakeLists.txt
Looks like the failing wheels build was due to a recent update in scikit-build that affects how the location of Python libraries are reported to CMake. I based the fix on notes from https://github.com/scikit-build/scikit-build/issues/963 and https://github.com/Qiskit/qiskit-aer/pull/1786
Fix verified in https://github.com/siliconcompiler/siliconcompiler/actions/runs/4854034031. I did notice that one of the KL show tests timed out for macOS, but is fine after re-running. Might be something to keep an eye on, not sure if we need to bump the timeout or if it's just a weird transient thing...
> Fix wheels

- siliconcompiler/core.py
sc-issue was attempting to gobble up all of the scpaths if its set and missing the input/output/report keys causing the generation to fail when executed on a failed run.
> dont take all of scpath and ensure task io is skipped

- siliconcompiler/core.py
- siliconcompiler/targets/asap7_demo.py
- siliconcompiler/targets/asic_demo.py
- siliconcompiler/targets/fpgaflow_demo.py
- siliconcompiler/targets/freepdk45_demo.py
- siliconcompiler/targets/skywater130_demo.py
- tests/core/test_create_cmdline.py
Ensures the target is loaded after the options are set and makes sure the provided targets are non-clobbering
> Fix load target order

- .readthedocs.yaml
Need to specify a newer build environment for RTD due to a breaking change in a transitive dependency. 
Fix based on https://github.com/readthedocs/readthedocs.org/issues/10290#issuecomment-1535120995.
> Configure docs build to use newer OS

- siliconcompiler/core.py
- tests/core/test_check_manifest.py
If a user accidentally adds duplicate edges to a flowgraph, they'll get a confusing error mid run: 
```
| INFO    | job0  | mystep    | 0  | Finished task in 60s
Process Process-4:
File "/opt/rh/rh-python38/root/usr/lib64/python3.8/multiprocessing/process.py", line 315, in _bootstrap
self.run()
File "/opt/rh/rh-python38/root/usr/lib64/python3.8/multiprocessing/process.py", line 108, in run
self._target(*self._args, **self._kwargs)
File "/home/centos/venv/lib64/python3.8/site-packages/siliconcompiler/core.py", line 3608, in _runtask
utils.copytree(f"../../../{in_job}/{in_step}/{in_index}/outputs", 'inputs/',
File "/home/centos/venv/lib64/python3.8/site-packages/siliconcompiler/utils.py", line 30, in copytree
os.link(srcfile, dstfile)
FileExistsError: …
```
> Gracefully handle duplicate edges

- siliconcompiler/apps/sc_show.py
- siliconcompiler/core.py
- tests/apps/test_sc_show.py
Adds: `-ext` option to sc-show to allow users to select the filetype to display. This is useful when multiple filetypes are available and you need a particular one, like def or odb.
> add extension to sc-show to allow users to pick the file type easily when multiple displayble files are generated

- siliconcompiler/apps/sc_issue.py
- siliconcompiler/core.py
- siliconcompiler/templates/issue/README.txt
- siliconcompiler/templates/issue/run.sh
Changes:
- `_find_files` can now return relative paths if the private variable `__relative_path` is set. This allows the testcase generator to build testcases with complete tests.
- Fixes incorrect libraries key path
- Rework the testcase generator to include a README.txt and a run.sh file to allow for standalone tests.
> [sc-issue] update to make testcases self-contained

- siliconcompiler/schema/schema_obj.py
- tests/core/test_setget.py
- tests/schema/test_unset.py
This PR fixes a bug where `unset()` would act as a silent no-op if an integer index was provided, which is inconsistent with how the `get/set/add` functions behave.
I also added additional unit tests for `unset()`, and moved the existing test from the core tests to the schema tests, since I think moving towards testing base `Schema` functionality within the schema tests will help with organization.
> Allow integer index for unset()

- siliconcompiler/tools/openroad/openroad.py
- siliconcompiler/tools/openroad/sc_apr.tcl
- siliconcompiler/tools/openroad/sc_route.tcl
allow for bypassing antenna repair steps when they are not needed
> add flags to control antenna repair and checking in routing task

- setup/docker/tool.docker
Without this the base image gets stale and new tool builds starts to fail.
> add apt-get update to tool dockerfile

- siliconcompiler/core.py
- tests/core/test_check_manifest.py
- tests/core/test_jobincr.py
This ensures the option,mode is set correctly before running as this avoid ambiguity about the run type, show the summary table is checked, and when checking mode specific requirements.
> Enforce mode setting

- siliconcompiler/tools/openroad/cts.py
- siliconcompiler/tools/openroad/dfm.py
- siliconcompiler/tools/openroad/export.py
- siliconcompiler/tools/openroad/floorplan.py
- siliconcompiler/tools/openroad/openroad.py
- siliconcompiler/tools/openroad/physyn.py
- siliconcompiler/tools/openroad/place.py
- siliconcompiler/tools/openroad/route.py
- siliconcompiler/tools/openroad/screenshot.py
- siliconcompiler/tools/openroad/show.py
- siliconcompiler/tools/surelog/surelog.py
- siliconcompiler/tools/yosys/syn_asic.py
This fixes the use of `find_files()` in `setup()` for the tools and moves it to the `pre_process()` where it belongs.
> Fix use of find_files in setup()

- siliconcompiler/core.py
- siliconcompiler/schema/schema_obj.py
- tests/core/test_env_schema.py
- tests/core/tools/dummy/dummy.py
- tests/core/tools/dummy/environment.py
This PR ensures the schema obj has access to a logger and avoids the need to manually deinit loggers when `run()` is engaged.
This closes: #1231
> Cleanup logger handling and pass logger to schema object

- docs/_ext/schemagen.py
- docs/reference_manual/schema.rst
- docs/user_guide/data_model.rst
- siliconcompiler/core.py
- siliconcompiler/schema/schema_cfg.py
- siliconcompiler/schema/schema_obj.py
- siliconcompiler/sphinx_ext/utils.py
- tests/core/data/defaults.json
- tests/core/test_read_manifest.py
- tests/core/test_scparam.py
This PR addresses the fact that our change to storing all value-specific data underneath the "node" dict makes the subfields not appear for unset parameters in a manifest. I fixed this by adding a `'default', 'default'` entry that is always empty and is used to initialize the node dict whenever it gets populated, mimicking the pattern that gets used for schema parameter keypaths themselves.
I was originally planning to have `'global', 'global'` be always filled in by default, but I realized this mucks with some of the logic as it loses the distinction between required and optional pernode parameters (required ones should not have a `'global', 'global'` entry).
> Show "node" subfields for unset schema params

- siliconcompiler/core.py
- tests/core/test_archive.py
- Improve `archive()` tests
- To facilitate running multiple tests on a single build directory, I also refactored `archive()` so it's not required to run it from the build working directory
- Add `include` kwarg for selecting files to include
- Provides more flexibility for tuning what goes in the archive
- Replaces `all_files` to ensure that we have orthogonal arguments
- Add configurable logging 
- Helpful for watching progress on large directories, but is disabled by default
- Support archiving multiple jobs
- Helpful for including e.g. PNR and signoff in one tarball
> `archive()` enhancements SC-25

- examples/gcd/gcd_skywater.py
- siliconcompiler/core.py
- siliconcompiler/schema/schema_cfg.py
- siliconcompiler/tools/openroad/sc_constraints.sdc
- tests/core/data/defaults.json
- tests/core/test_datasheet.py
This PR removes some non-useful parameters and adds a whole bunch of new parameters in preparation for using the manifests as sharable objects. A datasheet is the defacto standard abstraction for ICs today. A chip is sold to a customer using the datasheet as the contract between the company and the customer.
- Removing related supply, pin (not useful)
- Making absolute voltage a per pin parameter
- Adding thermal resistance parameters
- Adding pin function (stdcells)
- Making standard a pin mapping feature
- Adding pin polarity (stdcells)
- Adding relpin for all AC parameters (mandatory, multiple clks)
- Adding missing resistence paramters
- Adding electrical spec parameters (adc, opamp, etc)
- Adding reliability section
> Improving datasheet schema

- tests/apps/test_sc_issue.py
- tests/apps/test_sc_show.py
- tests/core/test_check_manifest.py
Some of the CI tests are taking slightly longer than 60 seconds to complete, this adds some guardband around those that appear in last nights failures.
> add additional timeout to some tests to allow for variations in runtime

- .github/workflows/daily_ci.yml
This ensures we checkout the correct ref when triggering the daily run otherwise we keep testing main, instead of testing the actual branch
> checkout client_payload.ref to ensure correct version of SC is tested

- siliconcompiler/core.py
- siliconcompiler/schema/schema_obj.py
- tests/core/test_write_manifest.py
- tests/examples/test_gcd.py
Reworks prune()
Adds loopback test for gcd to ensure python run and manifest based run both work the same
> rework prune to avoid removing information

- siliconcompiler/apps/sc.py
- siliconcompiler/apps/sc_show.py
- tests/apps/test_sc.py
- tests/flows/test_show.py
- tests/targets/test_asic_demo.py
- tests/tools/test_verilator.py
This removes the calls to the apps vias the subprocess module in favor of testing them directly from python with a monkeypatch for the sysargs
> Remove subprocess calls from non-server CI

- siliconcompiler/schema/schema_cfg.py
- tests/core/data/defaults.json
This does not modify the schema functionally, but correct the spacing in the examples and removes double spaces were they were present. Plus corrects the example quotes around generated example code
> correct spacing and quotes in schema cfg

- .github/workflows/server_ci.yml
This change triggers a workflow to deploy the current version of SC to a server instance, and run an end-to-end remote test. It should alert us to potential issues without the need for manual pre-release testing.
> Functional server test

- .github/workflows/server_ci.yml
This should reduce the test volume a bit, and we'll still be able to manually run the deploy/test action for large PRs before merging in the meantime.
> Run server functional tests on merges to main.

- siliconcompiler/utils.py
When the output of a task contains a symbolic link, the `copytree` method fails.
This converts the link to a full path, attempts to make it a symbolic link or copy the file if the initial hard link failed.
> linking fails when link is to a symbolic link

- siliconcompiler/tools/yosys/syn_asic.py
- siliconcompiler/tools/yosys/syn_asic.tcl
- tests/examples/test_gcd.py
Adds:
- this is an initial implementation of hierarchical synthesis for yosys.
Idea:
- break the synthesis step and look for modules below a specific size, those can be flattened and the rest kept and then try again.
> add hierarchical synthesis in yosys 

- siliconcompiler/scheduler.py
The design value is already in the Schema, and `chip.top()` points to the entrypoint parameter.
> Remove '-design' parameter from scheduler.py

- siliconcompiler/targets/asic_demo.py
It looks like the current heartbeat example die area causes divergence in the placement step with very recent versions of OpenROAD on some platforms (Ubuntu 22?)
50um is a nice, round number which works with the newer version, and IIRC this sort of fuzziness in placement convergence is a known issue with very small designs on the order of ~10s of standard cells.
> Round down demo die area to fix platform-dependent replace divergence

- siliconcompiler/core.py
- siliconcompiler/schema/schema_obj.py
- tests/examples/test_gcd.py
- tests/schema/test_manifest.py
- tests/schema/test_schema.py
This PR makes a few small updates to ensure that users can provide file paths as `pathlib.Path` objects for all our core API methods.
`set()`/`add()` are taken care of in the schema value normalization method, and then I added `str()` casts in a few places as needed. The rest of the methods that I audited expand file paths received by the user using `os.path.abspath()`, which already accepts a `pathlib.Path`.
Note that paths are always normalized to strings, so file paths read out of the schema or returned from other SC methods will remain as strings. This just makes user input more flexible.
> Add pathlib support to core API

- siliconcompiler/tools/execute/exec_input.py
Fixes issue found from: https://github.com/siliconcompiler/siliconcompiler/pull/1725
> ignore .pkg.json files in inputs for execute

- setup/_tools.json
OpenROAD has slowed down a good deal on placement and estimation of parasitics, this reverts us to a commit that predates this issue until they are able to fix it.
> revert OpenROAD to last known functional state

- siliconcompiler/tools/icarus/compile.py
This PR adds some additional functionality to the Icarus tool driver:
- Support for ['option', 'libext']
- The ability to select which Verilog language standard to use
- Explicitly provide the top-level module, which is necessary to ensure that ['option', 'entrypoint'] works correctly
> Add support for libext, Verilog standard to Icarus

- siliconcompiler/tools/surelog/surelog.py
- siliconcompiler/tools/verilator/verilator.py
- tests/flows/data/test_libext/lib.verilog
- tests/flows/data/test_libext/top.v
- tests/flows/test_libext.py
This PR implements libext for Surelog and Verilator, implementing a TODO in Surelog and ensuring consistency with Icarus (being added by PR #1736). Also adds a test of this feature, although I'm not a huge fan of adding yet another test that has to execute tools...
> Support libext option for Surelog and Verilator

- requirements.txt
This fixes the path error in python 3.6 for the daily CI
> pin streamlit to 1.9.0 for Python3.6

- .github/workflows/lint.yml
Removing install here speeds up linting a lot.
Also the feedback will be more useful feedback to the user.
The install gets executed in the `python_ci.yml` anyways for every push.
Tested that it still lints by adding violation:
https://github.com/siliconcompiler/siliconcompiler/actions/runs/5521649690/jobs/10070070190
```
./setup.py:7:1: F401 'streamlit' imported but unused
1     F401 'streamlit' imported but unused
Error: Process completed with exit code 1.
```
> Remove install from linter job

- examples/heartbeat/parallel.py
- tests/examples/test_heartbeat.py
- Fixed typo
- To enable the tests again I ran them locally and recorded the time it took:
- test_py 72s
- test_sim 3s
- test_cli 40s
- test_parallel_all_serial 140s
- test_parallel_steps 122s
- test_parallel_flows 72s
Then I adjusted the timeouts.
Let's see if the CI is now happy:
[Daily CI run](https://github.com/siliconcompiler/siliconcompiler/actions/runs/5534007110)
> Enable parallel heartbeat

- siliconcompiler/tools/verilator/compile.py
- siliconcompiler/tools/verilator/verilator.py
This PR updates our Verilator driver to multithread builds according to the SC threads parameter. It uses Verilator's `-j` flag, which should enable multi-threading both in the "Verilation" (RTL->C++) phase and in the C++ compile phase. 
In addition, I decided to bump the minimum required Verilator in order to make use of Verilator's `--build` flag and simplify the driver a bit. 4.028 was the version available in apt for Ubuntu 20.04, but I think newer versions of Verilator are more widespread now (22.04 includes 4.038).
> Multithread Verilator builds

- siliconcompiler/tools/openroad/openroad.py
- siliconcompiler/tools/openroad/scripts/sc_export.tcl
adds the flags needed to be able to control the abstract lef writing to the OpenROAD driver
> add abstract_lef controls to OpenROAD

- siliconcompiler/remote/client.py
This change lets the `check_progress/` API work with HTTP and JSON responses, while we make that transition.
> Enable all-JSON API transition with less strict checking on check_progress responses

- siliconcompiler/remote/client.py
Moving the local import nodes into spawned processes makes them parallelizable, but it also means that failures are silently ignored.
This change detects failed local tasks, and prevents a remote run from being submitted when they don't succeed, which was the behavior before #1755 got merged.
> Fix server CI failures caused by a failure to detect failures in the local import task.

- requirements.txt
- siliconcompiler/report/streamlit_viewer.py
this resizes the flowgraph to take up a maximum amount of space, or 40% if the screen is smaller than 1300 pixels
Here is a before and after:
Before:
After:
Limitations:
- If the user changes the screen width without refreshing, the flowgraph will not change it’s size
> resizes the flowgraph

- docs/_ext/clientservergen.py
Server API is correcting building again: https://siliconcompiler--1769.org.readthedocs.build/en/1769/reference_manual/server_api.html
> fix path to json api for server

- .github/workflows/daily_ci.yml
Use the `setup-python` github action with cached python versions instead of building from scratch. -2min
Use pip cache for packages. -2min
> Simplify and speed-up daily CI

- siliconcompiler/report/streamlit_viewer.py
There was a bit of an oversight on my part when I created the logic to search the data frame. Before, if either of the search bars were empty, the whole data frame was shown because no one wants to see no data. The oversight was that someone may want one axis filtered and one axis unfiltered.
Before:
After:
> fix dataframe search

- siliconcompiler/leflib/_leflib.pyx
The ternary operator was confusing Cython and let to double parantheses being generated e.g. `if ((expr))`. Clang seems to be more sensitive than gcc and issued an extraneous parantheses warning. Because for the leflib we currently treat all warnings as errors the [build was failing](https://github.com/siliconcompiler/siliconcompiler/actions/runs/5605379609/jobs/10256600902).
```
/Users/runner/work/siliconcompiler/siliconcompiler/_skbuild/macosx-10.15-x86_64-3.6/cmake-build/_leflib.cxx:5372:24: error: equality comparison with extraneous parentheses [-Werror,-Wparentheses-equality]
if ((__pyx_v_val == 1)) {
~~~~~~~~~~~~^~~~
```
This simplification fixes the issue.
[Successful build.](https://github.com/siliconcompiler/siliconcompiler/actions/runs/5611131909/jobs/10267090958)
> Fix leflib clang extraneous parantheses

- .github/workflows/wheels.yml
This PR fixes the bug that our compiled Surelog binary reports a missing system library on macOS Big Sur, even though the wheels are marked as compatible with this version. We need to define a special env variable `MACOSX_DEPLOYMENT_TARGET` that the macOS compiler uses to determine backwards compatibility requirements. This variable was previously set in the context where our leflib C-extension was built, but not for Surelog.
@mayagokhale tested out a binary built with this env var set, I'm re-running a wheels build from scratch with the macOS Surelog cache invalidated: https://github.com/siliconcompiler/siliconcompiler/actions/runs/5616770044. 
Closes #1732.
> Ensure compiled Surelog is backwards compatible with older macOS versions

- siliconcompiler/remote/client.py
- siliconcompiler/remote/server.py
Since the "job hash" identifier is now implemented as a UUID rather than a literal hash of the files/archive being uploaded, we can have the server generate it for the client instead of accepting it as an input parameter.
This change updates SC's remote client to use a job ID from the server's response, instead of generating its own.
> Update remote client to use job IDs generated by the server.

- siliconcompiler/tools/openroad/openroad.py
- siliconcompiler/tools/openroad/scripts/sc_apr.tcl
- siliconcompiler/tools/openroad/scripts/sc_procs.tcl
- siliconcompiler/tools/openroad/scripts/sc_write_images.tcl
- tests/apps/test_sc_show.py
- tests/conftest.py
- tests/tools/test_openroad.py
Adds:
- image generation at the end of each OpenROAD task: placement, routed nets, heatmaps, clock trees, etc.
> Adds OpenROAD image generation to the openroad tool driver

- docs/user_guide/quickstart.rst
" If you've completed the :ref:`Installation` section and **was** able to run the :ref:`ASIC Demo`, you will have completed a simple remote run through an ASIC design flow! " 
--> 
" If you've completed the :ref:`Installation` section and **were** able to run the :ref:`ASIC Demo`, you will have completed a simple remote run through an ASIC design flow!"
> fixing was --> were

- siliconcompiler/remote/client.py
This fixes the recently-added `error_action` on the `get_results` call - the function signature expects two arguments.
> Fix error_action signature in get_results call

- siliconcompiler/tools/openroad/openroad.py
- siliconcompiler/tools/openroad/scripts/sc_place.tcl
- siliconcompiler/tools/openroad/scripts/sc_procs.tcl
- tests/examples/test_gcd.py
Fixes:
- pin placement generates very dense pin placement when the design is not placed, this avoids this when there are unplaced instances in the design.
> gate pin placement refinement if there are unplaced instances

- siliconcompiler/remote/client.py
I accidentally left one of the `start_time` parameters in - finishing that removal will fix our check_progress calls.
The end-to-end tests still passed because the jobs eventually complete and bypass the `_process_progress_info` call.
> Fix check_progress calls

- tests/apps/test_sc_remote.py
Pending a better solution for detecting server readiness when we run it as a command line app during CI tests.
> Extend server startup delay to account for emulated ARM slowdown

- siliconcompiler/apps/sc_remote.py
- siliconcompiler/core.py
- tests/apps/test_sc_remote.py
After some more end-to-end testing on AWS, a couple of small improvements to the `-reconnect` flag.
* Produce a final summary manifest like a `chip.run()` call normally does.
* Omit local steps from the steplist, so the client doesn't try to fetch them from the server.
* Print a summary similar to a normal CLI run.
> Update steplist and summary logic in `sc-remote -reconnect`

- siliconcompiler/remote/client.py
We should treat failures to fetch remote results for individual flowgraph nodes as warnings, so that they don't prematurely fail out of the job run.
Individual nodes could fail in a way that is not fatal for the entire job, for example in a branching flowgraph. Interrupting the job when a result cannot be fetched could also interfere with ongoing downloads for other nodes which did complete. Finally, SC is already set up to report build failures after the client attempts to fetch all of its results.
> Update get_results error to allow single nodes to fail without interrupting the whole job

- siliconcompiler/core.py
- tests/core/test_collect.py
*What?*
Update source files that get uploaded to remote after editing them.
*Why?*
Currently we assume that if a file is present in the `sc_collected_files` directory we don't need to refresh it.
Of course a user might edit a file between runs.
*How?*
As an intermediate solution we can clear the `sc_collected_files` directory before a run.
Long term wise we should probably hash the files content and update only the files that changed.
*Test*
Edits files before collecting them for a second run.
The test fails before the changes and passes after the changes.
> Clean sc_collected_files before next run

- siliconcompiler/core.py
- tests/core/test_check_display.py
- tests/core/test_ssh_nodisplay.py
**What?**
Automatically enable `-nodisplay` for ssh or other configurations without display on linux.
**Why?**
On ssh it's one extra step to enable the nodisplay option. So this improves usability.
**How?**
We check the the `$DISPLAY` and `$WAYLAND_DISPLAY` variables on linux.
**Test:**
Checks that nodisplay is set on linux with x11 or wayland.
Additionally checks there are no regressions on other platforms.
> Set -nodisplay for ssh

- tests/flows/test_failure.py
fixes two failing CI tests based on the new exit quickly logic
also adds them to the quick list since they take almost no time to run.
> fix failure tests to pass based on new exit logic

- tests/core/test_check_display.py
**What?**
The wheels test on Windows with Python 3.11 fails with no apparent reason.
https://github.com/siliconcompiler/siliconcompiler/actions/runs/5873062166/job/15927788456
**Why?**
There seems to be some weird changes going on related to the environment variables on Windows + Python 3.11.
**How?**
Write a proper fixture so variables are not shared between tests.
Don't run the failing test cases on the platform
**Test**
Wheels passes again:
https://github.com/siliconcompiler/siliconcompiler/actions/runs/5883403874/job/15956049276
**Original failing test for documentation purposes**
```
___________________________ test_check_display_run ____________________________
@patch('sys.platform', 'linux')
def test_check_display_run():
chip = siliconcompiler.Chip('test')
flow = 'test' …
```
> Skip failing wheels test on Windows with Python 3.11

- siliconcompiler/tools/verilator/compile.py
- siliconcompiler/tools/verilator/lint.py
- siliconcompiler/tools/verilator/verilator.py
This PR moves Verilator driver command line options to `runtime_options()`. This makes it so a user can supply custom CLI options using the tool/task parameter. 
cc @petergrossmann21
> Refactor Verilator driver to allow user options

- siliconcompiler/scheduler.py
We have seen some intermittent failures in the Slurm tests, which appeared to be caused by the scheduler module encountering unexpected states when it looks at the job queue.
This change adds two more non-error states which are uncommon, but may be reported during normal Slurm runs.
> Track all possible Slurm job states

- siliconcompiler/schema/schema_obj.py
- tests/schema/test_unset.py
This is useful when removing previously set constraints like components or timing corners.
Only allows removal of user definable keys (ie. default keys)
> add _remove to schema object to help remove default keys

- siliconcompiler/remote/client.py
Allows a user to do Control+C to exit out of SC and gives the required information to resume the connection
> add : cntrl+c capturing to remote run 

- examples/gcd/gcd.py
- examples/gcd/gcd_multiflow.py
- tests/examples/test_gcd.py
I couldn't find a reason as to why this option is enabled for regular test cases.
> Remove skipcheck from gcd test cases

- siliconcompiler/tools/openroad/openroad.py
- siliconcompiler/tools/openroad/scripts/sc_apr.tcl
Changing macro_extension in openroad to 0 by default as this makes routing easier in almost all cases.
> fix default setting for macro extensions and add helper messages to global router setup

- siliconcompiler/schema/schema_obj.py
- tests/schema/test_schema.py
This PR fixes a bug where setting a single "scalar" value for a list-of-tuples field using a list rather than a tuple is considered invalid. There's a bit of ambiguity here when parsing the type/value from the "outside-in", so I think the easiest solution without restructuring this code is to speculatively consider the value in each possible way and see which works.
> Fix normalization of list to tuples for list-of-tuples

- siliconcompiler/apps/sc_remote.py
- siliconcompiler/core.py
- siliconcompiler/remote/client.py
- siliconcompiler/remote/server.py
- siliconcompiler/report/report.py
- siliconcompiler/scheduler.py
- siliconcompiler/schema/schema_cfg.py
- tests/apps/test_sc_remote.py
- tests/core/data/defaults.json
Like we've discussed offline, the job ID values could easily be moved into the core schema, instead of using the ephemeral `chip.status` dictionary, which we would like to get rid of eventually.
This PR implements the client-side changes required to do that. I bumped the schema's minor version number instead of its patch number, because v0.35.0 manifests will not work with servers that are using the new version for remote runs.
I also updated the `sc-remote` CLI app to replace its `-jobid` CLI parameter with `-cfg`, which was already required for reconnecting to a running job. That required a little bit of extra logic to insert the job ID values into the manifests produced by the locally-run entry steps, because the client doesn't know what its job ID will be until it submits a job and …
> Move job IDs into the core Schema

- .github/workflows/daily_ci.yml
- .github/workflows/docker_image.yml
**What?**
This commit introduces a github action that takes the tool as an input and returns the latest version of its docker image.
**Why?**
We currently copy and paste the code to retrieve the latest version of the `sc_tools` images.
This is also the case for sclib, zerosoc and scscerver.
**Successful run:**
https://github.com/siliconcompiler/siliconcompiler/actions/runs/6039399625
> Reuse docker image

- .github/workflows/docker_image.yml
For https://github.com/siliconcompiler/zerosoc/pull/32 it is useful to have the latest released version available.
**Succesful run of daily CI - targeting this branch**
https://github.com/siliconcompiler/siliconcompiler/actions/runs/6050735765
> Allow latest version docker image

- siliconcompiler/__init__.py
- siliconcompiler/_common.py
- siliconcompiler/core.py
- siliconcompiler/remote/client.py
- siliconcompiler/report/streamlit_viewer.py
- siliconcompiler/report/utils.py
- siliconcompiler/tools/builtin/_common.py
- tests/apps/test_sc_remote.py
- tests/builtin/test_minmax.py
- tests/core/test_check_flowgraph_io.py
- tests/core/test_check_manifest.py
- tests/core/test_summary.py
- tests/flows/test_flowstatus.py
- tests/flows/test_multiple_tools.py
- tests/flows/test_steplist.py
- tests/flows/test_tool_option.py
**What?**
Refactor of `run()` no functionality changes.
Also solves SC-586
**Why?**
SC-557, SC-562 and others are difficult to do since `_runtask()` and `run()` are huge function in which changes could easy break something important.
**How?**
We split up `run()` to make editing and testing the steps of the flow easier.
**Test**
So far just the existing test cases.
I could add further ones if necessary.
[Successful run on remote server](https://github.com/zeroasiccorp/scserver/actions/runs/6023567892/job/16340572454)
> Split up run()

- siliconcompiler/remote/client.py
This will make it easier to allow remote jobs to be resumed, and aid debugging. Splitting this self-contained change off from #1934 at Peter's request.
After this change, jobs will either be automatically deleted after a period of inactivity, or when the user manually runs `sc-remote -cfg [...] -delete`.
> Remove the 'delete_job' call from the client

- siliconcompiler/remote/client.py
- tests/apps/test_sc_remote.py
Leaving username and password empty is currently not allowed but would be very helpful to connect to a test instance of scserver.
> Allow no username and password in cmd

- siliconcompiler/core.py
Cleanup from https://github.com/siliconcompiler/siliconcompiler/pull/1937
Replace any remaining uses of `self.getkeys('flowgraph',)` with `self._get_flowgraph_nodes()`.
Any now remaining instances of `self.getkeys('flowgraph',)` require the rewrite with `from/to`.
> Flowgraph nodes remaining instances

- siliconcompiler/tools/openroad/scripts/sc_route.tcl
Just did an initial run of the [`ttclcheck` linter](https://wiki.tcl-lang.org/page/ttclcheck).
It's the linter used in Vivado.
Still haven't figured out completly how to set up openroad and other dependencies but I found my first real error within seconds.
Hopefully we can set it up properly and integrate it soon...
> Lint - Fix unknown proc openroad_pin_access_args

- siliconcompiler/apps/sc_remote.py
- siliconcompiler/apps/sc_run.py
- siliconcompiler/core.py
- siliconcompiler/tools/yosys/markDontUse.py
- siliconcompiler/tools/yosys/syn_asic.py
Changes:
- all tool outputs is directed through the logger
Motivation:
- on parallel executions outputs to the terminal ambiguous, this ensures they get the prefix for the step and index it belongs to.
Before:
```
| WARNING | job0  | import     | 0  | [WRN:PA0205] /siliconcompiler/examples/gcd/gcd.v:586:1: No timescale set for "ZeroComparator_0x422b1f52edd46a85".
| WARNING | job0  | import     | 0  | [WRN:PA0205] /siliconcompiler/examples/gcd/gcd.v:615:1: No timescale set for "Mux_0x683fa1a418b072c9".
| WARNING | job0  | import     | 0  | [WRN:PA0205] /siliconcompiler/examples/gcd/gcd.v:658:1: No timescale set for "Mux_0xdd6473406d1a99a".
| WARNING | job0  | import     | 0  | [WRN:PA0205] /siliconcompiler/examples/gcd/gcd.v:698:1: No timescale set for "Subtractor_0x422b1f52edd46a85".
| …
```
> direct all outputs through logger

- siliconcompiler/apps/sc_issue.py
- siliconcompiler/core.py
- siliconcompiler/remote/client.py
- tests/core/test_error_manifest.py
**What?**
- Write output manifest on all steps including failures.
- Write the schema when possible
- Replace file existence as criteria for node success when resuming
**Why?**
Currently the manifest does not capture the schema after every node execution.
In particular failed nodes do not have a written manifest and won't be part of the final schema.
It also is one step further to eventually get rid of the `status` dictionary.
**How?**
We now write the manifest on non fatal errors which are captured by `_haltstep`.
This requires reading the manifest to get the node status instead of just checking if the manifest exists for resuming.
If the node does not get executed at all because its input dependencies failed then we don't write a manifest.
**Testing**
- tests/flowgraph.py
- …
> Merge and write manifest on error

- siliconcompiler/core.py
- siliconcompiler/schema/schema_obj.py
Setup node for OpenROAD is noticeably slow. This appears to be from all the calls to `valid()`
This change speeds that up by ~178x.
Before profile:
```
3556918 function calls (3413821 primitive calls) in 3.751 seconds
```
After profile:
```
58632 function calls (53019 primitive calls) in 0.021 seconds
```
Also removes seemingly unused `valid_keypaths` argument from `.valid`
> speeds up .valid by simply checking the schema dictionary instead of requiring the allkeys()

- siliconcompiler/scheduler.py
**What?**
Pass through errors from slurm jobs on "small" server.
**Why?**
Currently on the local slurm setup (used by the `siliconcompiler/remote/server.py` and `test_slurm_local.py`) it is not possible to debug a failed node as the returncode of `touch` overshadows that one of `sc`.
Additionally in case of a failed run no information about the failure is printed.
As far as I can tell this does not affect "real" scserver because scserver has different `stepindex.sh` scripts.
**How?**
Remove last `touch` to create success file (on failure).
Add slurm output to error log which contains the exit code, run script location and run log location.
**Before:**
```
--------------------------------------------------------------------------------- Captured stdout setup …
```
> Allow debugging failed slurm jobs on "small" server

- setup.py
because `sc` is a system alias in Windows powershell, this provides a full name `siliconcompiler` cli app which is an alias to `sc` to allow for easier use on Windows.
> provide siliconcompiler cli app as alias for sc

- setup/_tools.json
- siliconcompiler/tools/yosys/prepareLib.py
- siliconcompiler/tools/yosys/syn_asic.py
- siliconcompiler/tools/yosys/syn_asic.tcl
- siliconcompiler/tools/yosys/yosys.py
- tests/examples/test_gcd.py
This removes the need to modify the libraries for ABC to mark cells as dont_use, but instead use the new -dont_use.
> Update yosys to make use of new -dont_use flag to ABC

- siliconcompiler/core.py
- siliconcompiler/schema/schema_obj.py
- tests/core/test_get_copy.py
**What?**
Always copy the list or other objects that would otherwise returned by reference from the schema.
**Why?**
Benazeer was most recently running into accidental edits of lists in the schema.
I have personally noticed this in the past.
**Issues:**
I'm not sure if this is "deep" enough.
Maybe this should even be on the `schema.get()` level.
**Testing:**
tests/core/test_get_copy.py
> Return copy instead of reference for chip.get()

- examples/gcd/gcd.py
- tests/examples/test_gcd.py
- tests/fixtures.py
- tests/flows/test_tool_option.py
- tests/tools/test_openroad.py
Ran into this while working on https://github.com/siliconcompiler/siliconcompiler/pull/2000
I'm not quite sure why it got removed in the first place.
> Add version check back in to examples and tests

- .github/workflows/daily_ci.yml
- .github/workflows/python_ci.yml
- .github/workflows/wheels.yml
- README.md
- docs/user_guide/installation.rst
- requirements.txt
- setup.py
- siliconcompiler/core.py
- siliconcompiler/report/streamlit_report.py
- tests/core/test_dashboard.py
This removes support for 3.6 and 3.7.
Changes:
- removes wheels builds for those versions
- updates docs to use minimum version of 3.8
> deprecate support for python3.6 and python3.7 as they are EOL

- siliconcompiler/tools/verilator/verilator.py
- tests/data/assert.v
- tests/tools/test_verilator.py
This makes it possible to use assertions in Verilator to help with verification.
**Usage:**
```
sc ... \
-tool_task_var 'verilator compile enable_assert true' 
```
**Before:**
I.e. `assert(0)` was ignored.
**After:**
```
[0] %Error: heartbeat.v:10: Assertion failed in TOP.heartbeat: 'assert' failed.
%Error: inputs/heartbeat.v:10: Verilog $stop
Aborting...
```
> Enable assertion support in verilator

- .github/workflows/python_ci.yml
- tests/apps/test_sc_remote.py
- tests/leflib/test_leflib.py
Once leflib is fully ported the only thing needed for each os is the graphviz install.
> add windows and macos to python ci tests

- siliconcompiler/schema/schema_obj.py
- tests/core/test_create_cmdline.py
- tests/schema/test_manifest.py
This change will allow us to open older schemas without failing out.
This is useful when attempting review older runs, but the schema has changed since that run and now.
> read schema manifest despite missing keys

- siliconcompiler/core.py
- tests/apps/test_sc.py
- tests/core/test_collect.py
- tests/core/test_find_file.py
Fixes:
- when getting a remote submission which was started on windows, the path format wasn't handled correctly on the linux machines.
- this ensures that the path and path hashing is all handled as posix paths to avoid any compatibility issues.
Replaces: #2005
> fix handling of windows paths

- siliconcompiler/core.py
- tests/core/test_nodes_to_execute.py
- tests/flows/test_prune.py
**What?**
Changes the approach used when determinig which nodes to execute from a breadth first approach with to as a border to a path based approach with to as the final node(s).
Additionally change behavior to ignore from/to when using a different flow than the currently set flow.
**Why?**
Extra test cases mimic the behavior of usage did not align with the currently used algorithms
> Test cases for to from

- siliconcompiler/remote/client.py
**What?**
Fix for https://github.com/siliconcompiler/siliconcompiler/issues/2036
**Why?**
The public version of the server somehow loses the information that the entry nodes were already executed.
The issue is not reproducible on the server CI which receives the import node status information as expected.
**How?**
Set the starting point on server explicitely with `-from` in the client.
**Successful Test**
```
sc -target asic_demo -remote
____  _ _ _                    ____                      _ _
/ ___|(_) (_) ___ ___  _ __    / ___|___  _ __ ___  _ __ (_) | ___ _ __
\___ \| | | |/ __/ _ \| '_ \  | |   / _ \| '_ ` _ \| '_ \| | |/ _ \ '__|
___) | | | | (_| (_) | | | | | |__| (_) | | | | | | |_) | | |  __/ |
|____/|_|_|_|\___\___/|_| |_|  \____\___/|_| |_| |_| .__/|_|_|\___|_|
|_|
Authors: …
```
> Explicitely set -from for public server

- .github/workflows/python_ci.yml
- .github/workflows/tools_ci.yml
**Why?**
The Python CI and Tools CI don't get executed on pull requests currently. See for example [here](https://github.com/siliconcompiler/siliconcompiler/pull/2004).
**Testing:**
After merging this into main we should double check that changes to the workflows from external contributors are only executed after approval: https://docs.github.com/en/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks
> Run python and tools CI on pull requests

- .github/workflows/wheels.yml
**Why?**
Alternative source for the releases.
**Testing:**
We should double check on our next smaller release that all artifacts were uploaded as expected.
> Add wheels to GitHub release artifacts

- siliconcompiler/core.py
- tests/core/test_check_logfile.py
**Why?**
This makes it easier to figure out where the warning and errors come from in the original log.
@gadfort I added it to infos and the logger output as well.
Do you think that's a good idea or should I remove it?
> Add line numbers to parsed logs

- siliconcompiler/core.py
- siliconcompiler/remote/client.py
- siliconcompiler/tools/builtin/_common.py
- siliconcompiler/utils.py
- tests/apps/test_sc_issue.py
**Why?**
We [deprecated python 3.6 and 3.7 ](https://github.com/siliconcompiler/siliconcompiler/commit/84ce9c1f060cbce78877ea55365f7d3e0dbb13ed)so now we can rely on `shutil.copytree()`.
**How?**
Using `shutil.copytree()` and its `copy_function` and `ignore` parameters we can achieve the same functionality as `utils.copytree()`.
> Replace utils.copytree() with shutil.copytree()

- .github/workflows/bin/setup_wheel_env_linux.sh
- .github/workflows/wheels.yml
**What?**
Fix tests depending on Klayout
**Why?**
Klayout was not installed on Linux and `show` based tests were skipped.
**How?**
Turns out all source files including the `setup` directory are getting copied as expeted.
So it was just necessary to pass in the source directory and fix a typo.
**Before:**
https://github.com/siliconcompiler/siliconcompiler/actions/runs/6527358684/job/17722145244
**After:**
https://github.com/siliconcompiler/siliconcompiler/actions/runs/6535081745/job/17743780717
> Ensure show runs on wheels ci for linux

- siliconcompiler/tools/klayout/klayout_utils.py
This fixes a problem where even though the dbu is set in the technology, the final layout after the export step was not adhering to that. The layoutOptions class was resetting the layout dbu to that of the layout being read in.
> Change layout options to read layouts with the technology dbus

- siliconcompiler/schema/schema_cfg.py
- tests/core/data/defaults.json
**What?**
Remove the valid bit from the schema. 
Change the `patch` number in the schemaversion because it was never implemented to begin with.
**Why?**
Now we have `-prune` to specify which paths/nodes in the flowgraph will not be run.
Therefore attaching the valid bit to nodes in the flowgraph is not necessary.
> Remove valid bit from schema

- siliconcompiler/core.py
- tests/core/data/place.log
- tests/core/test_check_logfile.py
**What?**
Order matched suffixes in logfiles from tools as follows `[..., 'warnings', 'errors']`.
Also show a small summary of the number of each suffix.
**Why?**
Improves readability of log output.
**How?**
Reorder the way the log files are scanned.
**Example output:**
```
| WARNING | job0 | export | 0 | 28: [WARNING] no fill config file specified
| INFO    | job0 | export | 0 | Number of warnings: 1
| INFO    | job0 | export | 0 | Number of errors: 0
```
> Error and warning parsing should split the print of errors and warnings

- .github/workflows/daily_ci.yml
- .github/workflows/tools_ci.yml
Reworks container credentials to use Github actor/token for read-only
access, only using secrets for write access where needed. This means if
tools aren't changed, external contributors can run the tools CI
normally. If tools are changed, a member will have to trigger the
workflow themself.
There was an administrative change required to make this work. In order to keep the packages private for now, and ensure `{{ github.token }}` provides read access, each package has to have the following set in its individual Package Settings:
Most packages had nothing here, although a few were set to "Admin". I've set them all to have "Read" permissions in order to be consistent. 
Test PRs:
- External contribution with no tools changed (expect pass): …
> Ensure external contributors can run tools CI [SC-668]

- setup/docker/builder.py
I'm not sure if this is required, I haven't noticed any related bugs... but I noticed this when I was implementing  #2067. The structure of the code as written doesn't seem right, since I don't think this call has any point otherwise.
> Fix docker image existence check

- siliconcompiler/core.py
- siliconcompiler/tools/bambu/convert.py
- siliconcompiler/tools/bluespec/convert.py
- siliconcompiler/tools/chisel/convert.py
- siliconcompiler/tools/klayout/klayout.py
- siliconcompiler/tools/magic/magic.py
- siliconcompiler/tools/netgen/lvs.py
- siliconcompiler/tools/openroad/openroad.py
- siliconcompiler/tools/template/template.py
- siliconcompiler/tools/vivado/vivado.py
- siliconcompiler/tools/yosys/yosys.py
- tests/core/test_find_file.py
Removes searching of scroot from SC and relies only on the packaging
> switch tools refdir to use siliconcompiler package

- siliconcompiler/tools/openroad/scripts/sc_write_images.tcl
Fixes a small bug caught by the tclint indent check.
> Add missing backslash

- requirements.txt
- siliconcompiler/tools/openroad/scripts/sc_apr.tcl
- siliconcompiler/tools/yosys/syn_asic.tcl
I think I caught a subtle bug in a few Tcl procs caused by supplying an expression directly to `return`. 
It seems like Tcl will always return the last word of the expression:
```tcl
proc foo {} {
return 0 && 1
}
puts [foo]
```
prints 1 for me. This can be fixed by adding an `expr` command to wrap the expression.
`tclint` 0.1.2 now catches this issue.
> Add expr to unwrapped Tcl return expressions

- pyproject.toml
- requirements.txt
- siliconcompiler/tools/openroad/scripts/sc_apr.tcl
- siliconcompiler/tools/openroad/scripts/sc_constraints.sdc
- siliconcompiler/tools/openroad/scripts/sc_physyn.tcl
- siliconcompiler/tools/openroad/scripts/sc_screenshot.tcl
- siliconcompiler/tools/openroad/scripts/sc_write_images.tcl
- siliconcompiler/tools/vivado/scripts/sc_syn_fpga.tcl
- siliconcompiler/tools/yosys/sc_syn.tcl
This uses the new `tclint` fileset configuration feature to set an alternate indent for the OpenROAD scripts, which made it a lot quicker to clean up. There were 2 files in the OpenROAD scripts that used 4 space indent, but I transitioned them over in this PR.
> Enable tclint indent checks and fix violations

- .github/workflows/bin/setup_wheel_env_linux.sh
- siliconcompiler/tools/klayout/klayout.py
- siliconcompiler/tools/klayout/klayout_export.py
- siliconcompiler/tools/klayout/klayout_operations.py
- siliconcompiler/tools/klayout/klayout_show.py
- siliconcompiler/tools/klayout/klayout_utils.py
- tests/flows/test_show.py
Switch to importing schema module by file to avoid name collision with other `schema` module.
Fix wheels to correctly install klayout again and re-enable those tests
> fix klayout

- pyproject.toml
- requirements.txt
- siliconcompiler/tools/netgen/sc_lvs.tcl
- siliconcompiler/tools/openroad/scripts/sc_procs.tcl
- siliconcompiler/tools/openroad/scripts/sc_route.tcl
This PR updates `tclint` with the latest version that implements your suggestion (https://github.com/nmoroze/tclint/issues/5), and fixes violations accordingly.
Note that the default allows for 2 consecutive newlines (since I've seen that commonly used), but I updated it here to match your suggestion in the tclint issue.
> Update tclint to check blank lines

- examples/benchmark/benchmark.py
I wasn't able to run the "benchmark" example, it seems like some of the schema keypaths are from an older version of siliconcompiler.
> Fix "benchmark" example

- siliconcompiler/tools/klayout/klayout_show.py
- siliconcompiler/tools/klayout/show.py
This allows using klayout built without Qt bindings with siliconcompiler. The Qt bindings were only used to grab an image of a `LayoutView` and then save it to a .png. This can be achieved by calling `save_image()` directly which combines those two steps in a single call without the need of handling an intermediate Qt object.
Tested this with the normal klayout export task as well as the gcd_screenshot example.
> Remove dependency on klayout Qt bindings for saving screenshots

- .github/workflows/conda_ci.yml
- setup/conda/environment.yml
This fixes the Conda CI Test by forcing the environment setup to use python>=3.8, which apparently also solves the dependency problem with the old ruby version.
> Fix Conda CI Tests and environment

- siliconcompiler/core.py
Logfile parsing (`check_logfile`) happens in the spawned subprocess and uses (when encountering invalid encoding) the error handlers registered with the `codecs` registry in the main process. This works when using `fork`, but not with `spawn` which will lead to an error like this when a logfile contains invalid characters:
```
Process SpawnProcess-1:
[...]
LookupError: unknown error handler name 'ignore_with_warning'
```
This example shows the difference in passing on the codec registry to child processes when using `spawn`/`fork`:
```python
import codecs
import multiprocessing
def subprocess():
print("Triggering error in sub process")
b"\xf5".decode(encoding="UTF-8", errors="ignore_with_warning")
def main():
def log_error_handler(e):
print("I am the …
```
> Initialize codec error handlers in each spawned subprocess

- tests/core/data/failing_tool.sh
- tests/core/test_codecs.py
- tests/core/tools/run/run.py
This test runs a step producing output/logfile with invalid UTF-8. This tests whether the codecs error handling works correctly in a spawned subprocess.
> Add test for error handlers in codecs

- siliconcompiler/tools/yosys/syn_asic.py
- siliconcompiler/tools/yosys/syn_asic.tcl
I think this is quite a useful option to have when running only a yosys frontend flow through siliconcompiler. It allows masking out RTL modules, which would later be replaced my macro cells without having to modify the RTL.
> Yosys: Introduce parameter allowing to mask out RTL modules

- siliconcompiler/core.py
This gives users the option to override `_getworkdir()` with a custom scheme and keep everything else working.
> Consistently use `Chip._getworkdir()`

- siliconcompiler/tools/yosys/mergeLib.py
ABC does not support having multiple liberty files. Hence it is required to first merge all liberty files before passing it to abc. An issue can occur when those different liberty files contain templates that have the same name in different files but with different formats.
This fix does a proper merging by renaming the templates across the files.
This has been discussed in lambdapdk repository, see issue here: https://github.com/siliconcompiler/lambdapdk/issues/34
> Fix liberty files templates issues when using multiple liberty files

- siliconcompiler/core.py
- siliconcompiler/flowgraph.py
- tests/core/test_summary.py
before nodes before "option/from" would be excluded.
> ensure start of flow is present in summary

- siliconcompiler/apps/sc_issue.py
- siliconcompiler/remote/client.py
- siliconcompiler/scheduler/__init__.py
- siliconcompiler/schema/schema_cfg.py
- siliconcompiler/tools/openroad/openroad.py
- tests/core/data/defaults.json
Adds:
- option/scheduler/maxnodes to schema to control maximum number of parallel jobs allowed in the local scheduler
- honor requested number of threads against local machines total number of threads to avoid overloading system.
> ensure local runs honor thread resources

- .github/workflows/tools_ci.yml
- requirements.txt
- siliconcompiler/tools/openroad/scripts/sc_rcx_bench.tcl
I just released a new version of tclint that adds an OpenROAD plugin for checking its tool-specific commands. This PR fixes an issue it caught and demonstrates how you can add it to CI.
Using the plugin is more involved than just enabling it in the regular job - in order to be responsive to OpenROAD API changes, the plugin requires generating a "command spec" in an environment that has OpenROAD installed. I figured the simplest approach to adding it to the SC CI was to add it as a new job to the tool CI workflow. I kept the regular Tcl lint check as a fast failure path.
Here's an example of a [passing](https://github.com/nmoroze/siliconcompiler/actions/runs/9440700733/job/26000427774) and [failing](https://github.com/nmoroze/siliconcompiler/actions/runs/9440506425/job/25999939939) check …
> Add OpenROAD command checking with tclint

- .github/workflows/daily_ci.yml
Currently entire gallery with no rules are enforced, except timeout.
This will increase the runtime from ~50 minutes to 3:30 hours, but for the daily/nightly tests this is acceptable.
https://github.com/siliconcompiler/siliconcompiler/actions/runs/9537997312
> move daily tests to use scgallery

- requirements.txt
- siliconcompiler/scheduler/__init__.py
- tests/core/test_track.py
netifaces does not have a maintainer and installing it requires you to compile the package which is cumbersome on windows.
adds a test for tracking to ensure values are logged.
> Replace netifaces with psutil

- siliconcompiler/schema/schema_cfg.py
- tests/core/data/defaults.json
Net name is not always identical to the port name.
> Adding missing portname for pin definition

- pyproject.toml
- siliconcompiler/schema/schema_obj.py
When orjson is not available will fall back to builtin json:
https://catnotfoundnear.github.io/finding-the-fastest-python-json-library-on-all-python-versions-8-compared.html
https://github.com/siliconcompiler/siliconcompiler/actions/runs/10578020768
> use orjson to write schema

- siliconcompiler/schema/schema_cfg.py
- tests/core/data/defaults.json
- tests/core/data/last_minor.json
- Removing net/port parameters doesn't belong here. The datasheet should not describe things intenal to device, slipper slope.
- Adding a 'pin' key for better grouping. Previously I had optimized brevity over clarity (bad choice)
- Adding missing logical pin 'name' mapping to package
> Updating package pin schema

- siliconcompiler/schema/schema_cfg.py
- tests/core/data/defaults.json
- tests/core/data/last_minor.json
- tests/core/test_read_manifest.py
- Making the default ASIC design, our bread and butter
- @gadfort pointed out that since the default in the ASIC world is lower left corner, using the center coordinate adds extra work/code for the user and in the tool specific driver....non intuitive.
- Adding origin parameter to support packaging and board design
> Changing the default origin from center to lower left corner

- .github/workflows/lint.yml
- pyproject.toml
- siliconcompiler/tools/_common/tcl/sc_pin_constraints.tcl
- siliconcompiler/tools/magic/sc_drc.tcl
- siliconcompiler/tools/magic/sc_extspice.tcl
- siliconcompiler/tools/magic/sc_magic.tcl
- siliconcompiler/tools/netgen/sc_lvs.tcl
- siliconcompiler/tools/openroad/scripts/sc_apr.tcl
- siliconcompiler/tools/openroad/scripts/sc_cts.tcl
- siliconcompiler/tools/openroad/scripts/sc_dfm.tcl
- siliconcompiler/tools/openroad/scripts/sc_export.tcl
- siliconcompiler/tools/openroad/scripts/sc_floorplan.tcl
- siliconcompiler/tools/openroad/scripts/sc_metrics.tcl
- siliconcompiler/tools/openroad/scripts/sc_physyn.tcl
- siliconcompiler/tools/openroad/scripts/sc_procs.tcl
- siliconcompiler/tools/openroad/scripts/sc_rcx.tcl
- siliconcompiler/tools/openroad/scripts/sc_route.tcl
- siliconcompiler/tools/openroad/scripts/sc_screenshot.tcl
- siliconcompiler/tools/openroad/scripts/sc_write_images.tcl
- siliconcompiler/tools/opensta/scripts/sc_procs.tcl
- siliconcompiler/tools/vivado/scripts/sc_run.tcl
- siliconcompiler/tools/yosys/sc_lec.tcl
- siliconcompiler/tools/yosys/sc_syn.tcl
- siliconcompiler/tools/yosys/syn_asic.tcl
- siliconcompiler/tools/yosys/syn_fpga.tcl
Announcing that `tclint` finally includes a formatter (`tclfmt`) by way of this PR!
The first commit is the result of running the formatter on the code (`tcfmt --in-place .`). It mostly follows `tclint`'s style guide, and uses the same configuration. There are two categories of changes that are responsible for most of the diff that perhaps might be controversial:
- `tclfmt` pushes the braces for multi-line expressions onto different lines. There were a couple reasons for doing this, the main one is that it consistently looks good across differently configured indent levels (the style currently used by this repo can sometimes have a case where the expression of an if statement is indented the same as the body, for example). 
- It breaks `set` alignment. This was just a case of being more …
> Format Tcl code using `tclfmt`

- MANIFEST.in
- pyproject.toml
The wheel install slows down a good amount when installing as editable because its iterating over all files. this avoids this.
https://github.com/siliconcompiler/siliconcompiler/actions/runs/10838253192
> fix editable wheel install speed

- examples/picorv32_ram/picorv32_ram.py
- siliconcompiler/schema/schema_cfg.py
- siliconcompiler/tools/openroad/scripts/sc_floorplan.tcl
- tests/core/data/defaults.json
- tests/core/data/last_minor.json
- tests/schema/test_unset.py
1. Removing the recent experimental 'origin' parameter in the constraints. This doesn't belong here. The information is squarely the domain of the underlying device (LEF or another SC object), should not be repeated here. 
2.  Adding a mission 'anchor' parameter in the datasheet package section
3. Merging the flip and rotation parameters into a single paramter that is consistent with DEF. The rotation specified in degrees was unconstrained. For ASICs there are no arbitrary placement rotations.
4. Unifying [ackage/constraints dimension units around 'um'. It was confusing to make some constraints in um and the package in mm.
> Package design schema updates 

- siliconcompiler/scheduler/__init__.py
This was needed when the remote was doing some local processing, since this was removed, this should no longer be needed.
https://github.com/siliconcompiler/siliconcompiler/actions/runs/10909828428 - passing
> dont force spawning

- siliconcompiler/scheduler/__init__.py
This issue appears when running magic which seems to be modifying the terminal echo.
> use stdin DEVNULL to avoid tools modifying user terminal

- setup/docker/builder.py
- setup/docker/slurm/slurm.conf.in
Before
```
112.05s call     tests/flows/test_slurm_local.py::test_slurm_local_py
```
After
```
76.10s call     tests/flows/test_slurm_local.py::test_slurm_local_py
```
> speedup slurm for CI

- siliconcompiler/remote/schema.py
- siliconcompiler/remote/server.py
- tests/conftest.py
Before
```
112.94s call     tests/server/test_slurm_server.py::test_gcd_server
85.01s call     tests/server/test_server.py::test_gcd_server
84.55s call     tests/server/test_gcd_server_auth.py::test_gcd_server_authenticated
```
After
```
85.50s call     tests/server/test_slurm_server.py::test_gcd_server
62.80s call     tests/server/test_server.py::test_gcd_server
51.81s call     tests/server/test_gcd_server_auth.py::test_gcd_server_authenticated
```
> speedup server tests by reducing checks from 30 seconds to 1 second

- siliconcompiler/tools/vpr/vpr.py
This PR closes some corner cases in running VPR on designs that have dangling I/Os.  
If we wish to include test cases for this there are open source designs available that expose the related issue.
> Add options to prevent VPR from crashing on designs with dangling ports

- siliconcompiler/scheduler/__init__.py
This allows tasks to avoid printing package information after it is no longer needed.
> use pipe to communicate package information

- siliconcompiler/core.py
- siliconcompiler/utils/logging.py
Why:
- adding colors to the logging in the terminal makes it easier to find errors and warnings
Before:
New:
Choice of colors can be adjusted.
> apply colors to log levels

- siliconcompiler/schema/schema_cfg.py
- tests/core/data/defaults.json
- tests/core/data/last_minor.json
1. Placing the pin description (length, width, shape) in the datasheet did not make sense, moving it to the pin constraints section to be consistent with the component placement
2. Change the datasheet footprint pointer from a designator to a file reference, less indirection
3. Adding a 3d model pointer in datasheet (critical for 3D)
4. Changing 'name' to 'signal' in pin alias, for clarity, aligns with PCF naming
5. Adding substrate/height to the component placement constarints to accomodate advanced packging constraints
6. Adding width, height, shape, length to pin constraints
Changes after review:
1.) Rename 3D height --> zheight to deconflct with ASIC height/width onstruct
2.) Splitting substrate into substrate + side (splitting strings is ugly)
> Updating schema for advanced packaging

- siliconcompiler/schema/schema_cfg.py
- tests/core/data/defaults.json
- tests/core/data/last_minor.json
- tests/core/test_schematic.py
- Removing pin height constraint....not needed. Confuses things when trying to apply pin dimesions tp chip, package, pcb.
- Fixing schematic terminology issue. 'model' was confusing. Using "partname" instead of cell for consistency
- Refactor to use partname in place of name in datasheet for clarity
> Packaging related schema parameter name changes

- pyproject.toml
- siliconcompiler/flows/_common.py
- siliconcompiler/tools/slang/__init__.py
- siliconcompiler/tools/slang/elaborate.py
- siliconcompiler/tools/slang/lint.py
- siliconcompiler/tools/surelog/__init__.py
- tests/examples/test_gcd.py
- tests/flows/test_failure.py
- tests/flows/test_timeout.py
- tests/tools/test_slang.py
Removes surelog as verilog frontend and replaces it with slang.
Why?
- slang provides better coverage of system verilog and verilog.
> switch to pyslang

- .github/workflows/python_ci.yml
- siliconcompiler/core.py
- siliconcompiler/scheduler/__init__.py
- siliconcompiler/scheduler/docker_runner.py
- siliconcompiler/utils/logging.py
Avoids direct access of `.handlers` parameter in `logger` as well, steps towards cleanup of logger use
> avoid putting color information into text logs

- siliconcompiler/report/dashboard/cli/__init__.py
Some tools, `make` especially, generate lines that use brackets, which confuses the `rich` text rendering. 
`make[2]: Entering directory ... `
> escape brackets in cli dashboard log handler

- siliconcompiler/report/dashboard/cli/__init__.py
Closes #3463 
@Ciprian167 try this out and see if it works for you.
There was a bug that caused the priority printing order to overwrite the errors.
I also switched the final render to show the entire table (not 100% sold on that one, yet).
> cli dashboard: ensure errors get priority in printing and print final table

- tests/tools/data/lec/foo.sdc
- tests/tools/test_opensta.py
The OpenSTA driver did not have a test in the tests directory. Added a basic test which takes the foo design used for the Parmys test and performs timing analysis.
In order to make the test interesting, wrote a simple SDC file for this testcase.
> [Tools][Tests] Added OpenSTA Tool Driver Test

- siliconcompiler/scheduler/schedulernode.py
When a scheduler node is skipped, it currently forwards all of its inputs to the output directory. If the tool was not expecting these files in the output directory, this can raise an issue.
To fix this issue, when a node is being skipped, we now only forward the input files which were required to be output files.
> [Scheduler] Do Not Forward non-Required Outputs

- siliconcompiler/tools/genfasm/genfasm.py
- siliconcompiler/tools/vpr/vpr.py
VTR updates its versions infrequently enough to make it so the minor versions cannot only be used to check the version of VTR.
Updated the version parsing for VTR to include the number of commits since the last release as another release segment.
> [VPR] Updated the VTR Version Parsing

- siliconcompiler/design.py
- Directory suggests path. This name change makes it clear that we are passing around a reference rather than an explicity path.
> Reducing confusion around datadir in design API

- docs/reference_manual/schema_api.rst
- siliconcompiler/__init__.py
- siliconcompiler/packageschema.py
- siliconcompiler/schema/schema_cfg.py
- siliconcompiler/schema_obj.py
- tests/test_packageschema_impl.py
- tests/test_tool.py
Notes:
- ~could move all this down a level to `package` or another phrase to avoid generating too much of a flat schema.~
Some fields removed from the current implementation: 
- `docs/homepage` -> seems covered by the `docs/*`
- `author/username`, `author/location`, `author/publickey` were removed, could added back, but dont seem needed for packaging
- ~`license` and `licensefile` were moved to `license/name`, `license/file`~
> implement package schema

- siliconcompiler/schema/parametervalue.py
- tests/constraints/test_asic_timing.py
- tests/schema/test_parameter.py
- tests/schema/test_parametervalue.py
- tests/test_library.py
- tests/test_schema_information.py
Working with sets resolves in indeterminate ordering this ensures a set is a list of unique values
> ensure sets return a list to preserve ordering
