docs/user_guide/installation.rst
- Optimizing based on friends and family feedback.
=> Fixing installation instructions

docs/index.rst, docs/tutorials/chisel.rst
This PR adds a short tutorial describing the Chisel frontend.
=> Document chisel frontend

.github/workflows/wheels.yml, setup.py
package_data doesn't interpret recursive '**' globs, so we need to do this manually using glob module.
Fix tested with manual build: https://github.com/siliconcompiler/siliconcompiler/actions/runs/1603128202
=> Fix wheel builds

.github/workflows/on_push_tests.yml, docs/index.rst, docs/tutorials/bambu.rst, setup/install-bambu.sh, siliconcompiler/flows/_common.py, siliconcompiler/tools/bambu/bambu.py, tests/flows/data/gcd.c, tests/flows/test_bambu.py
This PR adds Bambu C support and a brief tutorial.
=> Add Bambu frontend support

docs/index.rst, docs/tutorials/bluespec.rst, setup/install-bsc.sh, siliconcompiler/flows/_common.py, siliconcompiler/tools/bluespec/bluespec.py, tests/flows/data/FibOne.bsv, tests/flows/test_bluespec.py
Yet another frontend, Bluespec this time!
=> Add Bluespec support

siliconcompiler/_metadata.py
We need to bump the version to package new wheels with Will's recent fix.
=> Bump version to 0.3.1

siliconcompiler/core.py, siliconcompiler/tools/icepack/icepack.py, siliconcompiler/tools/klayout/klayout.py, siliconcompiler/tools/magic/magic.py, siliconcompiler/tools/netgen/netgen.py, siliconcompiler/tools/nextpnr/nextpnr.py, siliconcompiler/tools/openroad/openroad.py, siliconcompiler/tools/surelog/surelog.py, siliconcompiler/tools/sv2v/sv2v.py, siliconcompiler/tools/verilator/verilator.py, siliconcompiler/tools/yosys/yosys.py, tests/core/test_check_flowgraph_io.py, tests/core/test_check_manifest.py
This PR implements a check to make sure that the file requirements of each step in the flowgraph will be satisfied by previous steps. 
There's a lot of stuff changed here and I think we consider this a nice-to-have, so I'd be happy to postpone merge until we have a chance to discuss.
=> Implement file requirements in check_manifest()

requirements.txt, siliconcompiler/core.py, siliconcompiler/schema.py, siliconcompiler/tools/bambu/bambu.py, tests/flows/test_asicflow.py
This PR implements the `_make_record()` function.
=> Implement automatic record keeping

siliconcompiler/core.py, tests/core/test_env_schema.py
This PR adds functionality for 'env' parameter + a test for it.
=> Implement 'env' schema parameter

siliconcompiler/core.py
I noticed that with the old code in `_find_sc_file()`, we'd get a Python exception if there was ever a path with an environment variable that the user forgot to define, instead of a clean error/warning. This refactor makes this a bit more robust.
- Switch over _find_sc_file() to use _resolve_env_vars() helper
- Refactor _resolve_env_vars() to utilize built-in Python method
- Add explicit error check for missing vars
=> Refactor env var resolution in _find_sc_file

Changes, siliconcompiler/core.py, siliconcompiler/pdks/freepdk45.py, siliconcompiler/schema.py, siliconcompiler/tools/klayout/klayout.py, siliconcompiler/tools/openroad/openroad.py, siliconcompiler/tools/surelog/surelog.py, siliconcompiler/tools/yosys/yosys.py, tests/core/data/gcd.pkg.json
- Enables linking of metric summary to the source that generated that table.
=> Using metric as keyword into tool report parameter

siliconcompiler/schema.py
- Add some categories to library cell list
- A couple typo fixes
=> Schema updates

setup/install-bsc.sh
Setting up Bluespec on new computer, thought this would be a helpful thing to add (is a prereq on a fresh system),
=> Include Haskell build tools in bluespec setup

Changes, siliconcompiler/_metadata.py, siliconcompiler/tools/klayout/klayout_show.py, siliconcompiler/tools/openroad/sc_apr.tcl
Lucky 0.7! This PR bumps the version number + adds release notes.
=> Bump version to 0.7

siliconcompiler/tools/surelog/surelog.py
=> bug fixed (surelog puts paths in quotes)

siliconcompiler/flows/dvflow.py, siliconcompiler/pdks/asap7.py, siliconcompiler/pdks/freepdk45.py, siliconcompiler/pdks/skywater130.py, siliconcompiler/targets/freepdk45_demo.py, siliconcompiler/tools/ghdl/ghdl.py, siliconcompiler/tools/icarus/icarus.py, siliconcompiler/tools/icepack/icepack.py, siliconcompiler/tools/klayout/klayout.py, siliconcompiler/tools/magic/magic.py, siliconcompiler/tools/netgen/netgen.py, siliconcompiler/tools/openfpga/openfpga.py, siliconcompiler/tools/surelog/surelog.py, siliconcompiler/tools/sv2v/sv2v.py, siliconcompiler/tools/verilator/verilator.py, siliconcompiler/tools/vpr/vpr.py, siliconcompiler/tools/xyce/xyce.py, siliconcompiler/tools/yosys/yosys.py
- API was changed a long time ago, seup scripts not updated to allow for standalone exexuction.
- The __main__ code not executed during normal operation.
- Useful for bringup debugging...
=> Fixing issues with running setup modules as standalone programs

siliconcompiler/core.py
- For now, hardcode last step as export. Otherwise, this breaks when running Skywater verification steps.
- Make extra_options use 'None' sentinel instead of list, using list in kwarg can cause troubles due to Python quirk.
- Make _makecmd accept extra_options so we don't have to modify schema. This results in trouble if we want to make multiple calls to show().
- Clean up logging a bit so we don't print "None"
Closes #865.
=> Some show() bugfixes

setup/install-klayout.sh, siliconcompiler/pdks/freepdk45.py, siliconcompiler/pdks/skywater130.py, siliconcompiler/tools/klayout/klayout.py, siliconcompiler/tools/klayout/klayout_show.py, tests/core/test_show.py, tests/tools/test_klayout.py, third_party/pdks/skywater/skywater130/pdk/v0_0_2/setup/klayout/skywater130.lyt
This PR splits off KLayout-related stuff from #900.
=> Update supported KLayout to 0.27.x

setup/install-openroad.sh
Signed-off-by: Massimiliano Giacometti <massimiliano.giacometti@planv.tech>
=> add missing boost libs for openroad

docs/user_guide/examples/flowgraph_doe.py, docs/user_guide/examples/heartbeat_flowgraph.py, siliconcompiler/schema.py
- Small typo in schema.py
- Update examples in Execution Model
=> Some small doc fixes

siliconcompiler/tools/openroad/sc_apr.tcl
One of mine, from a recent commit.
=> Fix typo in sc_apr.tcl

examples/microwatt/build.py, siliconcompiler/tools/ghdl/ghdl.py
Treating this example special since it involved a tool modification. 
Current status of this example is that it runs through GHDL successfully, but Yosys fails on the Verilog output (GHDL seems to be inserting some calls to undefined debug functions, something called `$fatal`?)
There's still some work to be done here, but I think this could be a good starting place for contributions to VHDL support, so I think we should keep it! (see  #917)
=> Clean up microwatt example a bit

siliconcompiler/core.py
Using our usual subprocess scheme seems to break terminal echo for some tools when run interactively through SC. This PR switches things over to using a pseudo-terminal via [pty](https://docs.python.org/3/library/pty.html) to run them instead. This seems to solve the problem.
=> Use pseudoterminal to run tools when bkpt enabled

setup/conda/README.md, setup/conda/environment.yml
Just a couple of small fixes in response to feedback from @proppy on #934.
=> Address conda environment feedback

.github/workflows/bin/install_surelog_macos.sh, .github/workflows/bin/install_surelog_win.bat, .github/workflows/bin/setup_wheel_env_linux.sh, siliconcompiler/core.py, tests/tools/test_surelog.py
This PR should get our daily wheels build back to green. I had to make a few changes to fix things I broke on Windows and macOS with my replay script change, and also some things to accommodate Github/infrastructure-related changes.
Manual run to verify: https://github.com/siliconcompiler/siliconcompiler/actions/runs/2005918393
=> Fix wheels build

siliconcompiler/tools/magic/magic.py, siliconcompiler/tools/magic/sc_drc.tcl, siliconcompiler/tools/netgen/netgen.py, siliconcompiler/tools/netgen/sc_lvs.tcl
`outputs/` was the wrong place for these files to go. Also register them using the 'eda', 'report' schema so they can be opened in graphical summary.
=> Make Netgen/Magic put outputs in reports/

siliconcompiler/core.py
This PR is a refactor I thought was needed for #973, but turned out to be unnecessary. I think it's a nice tweak though, so I'm splitting it out so we can review separately.
At a high level, our old run logic looked something like:
```
if remote:
launch remote run
else:
launch local run
merge manifests from indices of last step:
loop over all, load first w/clobber=True (but preserving local dir), partial load the rest
if no valid manifests, read directory to find last successful step 
(for remote only, local should have finished successfully by this point)
write manifest into root
```
The new logic looks like:
```
if remote:
launch remote run
if root manifest returned from server:
load full root manifest, preserving local dir
else:
perform hack to determine failed step
else:
launch local …
```
=> Refactor logic at end of run()

docs/user_guide/remote_processing.rst, docs/user_guide/tools.rst, siliconcompiler/core.py, siliconcompiler/schema.py, tests/core/data/defaults.json, tests/flows/test_flowstatus.py
Otherwise we can't disable it via CLI.
=> 'vercheck' -> 'novercheck'

.github/workflows/bin/setup_wheel_env_linux.sh
Was getting an error while installing wget in the Surelog Linux build script. Fix from here: https://stackoverflow.com/questions/26734777/yum-error-cannot-retrieve-metalink-for-repository-epel-please-verify-its-path.
=> Fix failing Linux Wheels build

Changes, siliconcompiler/_metadata.py
Will tag release and run build/test/publish process once this is merged!
=> Prepare 0.9.1 release

siliconcompiler/core.py, siliconcompiler/tools/bambu/bambu.py, siliconcompiler/tools/bluespec/bluespec.py, siliconcompiler/tools/chisel/chisel.py, siliconcompiler/tools/echo/echo.py, siliconcompiler/tools/ghdl/ghdl.py, siliconcompiler/tools/icarus/icarus.py, siliconcompiler/tools/icepack/icepack.py, siliconcompiler/tools/klayout/klayout.py, siliconcompiler/tools/magic/magic.py, siliconcompiler/tools/netgen/netgen.py, siliconcompiler/tools/nextpnr/nextpnr.py, siliconcompiler/tools/openfpgaloader/openfpgaloader.py, siliconcompiler/tools/openroad/openroad.py, siliconcompiler/tools/surelog/surelog.py, siliconcompiler/tools/sv2v/sv2v.py, siliconcompiler/tools/template/template.py, siliconcompiler/tools/verilator/verilator.py, siliconcompiler/tools/vivado/vivado.py, siliconcompiler/tools/vpr/vpr.py, siliconcompiler/tools/xyce/xyce.py, siliconcompiler/tools/yosys/yosys.py
- Delete unused imports/variables
- No clobber=False on exe/vswitch, clobber=False on threads/script/refdir/version
- post_process():
- Delete if empty
- Remove return 0
- Remove error/warning processing (use regex)
=> Clean up tool drivers

docs/user_guide/installation.rst, siliconcompiler/flows/signoffflow.py
This PR fixes a couple recent issues pointing out bugs in our docs.
Closes #1067, #1066
=> Fix some problems with docs

examples/parity/arch.xml, examples/parity/parity.v, examples/spree/arch.xml, siliconcompiler/flows/fpgaflow.py, siliconcompiler/tools/vpr/vpr.py, siliconcompiler/tools/yosys/yosys.py, tests/examples/test_fasm_parity.py, tests/examples/test_vpr_spree.py
This PR adds support for genfasm step in the VPR flow.
=> Add genfasm submodule

siliconcompiler/core.py
This PR cleans up some things that gave me trouble when I was testing out PR #1089. I also did a pass on the docstring.
Code changes:
- If logfile is not supplied, construct full path based on jobname, step, and index. This makes this function more usable in a user's scripts, right now it is implicitly designed to run inside the task directory.
- Make default behavior for 'index' consistent with 'step' (use ['arg', 'index'] instead of first item in flowgraph)
- raise exception if no step or index provided (otherwise this bubbles into a fatal error, since these are needed to find regexes)
- Close the report files when done. Python garbage collector probably handles this, but it's good practice
- Fix inconsistent indentation
Docs changes:
- "logged" instead of "displayed to STDOUT" in …
=> Some cleanup of check_logfile()

Changes, tests/core/test_jobincr.py
- Fix test_jobincr for Windows
- Fix typo in Changelog
=> Release fixups

examples/heartbeat/parallel.py, siliconcompiler/core.py, siliconcompiler/flows/asicflow.py, siliconcompiler/templates/report/sc_report.j2, siliconcompiler/tools/yosys/yosys.py
This PR removes the code that resets all metrics to zero in `_runtask()`. This has been a TODO for a while, although it has some interesting implications that will probably require discussion. 
I think the main reason we should get rid of this code is that it feels a little "unsafe", and can mask a lot of issues. I made the change now because I got bit by this: the goal for many metrics is to be zero, but if we reset metrics to zero to begin with that could make us inadvertently think that we've hit zero even if the metric isn't supported by a tool, or worse, if there's a bug in a tool's `post_process()` driver that causes the metric to not get set.
These are the main choices I made here:
- Unset metrics have `None` values
- In `summary()`, all unset metrics get displayed as `---`
- If a …
=> Delete code that resets metrics to zero

Changes, siliconcompiler/_metadata.py
Bump version number and update Changelog.
=> 0.9.4 release

siliconcompiler/core.py
=> Better error message for file path resolution

siliconcompiler/tools/verilator/verilator.py
- Implement ['option', 'warningoff']
- Use ['option', 'trace'] instead of passthrough for enabling tracing
- Supply passthroughs for CFLAGS and LDFLAGS
- Error out if Make post-process step fails
=> Enhancements to Verilator driver

Changes, siliconcompiler/_metadata.py
Bump version/release notes for 0.9.6.
=> Release 0.9.6

docs/user_guide/introduction.rst
Signed-off-by: Michael Gielda <mgielda@antmicro.com>
=> Minor numbered list fix in introduction.rst

siliconcompiler/tools/yosys/markDontUse.py, siliconcompiler/tools/yosys/syn_asic.tcl, siliconcompiler/tools/yosys/syn_fpga.tcl, siliconcompiler/tools/yosys/yosys.py, tests/examples/test_gcd.py
Fixes:
- FPGA flow with missing report
- Better handling of `abc_clock_period` (when missing)
=> yosys: fix for CI

.gitignore
Fixes:
- gitignore of deps to match the directory in setup/deps
=> fix deps ignore path

examples/blinky/blinky_fusesoc.v, examples/blinky/run_vivado.sh, siliconcompiler/core.py, siliconcompiler/tools/vivado/compile.tcl, siliconcompiler/tools/vivado/vivado.py
This PR fixes up and enhances SC's Vivado support. Changes:
- Modernize/fix up the driver
- Add metrics parsing
- Updates for fileset change
- Fix blinky example to make sure it at least builds (verified locally, since we don't have CI for this)
- Small core change to skip version checking if no target versions are specified (seems like a reasonable default to me?)
=> Vivado improvements

siliconcompiler/core.py, siliconcompiler/flows/asicflow.py, siliconcompiler/flows/asictopflow.py, siliconcompiler/flows/fpgaflow.py, siliconcompiler/schema/schema_cfg.py, siliconcompiler/tools/vivado/compile.tcl, siliconcompiler/tools/yosys/lec.py, siliconcompiler/tools/yosys/syn.py, siliconcompiler/tools/yosys/syn_asic.py, siliconcompiler/tools/yosys/syn_fpga.py, siliconcompiler/tools/yosys/yosys.py, tests/core/data/defaults.json, tests/examples/test_gcd.py
Like we discussed today. I left the mode-dependent setup logic in `lec` for the sake of our tests - we can decide how to partition that logic when we start to use it more.
=> Split yosys synthesis task into syn_fpga and syn_asic

siliconcompiler/core.py, siliconcompiler/flows/asicflow.py, siliconcompiler/flows/asictopflow.py, siliconcompiler/flows/dvflow.py, siliconcompiler/flows/fpgaflow.py, siliconcompiler/flows/showflow.py, siliconcompiler/flows/signoffflow.py, siliconcompiler/targets/asap7_demo.py, siliconcompiler/targets/fpgaflow_demo.py, siliconcompiler/targets/freepdk45_demo.py, siliconcompiler/targets/skywater130_demo.py, siliconcompiler/targets/utils.py, siliconcompiler/utils.py, tests/core/test_target.py, tests/examples/test_fasm_parity.py, tests/examples/test_vpr_spree.py
Changes:
- Several flows were acting as quasi targets, this fixes the flows to just setup the flowgraph and moves settings into the appropriate targets.
Adds:
- a helper function to set the showtools in the targets so it's consistent
=> flows cleanup

examples/oh_experiments/check_area.py, tests/examples/test_picorv32_ram.py
Fixes failing tests on daily ci. (one is disabled until routing can be resolved).
=> fix daily ci

siliconcompiler/tools/openroad/sc_floorplan.tcl
Changes:
- Adds pin constraint support (initial), still needs to be refined
- Support for partname in component placement
=> openroad constraint pins/partname

siliconcompiler/core.py, siliconcompiler/schema/schema_cfg.py, tests/core/data/defaults.json
This PR switches over the record group to use the new step/index scheme. Also took the chance to fix a few set(..., None)s to unset()s where I noticed them.
=> Make record schema use step/index

siliconcompiler/libs/sky130hd.py, siliconcompiler/libs/sky130io.py, siliconcompiler/sphinx_ext/dynamicgen.py, siliconcompiler/tools/openroad/openroad.py
Changes:
- Repairs the target references to libraries that broke after switching to `.Library`
- Fix openroad links in docs
- Add reference to the PDK associated with the skywater130 pdk
=> Minor docs fixes

.github/workflows/daily_tests.yml, siliconcompiler/schema/schema_cfg.py, siliconcompiler/schema/schema_obj.py, siliconcompiler/schema/utils.py, siliconcompiler/sphinx_ext/dynamicgen.py, siliconcompiler/tools/klayout/klayout.py, siliconcompiler/tools/klayout/klayout_export.py, siliconcompiler/tools/klayout/klayout_show.py, siliconcompiler/utils.py
- Need to refactor Schema a bit to avoid dependencies elsewhere in SC project
- Need to pass path via CLI options so that it can be resolved at runtime (otherwise remote runs won't work)
testing with manual daily CI run: https://github.com/siliconcompiler/siliconcompiler/actions/runs/4086206108
=> klayout: import Schema directly to avoid dependencies

siliconcompiler/sphinx_ext/dynamicgen.py, siliconcompiler/tools/yosys/syn_asic.py
Adds:
- Variable and File sections to the tools (currently only yosys has this done).
=> docs: add variable and file sections to allow for documenting free variables and files

docs/user_guide/installation.rst
=> docs: document Bison/Flex requirement for MacOS

examples/gcd/run_asap7.sh, siliconcompiler/libs/asap7sc7p5t.py, siliconcompiler/pdks/asap7.py, siliconcompiler/targets/asap7_demo.py, siliconcompiler/tools/openroad/sc_floorplan.tcl
Closes #1100
Changes:
- timing libraries needed to be fixed
- enables all three timing corners on asap7 target
=> Sc 13 asap7 corners

docs/tutorials/bambu.rst, docs/tutorials/bluespec.rst, docs/tutorials/chisel.rst, docs/tutorials/contribution.rst, docs/tutorials/migen.rst, docs/tutorials/parallel.rst, docs/tutorials/slurmsetup.rst
Does not modify zerosoc and only fixes keypaths in slurm
=> update tutorials folder

docs/_ext/schemagen.py, siliconcompiler/sphinx_ext/dynamicgen.py, siliconcompiler/sphinx_ext/utils.py
Changes:
- make keypaths in docs a generated link instead of hardcoded to the website
=> Fix schema key links

examples/gcd/gcd_skywater.py, siliconcompiler/core.py, siliconcompiler/schema/schema_obj.py, siliconcompiler/tools/openroad/export.py, siliconcompiler/tools/openroad/sc_apr.tcl, siliconcompiler/tools/openroad/sc_constraints.sdc, siliconcompiler/tools/openroad/sc_floorplan.tcl, siliconcompiler/tools/openroad/sc_metrics.tcl
Changes:
- adds job name to checklist message
- adds io constraints to auto generated SDC file
- fixes various script issues in floorplanning
=> fixes to OpenROAD scripts found when enabling ZeroSOC

setup/_tools.json, siliconcompiler/libs/sky130io.py, siliconcompiler/tools/openroad/floorplan.py, siliconcompiler/tools/openroad/openroad.py, siliconcompiler/tools/openroad/sc_floorplan.tcl, tests/examples/test_gcd.py, third_party/pdks/skywater/skywater130/libs/sky130io/v0_0_2/io/sky130_ef_io.lef
Changes:
- Adds padring script access to the floorplanning step in OR
- Bumps the required version of OpenROAD (@WRansohoff can we work on getting the CI running the new version)
=> Implement OpenROAD padring

.github/workflows/bin/install_surelog_macos.sh, .github/workflows/bin/setup_wheel_env_linux.sh
Closes #1338 
We should trigger the surelog build before merging, probably next week
=> ensure workflow scripts point at the base siliconcompiler directory

docs/user_guide/flows.rst, docs/user_guide/pdks.rst, docs/user_guide/targets.rst, docs/user_guide/tools.rst
Currently only contains the `Flows` page.
I'll mark this as ready for review when the `PDKs`, `Checklists`, `Targets`, and possibly `Tools` pages are also ready.
=> Initial rewrite of user guide module docs.

docs/_ext/requirements.py, docs/_ext/schemagen.py, docs/user_guide/data_model.rst, siliconcompiler/pdks/freepdk45.py, siliconcompiler/pdks/skywater130.py, siliconcompiler/targets/freepdk45_demo.py
=> docs: cleanup formatting and other minor fixes

siliconcompiler/tools/openroad/sc_route.tcl
Issue reported to @maliberty
Interim solution: disable checks and reenable when fixed.
=> disable check antennas until segfault is resolved by OR-team

siliconcompiler/tools/openroad/openroad.py, siliconcompiler/tools/openroad/sc_apr.tcl, siliconcompiler/tools/openroad/sc_constraints.sdc, siliconcompiler/tools/openroad/sc_floorplan.tcl, siliconcompiler/tools/openroad/sc_place.tcl
Changes:
- from vars to files to support the remote flow correctly
=> change type of vars which are actually files in OR

docs/tutorials/picorv32_ram.rst
Walked through instructions again and found some minor things.
=> Minor reword update to picorv32 tutorial

siliconcompiler/core.py, siliconcompiler/templates/report/sc_report.j2, siliconcompiler/tools/magic/drc.py, siliconcompiler/tools/netgen/lvs.py, siliconcompiler/tools/openroad/openroad.py, siliconcompiler/tools/vivado/vivado.py, siliconcompiler/tools/yosys/lec.py, siliconcompiler/tools/yosys/yosys.py, siliconcompiler/units.py, tests/core/test_record_metric.py, tests/core/test_units.py, tests/tools/test_openroad.py
Changes:
- adds `_record_metric` helper function to assist tools in recording the metrics with the correct units + unit tests to check functionality
- adds `_clear_metrics` helper function to unset metrics and reports
- updates all tool drivers that use new helpers and core
- adds units modules to help with converting between units and formatting + unit tests to check functionality
Before summary():
```
import0        syn0       floorplan0       physyn0         place0          cts0          route0          dfm0        export0        export1
errors               0            0              0              0              0              0              0              0             0              0
warnings             10           75             16             0              0              2 …
```
=> Ensure units are used in metrics and used when printing tables and reports

siliconcompiler/tools/klayout/klayout_export.py
Fixes: https://github.com/siliconcompiler/zerosoc/issues/22
=> Fix klayout export to handle empty cells and DBUs mismatch

docs/index.rst, docs/tutorials/bambu.rst, docs/tutorials/bluespec.rst, docs/tutorials/chisel.rst, docs/tutorials/hw_frontends.rst, docs/tutorials/migen.rst, docs/user_guide/introduction.rst, docs/user_guide/quickstart.rst, siliconcompiler/flows/asicflow.py
I think there might be several phases to documentation updates. For this first phase, I'm hoping to just settle on a reordering of the pages for overall readability and to make clear what user vs developer is and provide information on how they should approach the documentation, without being too focused on content of specific pages. 
<html>
<body>
Change | Reason
-- | --
(1) Move intro into index.html | Helps make the default entrance page more meaningful
(2) Shorten User Guide | - Pulling out all pages which require developer mindset<br>- Want to keep clean information for users (who don’t plan to contribute)
(3) Add new FLOW BASICS section for flow | Group together "data model," "programming model" and "execution model" since these three main sections are the next step to understanding …
=> Restructure Documentation for Readability

siliconcompiler/core.py
=> add recording of child process memory usage

.gitmodules
Changes:
- no functional changes, these are repositories with no references in SC.
=> remove all submodules with no references in the SC repo

setup/_tools.json
Updating openroad to 47991be874e4db0197c787e072ad23100b5b0911
=> [SC-BOT] Update openroad

siliconcompiler/core.py, tests/core/test_hash_files.py
Implement hash algorithm selection based on the schema
=> implement hashalgorithm selection from keypath instead of via function

siliconcompiler/core.py, siliconcompiler/schema/schema_cfg.py, siliconcompiler/schema/schema_obj.py, tests/core/data/defaults.json
Changes:
- Adds `copy` field to directories
- Update `_collect` to look for directories to copy and check imported directories for files before copying
This is a step towards being able to generate runnable testcases
=> Allow dir copy and implement in core

siliconcompiler/tools/yosys/syn_asic.py, siliconcompiler/tools/yosys/syn_asic.tcl
Fixes:
- vars that are actually files are now marked as files, which should make testcase generation more reliable
=> change to use file instead of var for synthesis files

siliconcompiler/tools/openroad/openroad.py
No functional changes, but is needed to support openroad in other implementations outside of APR flow.
=> split out basic tool setup

siliconcompiler/core.py
Changes:
- make load_target work like .use() by allowing a python module to be passed in as well as a string
=> allow load_target to take in a module or a string

.github/workflows/tool_updater.yml, setup/_tools.json, setup/_tools.py, setup/install-chisel.sh, siliconcompiler/tools/chisel/chisel.py
Add tool updating to klayout and chisel
fix chisel version parsing
=> Add tool updating to klayout and chisel

setup/_tools.json
Reverts siliconcompiler/siliconcompiler#1516
Segfault in placement
=> Revert "[SC-BOT] Update openroad"

tests/flows/test_lintflow.py, tests/tools/test_verilator.py
Looks like I broke CI on main...
=> Add missing ['option', 'mode'] settings

docs/user_guide/installation.rst
This must have gotten missed in the big docs release.
=> Minor update to remove ARM64 incompatibility info in docs

siliconcompiler/core.py, siliconcompiler/schema/schema_cfg.py, tests/core/data/defaults.json, tests/core/test_hash_files.py
For 'option,credentials, a list of files doesn't make sense and this makes it a single item instead
=> make option,credentials a single file instead a list

siliconcompiler/schema/schema_cfg.py, tests/core/data/defaults.json, tests/core/test_valid.py
This adds a 'pin' parameter in the constraints,timing,..,voltage to support multiple power/voltage domains
=> Add support for multiple voltages in constraints

siliconcompiler/tools/klayout/klayout_show.py
This restores the screenshots in my testing
=> correct loading of layout in klayout to use the technology

setup/docker/builder.py
Without this, changed to klayout versions do not trigger a rebuild of the docker images
=> ensure tool versions are also captured as part of sc_tools hash

.github/workflows/python_ci.yml, .github/workflows/tools_ci.yml, README.md, requirements.txt
At present our coverage is not great, but this will allow us to track and improve over time
=> add coverage tracking to CI

.github/workflows/tools_ci.yml, siliconcompiler/apps/sc_ping.py, siliconcompiler/client.py
There are no functional changes in this PR, just moving the code related to talking with the server to client.py to be consistent.
=> moving request code from sc-ping to client.py

siliconcompiler/client.py, tests/server/test_gcd_server_auth.py
This PR unifies the communications with the server into a single function `__post` to allow for simpler error handling and updates to how we talk between the client and sever.
There appears to be a lot of different ways the server can respond, so we need to fix that in the API to make this even simpler and easier to maintain.
=> refactor client.py

docs/development_guide/records.rst, siliconcompiler/core.py, siliconcompiler/schema/schema_cfg.py, tests/core/data/defaults.json
Changes:
- enables the records for time, tool, and scversion.
- Continues to use `'option', 'track'` to record the user and machine specific information
=> record records as we go through the flow

siliconcompiler/apps/sc_show.py, siliconcompiler/core.py, siliconcompiler/flows/showflow.py, tests/apps/test_sc_show.py
Adds:
- arg_step, arg_index, and jobname to sc-show to allow for granular opening of layouts
- add screenshot option
=> improve sc-show to take in arg_step and index

siliconcompiler/tools/openroad/export.py, siliconcompiler/tools/openroad/openroad.py, siliconcompiler/tools/openroad/sc_apr.tcl, siliconcompiler/tools/openroad/sc_cts.tcl, siliconcompiler/tools/openroad/sc_route.tcl
This fixes a few minor issues
Reorganizes the parameter setting to allow for getting them from the PDK and library settings
Adds some missing flags for resizer, (depends on https://github.com/siliconcompiler/zerosoc/pull/27)
=> General openroad tool driver cleanup

pyproject.toml, tests/apps/test_sc_ping.py
https://github.com/siliconcompiler/siliconcompiler/actions/runs/5267812067
=> extend timeout to account for slower linux arm run times

siliconcompiler/__init__.py, siliconcompiler/_common.py, siliconcompiler/core.py, siliconcompiler/report/__init__.py, siliconcompiler/report/html_report.py, siliconcompiler/report/summary_image.py, siliconcompiler/report/summary_table.py, siliconcompiler/report/utils.py
No functional changes.
Changes:
- moves `TaskStatus` and `SiliconCompilerError` into a _common.py file to avoid cyclical imports
- moves all code related to generating and displaying reports and summaries to reports/
=> code refactor for TaskStatus and SiliconCompilerError and reporting

siliconcompiler/report/streamlit_viewer.py
I forgot to take out the SC logo that was next to the title. This needs to be tested more.
=> untested SC logo, taken out for further testing

requirements.txt, tests/core/test_reports.py
Verified by https://github.com/siliconcompiler/siliconcompiler/actions/runs/5492682699
=> Fix Windows 3.6 wheels build

examples/heartbeat/parallel.py, requirements.txt, siliconcompiler/report/streamlit_report.py, tests/core/test_dasboard.py, tests/examples/test_heartbeat.py
Also disable currently breaking test, which needs to be fixed later
=> remove streamlit from Python 3.6

.github/workflows/python_ci.yml, .github/workflows/wheels.yml
Enabling the cache should save about 2min of time during test runs.
=> Enable pip caching

siliconcompiler/report/report.py, siliconcompiler/report/streamlit_viewer.py, siliconcompiler/report/summary_table.py, siliconcompiler/report/utils.py
I refactored the code based on Noah's suggestions in the last PR which include:
- creating _get_flowgraph_paths in utils.py to fit in with the summary table and get_flowgraph_paths in reports.py
- making show_dataframe_and_parameter_selection more readable
- Also let's compressed files readable when selected in the node information section
=> Code refactoring

siliconcompiler/libs/asap7sc7p5t.py, siliconcompiler/libs/nangate45.py, siliconcompiler/libs/sky130hd.py, siliconcompiler/pdks/freepdk45.py, siliconcompiler/pdks/skywater130.py, siliconcompiler/tools/openroad/openroad.py, siliconcompiler/tools/openroad/scripts/sc_apr.tcl, siliconcompiler/tools/openroad/scripts/sc_cts.tcl, siliconcompiler/tools/openroad/scripts/sc_export.tcl, siliconcompiler/tools/openroad/scripts/sc_floorplan.tcl, siliconcompiler/tools/openroad/scripts/sc_place.tcl, siliconcompiler/tools/openroad/scripts/sc_procs.tcl, siliconcompiler/tools/yosys/syn_strategies.tcl, tests/examples/test_gcd.py
Changes:
- fixes incorrect yosys scripts from ORFS
- adds steps to mirror ORFS for global placement and pin placement
Fixes:
- openroad driver using clock estimation layer for signal estimations
=> cleanup openroad and yosys setup

siliconcompiler/tools/openroad/openroad.py, siliconcompiler/tools/openroad/scripts/sc_apr.tcl, siliconcompiler/tools/openroad/scripts/sc_procs.tcl
relates to https://github.com/siliconcompiler/zerosoc/pull/29
=> add filtering to OR for PSM checking

siliconcompiler/tools/openroad/openroad.py, siliconcompiler/tools/openroad/scripts/sc_apr.tcl, siliconcompiler/tools/openroad/scripts/sc_export.tcl
Adds:
- final IR drop check to export
=> bump minimum version of OR to better support IR drop analysis

Changes, siliconcompiler/_metadata.py
Might be nice to merge #1790 first as well.
=> Release 0.13.1

docs/conf.py, docs/development_guide/remote_processing.rst
https://siliconcompiler--1844.org.readthedocs.build/en/1844/reference_manual/index.html
Schema: https://siliconcompiler--1844.org.readthedocs.build/en/1844/reference_manual/schema.html
=> increase TOC depth in docs to make them better to navigate

siliconcompiler/tools/surelog/surelog.py
Adds an option to Surelog that fixes the crash that Wenting reported.
=> Add disable write cache option to Surelog

siliconcompiler/remote/client.py
Just came accross this typo while debugging another issue
=> Fix remote client typo

docs/user_guide/quickstart.rst
Update quickstart guide to work properly with multiprocessing spawn
=> fix quickstart guide

siliconcompiler/schema/utils.py, siliconcompiler/tools/openroad/scripts/sc_floorplan.tcl, siliconcompiler/tools/yosys/syn_asic.py, siliconcompiler/tools/yosys/syn_asic.tcl
Adds:
- blackbox read support for yosys
Changes:
- adds type checking to tcl escape code, need to revisit to correct escaping
- corrects the instance placement in OpenROAD to avoid faulty `place_cell` command.
=> Add blackbox support and fix place in OpenROAD

siliconcompiler/core.py, tests/core/test_check_flowgraph.py
Adds check to see if steplist contains steps that are not in the flowgraph as this causes an error at the end of the run
=> add check for incorrect steplist to _check_flowgraph

siliconcompiler/tools/chisel/convert.py, siliconcompiler/utils.py
Adds:
- support to take in a build.sbt and provide arguments to the runMain command
=> improve chisel support

siliconcompiler/schema/schema_cfg.py, tests/core/data/defaults.json, tests/core/data/last_major.json
Unless I'm missing something major there is no place where this option is actually used in the run logic.
Part of SC-613
=> Remove skipstep option

siliconcompiler/remote/client.py, tests/apps/test_sc_remote.py
https://github.com/siliconcompiler/siliconcompiler/actions/runs/6084794388/job/16507538745
=> fix CI to patch home() to ensure OS testing works

siliconcompiler/apps/sc_remote.py, siliconcompiler/core.py, siliconcompiler/remote/client.py, siliconcompiler/remote/server.py, siliconcompiler/report/streamlit_viewer.py, siliconcompiler/report/summary_image.py, siliconcompiler/report/utils.py, tests/core/test_graph.py
**Why?**
When working more with the flowgraph it was a bit unclear at times what is a node vs step in existing code.
Additonally this should make it more clear at which points the steplist and indexlist are considered in the flowgraph.
Last minor benefit is that it saves one level of indentation.
**What?**
Introduce a function that gets all nodes `(step, index)` in the flowgraph and use it in existing code.
**Testing:**
[Remote server run](https://github.com/zeroasiccorp/scserver/actions/runs/6096289187/job/16542015595)
=> Get flowgraph nodes

.flake8, siliconcompiler/core.py, siliconcompiler/sphinx_ext/dynamicgen.py
I noticed the flow was not building correctly in the docs. 
This fixes the flowgraph writing to correctly handle mismatching names and reenabled lost docs for steps
=> fix flow docs build

siliconcompiler/core.py
After some other code refactoring fixing [this](https://github.com/siliconcompiler/siliconcompiler/pull/1806#discussion_r1279656792) suggestion from Noah become fairly easy.
No functional changes just readability/reliability.
=> Use node tuple instead of string

siliconcompiler/core.py
Adds basic feedback to users of which node is getting configured.
=> add info message for node getting configured

siliconcompiler/core.py
Removes the extra space at the end of the step and index columns in logger and right aligns index.
Before:
```
| INFO    | job0  | --         | -  | Setting up node export1 with openroad/export
| INFO    | job0  | --         | -  | Checking manifest before running.
| INFO    | job0  | import     | 0  | Tool 'surelog' found with version '1.73' in directory '/usr/local/bin'
| INFO    | job0  | import     | 0  | Running in /home/pgadfort/siliconcompiler/examples/gcd/build/gcd/job0/import/0
```
After:
```
| INFO    | job0 | --        | - | Setting up node export1 with openroad/export
| INFO    | job0 | --        | - | Checking manifest before running.
| INFO    | job0 | import    | 0 | Tool 'surelog' found with version '1.73' in directory '/usr/local/bin'
| INFO    | job0 | import    | 0 | …
```
=> adjust logger to right align index and remove extra space

.github/workflows/bin/install_surelog_linux.sh, .github/workflows/bin/install_surelog_win.bat
Build surelog with static linking for zlib dependency: https://github.com/siliconcompiler/siliconcompiler/suites/16508799539/artifacts/943209333
Closes: #1986
=> build surelog with static zlib

setup/_tools.json, siliconcompiler/tools/openroad/openroad.py, siliconcompiler/tools/openroad/scripts/sc_apr.tcl, siliconcompiler/tools/openroad/scripts/sc_procs.tcl, siliconcompiler/tools/openroad/scripts/sc_write_images.tcl
Adds controls to heatmaps to set number of bins
Only emit heatmaps with data in them.
Always show clock tree.
=> update openroad and allow for better control of heatmaps

.github/workflows/wheels.yml, docs/user_guide/installation.rst
Wheels: https://github.com/siliconcompiler/siliconcompiler/actions/runs/6303016707
=> build two artifacts for wheels build to keep siliconcompiler artifact small

siliconcompiler/remote/client.py
Separating this from #2005 while we decide how/if to handle path normalization.
=> Update default ToS string

siliconcompiler/core.py, siliconcompiler/schema/schema_obj.py, tests/core/test_create_cmdline.py
This moved create_cmdline into the schema object class to allow for a generalized use of the schemas create_cmdline for the ServerSchema (coming later)
=> move create_cmdline to schema to allow schema to handle setting of cmdline arguments

Changes, siliconcompiler/_metadata.py
=> version 0.16.1

.github/workflows/wheels.yml
https://github.com/siliconcompiler/siliconcompiler/actions/runs/6519197312
=> only run release artifact on release flows

siliconcompiler/tools/openroad/scripts/sc_apr.tcl
Use the proper schema variable (detail_routing_unidirectional_layer) vs the one currently being used (drt_unidirectional_layer)
=> Fix schema variable in sc_apr.tcl

siliconcompiler/libs/sky130io.py
Fallout from adding -noblackboxes to the yosys synth script
=> add sky130io blackboxes

.github/workflows/tools_ci.yml, requirements.txt, setup/docker/builder.py, setup/docker/requirements.txt, setup/docker/sc_runner.docker
=> create docker runner labeled latest

siliconcompiler/apps/sc_remote.py, siliconcompiler/core.py, siliconcompiler/tools/vpr/vpr.py, siliconcompiler/tools/yosys/syn_asic.py
This is needed if the clock period is specified with a variable instead of a number
=> improve sdc parsing for yosys clock period extraction

siliconcompiler/package.py, siliconcompiler/utils.py
Update submodules explicitely
Also added the python package found message.
=> Missing submodule checkout

siliconcompiler/package.py, siliconcompiler/schema/schema_cfg.py, siliconcompiler/utils.py, tests/core/data/defaults.json, tests/core/data/last_minor.json, tests/package/test_package.py
adds control of cache location, this is needed for the server to operate properly.
=> add option/cache to schema

setup/docker/builder.py, setup/install-surelog.sh, setup/install-vpr.sh, setup/install-xyce.sh
Uses venv for the tools with python build dependencies.
=> fix tools build to account for changes in install-{}.sh files

siliconcompiler/tools/klayout/klayout_operations.py, siliconcompiler/tools/klayout/operations.py, tests/tools/test_klayout.py
=> add klayout rename_cell operation

siliconcompiler/tools/openroad/openroad.py, siliconcompiler/tools/openroad/scripts/sc_apr.tcl, siliconcompiler/tools/openroad/scripts/sc_cts.tcl
=> add obstruction aware option to cts in OpenROAD

siliconcompiler/core.py, siliconcompiler/remote/client.py
Avoids requiring specific python packages to be available on the remote.
=> Fix python package remote

requirements.txt, siliconcompiler/tools/openroad/scripts/sc_floorplan.tcl, siliconcompiler/tools/openroad/scripts/sc_screenshot.tcl, siliconcompiler/tools/yosys/sc_syn.tcl, siliconcompiler/tools/yosys/syn_asic.tcl
I just released a new version of `tclint` that parses expressions. It caught a few small things, one bug and a couple other things that are more of a style issue. 
Expression style checking is coming next, but wanted to open this now to get the bug fixed!
=> Update tclint and fix expression issues

docs/reference_manual/core_api.rst, siliconcompiler/core.py, siliconcompiler/schema/schema_cfg.py, siliconcompiler/tools/_common.py, siliconcompiler/tools/bambu/bambu.py, siliconcompiler/tools/bambu/convert.py, siliconcompiler/tools/bluespec/bluespec.py, siliconcompiler/tools/bluespec/convert.py, siliconcompiler/tools/chisel/chisel.py, siliconcompiler/tools/chisel/convert.py, siliconcompiler/tools/ghdl/convert.py, siliconcompiler/tools/ghdl/ghdl.py, siliconcompiler/tools/icarus/compile.py, siliconcompiler/tools/icarus/icarus.py, siliconcompiler/tools/surelog/parse.py, siliconcompiler/tools/surelog/surelog.py, siliconcompiler/tools/verilator/compile.py, siliconcompiler/tools/verilator/verilator.py, tests/core/data/defaults.json, tests/core/test_check_manifest.py
Adds:
* 'option', 'library' key to control which libraries should be used
* Helper functions for tool drivers to use to make supporting a uniform set of parameters easier
=> add support for soft libraries in frontend driver

setup/_tools.json
Reverts siliconcompiler/siliconcompiler#2252
Appears to break in Windows, needs to be debugged
=> Revert "[SC-BOT] Update klayout"

siliconcompiler/sphinx_ext/dynamicgen.py
=> allow docs to build external files

docs/conf.py
=> add source link to docs

.github/workflows/wheels.yml
https://github.com/siliconcompiler/siliconcompiler/actions/runs/8836576175
=> pin wheel mac build to macos-13

siliconcompiler/core.py, siliconcompiler/scheduler/__init__.py, siliconcompiler/tools/_common/__init__.py, siliconcompiler/tools/execute/exec_input.py, siliconcompiler/utils.py, tests/core/test_check_flowgraph_io.py, tests/tools/test_common.py
Necessary for GDS processing and LEC.
=> allow same file coming from multiple nodes into the same node

examples/gcd/gcd_screenshot.py, examples/gcd/gcd_skywater.py, examples/heartbeat_padring/build.py, siliconcompiler/apps/sc_show.py, siliconcompiler/core.py, siliconcompiler/flows/asicflow.py, tests/apps/test_sc_show.py, tests/core/test_flowgraph.py, tests/core/test_graph.py, tests/examples/test_fibone.py, tests/examples/test_gcd.py, tests/examples/test_gcd_chisel.py, tests/examples/test_gcd_hls.py, tests/examples/test_heartbeat.py, tests/examples/test_heartbeat_padring.py, tests/examples/test_picorv32.py, tests/examples/test_picorv32_ram.py, tests/flows/test_from_to.py, tests/flows/test_gcd_floorplan.py, tests/flows/test_resume.py, tests/flows/test_slurm_local.py, tests/server/test_gcd_server_auth.py, tests/server/test_server.py, tests/server/test_slurm_server.py, tests/targets/test_asic_demo.py
using index's at the end causes resume to fail to rerun if one fails.
=> split export in asicflow to ensure correct flowgraph handling

requirements.txt
This should fix the regression in #2502
=> Bump tclint to 0.3.1

tests/core/test_check_display.py
Fixes bad behavior identified in: https://github.com/siliconcompiler/siliconcompiler/pull/1874
=> remove windows skip on display

.dockerignore, .github/workflows/daily_ci.yml, .github/workflows/docker_image.yml, .github/workflows/python_ci.yml, .github/workflows/tools_ci.yml, docs/user_guide/docker.rst, docs/user_guide/index.rst, docs/user_guide/quickstart.rst, pyproject.toml, requirements.txt, setup/docker/sc_local_runner.docker, siliconcompiler/apps/sc_run.py, siliconcompiler/scheduler/__init__.py, siliconcompiler/scheduler/docker_runner.py, siliconcompiler/scheduler/run_node.py, siliconcompiler/schema/schema_cfg.py, siliconcompiler/tools/klayout/klayout.py, siliconcompiler/tools/surelog/surelog.py, tests/core/data/defaults.json, tests/tools/test_docker.py
Adds a docker scheduler which can be used to pull the runner image and run there
This avoids issues with keeping tools up to date
This cannot handle show tasks
=> add docker based running

siliconcompiler/core.py, siliconcompiler/flowgraph.py, siliconcompiler/flows/_common.py, siliconcompiler/flows/asicflow.py, siliconcompiler/flows/asictopflow.py, siliconcompiler/flows/dvflow.py, siliconcompiler/flows/fpgaflow.py, siliconcompiler/flows/generate_openroad_rcx.py, siliconcompiler/flows/lintflow.py, siliconcompiler/flows/screenshotflow.py, siliconcompiler/flows/showflow.py, siliconcompiler/flows/signoffflow.py, siliconcompiler/flows/synflow.py
=> add option to show IO on flowgraphs

tests/examples/test_oh_experiments.py
https://github.com/siliconcompiler/siliconcompiler/actions/runs/9873490946
=> fix feedback test

setup/ubuntu20/install-yosys.sh, setup/ubuntu22/install-yosys.sh, setup/ubuntu24/install-yosys.sh
Per: https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/pull/2110
=> enable better optimizations for yosys build

siliconcompiler/flows/_common.py, siliconcompiler/tools/_common/__init__.py, siliconcompiler/tools/slang/lint.py, siliconcompiler/tools/surelog/parse.py, siliconcompiler/tools/sv2v/convert.py, siliconcompiler/tools/verilator/verilator.py, siliconcompiler/utils/__init__.py
makes it easier to auto select frontends
=> split verilog and systemverilog in inputs

.github/workflows/tools_ci.yml
This reverts commit 4bac36809735f09efb7f51cdf59a98b2034014a2.
=> Revert "switch to remote branch"

docs/user_guide/images/challenge_nsquared.py, siliconcompiler/core.py, siliconcompiler/flowgraph.py, siliconcompiler/flows/_common.py
Use edge weights to avoid graphs from getting too skewed
=> cleanup flowgraph generation

siliconcompiler/remote/client.py, siliconcompiler/schema/schema_cfg.py, siliconcompiler/use.py, tests/apps/test_sc_remote.py, tests/core/data/defaults.json, tests/server/test_server.py
This ensures everything runs on the server, which requires a few more copy flags to be set.
=> remove the local run from server runs

siliconcompiler/templates/tcl/manifest.tcl.j2, siliconcompiler/tools/_common/__init__.py, siliconcompiler/tools/_common/asic.py, siliconcompiler/tools/klayout/export.py, siliconcompiler/tools/klayout/klayout_export.py, siliconcompiler/tools/klayout/klayout_utils.py, siliconcompiler/tools/magic/sc_drc.tcl, siliconcompiler/tools/magic/sc_extspice.tcl, siliconcompiler/tools/netgen/sc_lvs.tcl, siliconcompiler/tools/openroad/export.py, siliconcompiler/tools/openroad/openroad.py, siliconcompiler/tools/openroad/scripts/sc_apr.tcl, siliconcompiler/tools/opensta/__init__.py, siliconcompiler/tools/opensta/scripts/sc_report_libraries.tcl, siliconcompiler/tools/opensta/scripts/sc_timing.tcl, siliconcompiler/tools/yosys/sc_lec.tcl, siliconcompiler/tools/yosys/syn_asic.py, siliconcompiler/tools/yosys/syn_asic.tcl, tests/tools/test_common.py
=> recursive asic library importing

Changes, siliconcompiler/_metadata.py
~~Requires https://github.com/siliconcompiler/siliconcompiler/actions/runs/10514314211 to pass~~ (https://github.com/The-OpenROAD-Project/OpenROAD/issues/5637)
Requires https://github.com/siliconcompiler/siliconcompiler/actions/runs/10516103691 to pass
=> version 0.26.4

.github/workflows/conda_ci.yml, .github/workflows/daily_ci.yml, .github/workflows/lint.yml, .github/workflows/python_ci.yml, .github/workflows/tools_ci.yml, pyproject.toml
https://github.com/siliconcompiler/siliconcompiler/actions/runs/10541958843
=> rework CI testing to run in a separate directory

.github/workflows/bin/install_klayout_win.bat, .github/workflows/wheels.yml
https://github.com/siliconcompiler/siliconcompiler/actions/runs/10548063708
=> install klayout purely in yml file

Changes, siliconcompiler/_metadata.py
https://github.com/siliconcompiler/siliconcompiler/actions/runs/10566082908
https://github.com/siliconcompiler/siliconcompiler/actions/runs/10565870583
=> version 0.26.5

siliconcompiler/core.py
=> limit logger columns to 20 characters

examples/aes/aes.py, examples/oh_experiments/check_area.py, examples/picorv32/picorv32.py, examples/picorv32_ram/picorv32_ram.py, siliconcompiler/flows/screenshotflow.py
https://github.com/siliconcompiler/siliconcompiler/actions/runs/10596828480
=> fix daily run identified issues

siliconcompiler/schema/schema_cfg.py, tests/core/data/defaults.json
- Adding Option to options category
- Consistent capitalization
=> Cleanup of schema short help strings (non functional change)

siliconcompiler/schema/schema_obj.py, siliconcompiler/tools/vpr/place.py, siliconcompiler/tools/vpr/vpr.py, tests/core/test_setget.py
=> generate error when accessing default keys

docs/_ext/requirements.py, docs/conf.py, siliconcompiler/sphinx_ext/dynamicgen.py
=> ensure docs builds on python3.12

siliconcompiler/schema/schema_cfg.py, tests/core/data/defaults.json
=> use keypath to link keys in docs

siliconcompiler/schema/schema_cfg.py, siliconcompiler/tools/openroad/scripts/sc_floorplan.tcl, siliconcompiler/tools/openroad/scripts/sc_procs.tcl, tests/core/data/defaults.json
=> fix openroad rotations

examples/picorv32_ram/picorv32_ram.py
https://github.com/siliconcompiler/siliconcompiler/actions/runs/10975016808
=> place memory in the middle to allow for routing with better derating

siliconcompiler/tools/openroad/floorplan.py, siliconcompiler/tools/openroad/openroad.py, siliconcompiler/tools/openroad/scripts/sc_cts.tcl, siliconcompiler/tools/openroad/scripts/sc_floorplan.tcl, siliconcompiler/tools/openroad/scripts/sc_procs.tcl
Fix bug in check_enable
Add options to bypass remove_buffers, repair_timing setup/hold
print macro placements
=> update openroad driver

siliconcompiler/apps/sc_install.py, tests/apps/data/echo_prefix.sh, tests/apps/test_sc_install.py
Fixes incorrect key access in #2881
=> Guard install groups against unsupported os's

.github/workflows/tool_updater.yml
https://github.com/siliconcompiler/siliconcompiler/actions/runs/11308307778
=> fix tool updater

.github/workflows/wheels.yml
https://github.com/siliconcompiler/siliconcompiler/actions/runs/11316135425
=> pin wheels to 22

siliconcompiler/report/dashboard/components/__init__.py, siliconcompiler/report/dashboard/layouts/vertical_flowgraph.py, siliconcompiler/report/dashboard/layouts/vertical_flowgraph_node_tab.py, siliconcompiler/report/dashboard/layouts/vertical_flowgraph_sac_tabs.py
=> add node image viewer

siliconcompiler/tools/_common/__init__.py, siliconcompiler/tools/surelog/__init__.py
https://github.com/siliconcompiler/siliconcompiler/actions/runs/11543013204
=> ensure surelog records the proper require keys

.github/ISSUE_TEMPLATE/bug_report.yml, .github/workflows/conda_ci.yml, .github/workflows/daily_ci.yml, .github/workflows/python_ci.yml, .github/workflows/tools_ci.yml, .github/workflows/wheels.yml, pyproject.toml, tests/core/test_write_manifest.py
Wheels: https://github.com/siliconcompiler/siliconcompiler/actions/runs/11554009042
Daily: https://github.com/siliconcompiler/siliconcompiler/actions/runs/11554021103
=> add 3.13 to CIs

siliconcompiler/tools/yosys/sc_syn.tcl, siliconcompiler/tools/yosys/syn_asic.py, siliconcompiler/tools/yosys/yosys.py
Reverts siliconcompiler/siliconcompiler#2939
Not stable
=> Revert "fill in yosys requirements"

Changes, siliconcompiler/_metadata.py
Required to pass: https://github.com/siliconcompiler/siliconcompiler/actions/runs/11557291831
=> version 0.28.4

siliconcompiler/scheduler/__init__.py, siliconcompiler/schema/schema_obj.py, siliconcompiler/templates/tcl/manifest.tcl.j2
Needed to be able to check require list against the actually needed values.
By default, no functional changes.
=> provide hooks to debug require list for tool/task drivers

siliconcompiler/tools/openroad/rdlroute.py, siliconcompiler/tools/openroad/scripts/sc_rdlroute.tcl, tests/core/test_tool_tasks.py
This may be changed in the future to just an interposer task, depending on needs.
=> add standalone rdlroute task to openroad

examples/interposer/bumps.tcl, examples/interposer/interposer.py, examples/interposer/interposer.v, pyproject.toml, siliconcompiler/flows/drcflow.py, siliconcompiler/flows/interposerflow.py, siliconcompiler/libs/interposer.py, siliconcompiler/pdks/interposer.py, siliconcompiler/targets/interposer_demo.py, tests/examples/test_interposer.py
=> add interposer example

.github/workflows/python_ci.yml, .github/workflows/tools_ci.yml
=> use editable install to get code coverage

pyproject.toml, siliconcompiler/report/dashboard/__init__.py
https://github.com/streamlit/streamlit/blob/ea8dd49a463018a7a9a62c2190bbc4cac7eb9297/lib/setup.py#L141
=> remove streamlit from 3.9.7 and indicate that dashboard is not available

.github/workflows/wheels.yml
https://github.com/siliconcompiler/siliconcompiler/actions/runs/12055524683/job/33616072361
=> cache klayout in wheels to avoid failed workflows. 

examples/interposer/interposer.py, siliconcompiler/tools/openroad/__init__.py, siliconcompiler/tools/openroad/rdlroute.py, siliconcompiler/tools/openroad/scripts/apr/sc_init_floorplan.tcl, siliconcompiler/tools/openroad/scripts/common/procs.tcl, siliconcompiler/tools/openroad/scripts/common/reports.tcl
=> update openroad scripts to use newer commands

pyproject.toml
Reverts siliconcompiler/siliconcompiler#3040
=> Revert "remove urllib3 as this is correctly handled in PyGithub"

siliconcompiler/report/report.py, siliconcompiler/scheduler/__init__.py, siliconcompiler/schema/schema_cfg.py, tests/core/data/defaults.json, tests/core/test_reports.py, tests/core/test_track.py
Adds:
- pythonversion and pythonpackage to schema records to allow for better provenance
- add testing to ensure functionality
=> add python packages to schema

scripts/check_library.py, siliconcompiler/tools/opensta/check_library.py, siliconcompiler/tools/opensta/scripts/sc_check_library.tcl
Helper script for library generation check
=> check_library task for sta

siliconcompiler/tools/openroad/_apr.py
~https://github.com/siliconcompiler/siliconcompiler/actions/runs/12377753599~
~https://github.com/siliconcompiler/siliconcompiler/actions/runs/12379455578~
~https://github.com/siliconcompiler/scgallery/actions/runs/12382089663~
https://github.com/siliconcompiler/scgallery/actions/runs/12385569029
=> switch rtlmp as default for openroad

siliconcompiler/core.py, siliconcompiler/scheduler/__init__.py, siliconcompiler/schema/schema_cfg.py, siliconcompiler/schema/schema_obj.py, siliconcompiler/schema/utils.py, tests/core/data/defaults.json, tests/core/test_setget.py
limits printing of messages to a minimum
=> add quiet level to loglevel

.readthedocs.yaml, pyproject.toml, siliconcompiler/optimizer/__init__.py, siliconcompiler/optimizer/vizier.py
=> initial optimizer implementation

siliconcompiler/tools/yosys/syn_asic.py, siliconcompiler/tools/yosys/syn_asic.tcl, siliconcompiler/tools/yosys/yosys.py
requires update to yosys minimum version
=> add support for clockgate insertion via yosys

.github/workflows/wheels.yml
https://github.com/siliconcompiler/siliconcompiler/actions/runs/12760644510
=> only test klayout in wheel

siliconcompiler/tools/_common/asic_clock.py, siliconcompiler/tools/yosys/syn_asic.py, tests/tools/data/sdc_with_nested.sdc, tests/tools/data/sdc_with_number0.sdc, tests/tools/data/sdc_with_number1.sdc, tests/tools/data/sdc_with_variable.sdc, tests/tools/test_common.py
This will allow other tools to access this functionality
=> add helper function to allow for access to clock period

siliconcompiler/remote/client.py
Closes: https://github.com/siliconcompiler/siliconcompiler/issues/3175
=> remove remote collection once its no longer needed

siliconcompiler/apps/sc_install.py, tests/apps/test_sc_install.py
Unsupported OS:
- "Unsupported operating system" + print debug information
- Unsupported group:
- "asic group is not available for <os> due to lack of support for the following tools: klayout, openroad"
=> Better feedback in sc-install

siliconcompiler/scheduler/__init__.py, siliconcompiler/tools/openroad/_apr.py, tests/apps/test_sc_install.py, tests/flows/test_resume.py
https://github.com/siliconcompiler/siliconcompiler/actions/runs/13090802613
=> fix CI failures

siliconcompiler/tools/openroad/fillmetal_insertion.py, siliconcompiler/tools/openroad/macro_placement.py, siliconcompiler/tools/openroad/pin_placement.py
report_power adds up to a good amount of time, this limits it a little bit
=> remove power reporting from some steps in openroad

siliconcompiler/core.py
Extra "" was causing issues in my editor syntax higlighter
=> Removing extra quotes

Changes, siliconcompiler/_metadata.py
https://github.com/siliconcompiler/siliconcompiler/actions/runs/13394078253
=> version 0.30.0

siliconcompiler/scheduler/__init__.py, tests/flows/test_prune.py
Closes: https://github.com/siliconcompiler/siliconcompiler/issues/3252
=> ensure select_inputs only uses pruned inputs

siliconcompiler/core.py
=> cleanup output files during call to summary

siliconcompiler/tools/klayout/export.py, siliconcompiler/tools/klayout/klayout.py, siliconcompiler/tools/klayout/klayout_export.py, siliconcompiler/tools/klayout/klayout_operations.py, siliconcompiler/tools/klayout/klayout_utils.py, siliconcompiler/tools/klayout/operations.py, siliconcompiler/tools/openroad/_apr.py
=> Fix totalarea

siliconcompiler/schema/schema_obj.py, siliconcompiler/templates/tcl/manifest.tcl.j2, siliconcompiler/tools/_common/tcl/sc_pin_constraints.tcl, siliconcompiler/tools/openroad/rdlroute.py, siliconcompiler/tools/openroad/scripts/apr/sc_init_floorplan.tcl, siliconcompiler/tools/openroad/scripts/sc_rdlroute.tcl, tests/core/test_write_manifest.py
Closes: https://github.com/siliconcompiler/siliconcompiler/issues/3278
https://github.com/siliconcompiler/siliconcompiler/actions/runs/13638409178
=> dont convert all params in tcl to lists

siliconcompiler/tools/openroad/_apr.py, siliconcompiler/tools/openroad/scripts/common/write_images.tcl
Merge when OpenROAD version is fully resolved
=> add histogram images

Changes, siliconcompiler/_metadata.py
https://github.com/siliconcompiler/siliconcompiler/actions/runs/13842236624
https://github.com/siliconcompiler/siliconcompiler/actions/runs/13842608046
=> version 0.32.1

siliconcompiler/tools/openroad/_apr.py, siliconcompiler/tools/openroad/scripts/apr/sc_repair_timing.tcl, siliconcompiler/tools/openroad/scripts/common/procs.tcl
flow not updated as global router is failing on incremental
=> prepare for post routing timing repair

siliconcompiler/tools/openroad/scripts/apr/sc_repair_timing.tcl, siliconcompiler/tools/openroad/scripts/common/procs.tcl
Can be undone once https://github.com/The-OpenROAD-Project/OpenROAD/issues/6926 is resolved
=> fix segfault for on repeated called to haveroutes

siliconcompiler/tools/openroad/scripts/apr/sc_antenna_repair.tcl, siliconcompiler/tools/openroad/scripts/apr/sc_clock_tree_synthesis.tcl, siliconcompiler/tools/openroad/scripts/apr/sc_detailed_placement.tcl, siliconcompiler/tools/openroad/scripts/apr/sc_detailed_route.tcl, siliconcompiler/tools/openroad/scripts/apr/sc_endcap_tapcell_insertion.tcl, siliconcompiler/tools/openroad/scripts/apr/sc_fillercell_insertion.tcl, siliconcompiler/tools/openroad/scripts/apr/sc_fillmetal_insertion.tcl, siliconcompiler/tools/openroad/scripts/apr/sc_global_placement.tcl, siliconcompiler/tools/openroad/scripts/apr/sc_global_route.tcl, siliconcompiler/tools/openroad/scripts/apr/sc_init_floorplan.tcl, siliconcompiler/tools/openroad/scripts/apr/sc_macro_placement.tcl, siliconcompiler/tools/openroad/scripts/apr/sc_metrics.tcl, siliconcompiler/tools/openroad/scripts/apr/sc_pin_placement.tcl, siliconcompiler/tools/openroad/scripts/apr/sc_power_grid.tcl, siliconcompiler/tools/openroad/scripts/apr/sc_repair_design.tcl, siliconcompiler/tools/openroad/scripts/apr/sc_repair_timing.tcl, siliconcompiler/tools/openroad/scripts/apr/sc_write_data.tcl, siliconcompiler/tools/openroad/scripts/sc_rcx.tcl, siliconcompiler/tools/openroad/scripts/sc_rdlroute.tcl, siliconcompiler/tools/openroad/scripts/sc_show.tcl, siliconcompiler/tools/opensta/__init__.py, siliconcompiler/tools/opensta/scripts/sc_check_library.tcl, siliconcompiler/tools/opensta/scripts/sc_report_libraries.tcl, siliconcompiler/tools/opensta/scripts/sc_timing.tcl, siliconcompiler/tools/opensta/timing.py, siliconcompiler/toolscripts/_tools.json, siliconcompiler/toolscripts/rhel9/install-opensta.sh, siliconcompiler/toolscripts/ubuntu20/install-opensta.sh, siliconcompiler/toolscripts/ubuntu22/install-opensta.sh, siliconcompiler/toolscripts/ubuntu24/install-opensta.sh
Needed for when openroad stops installing the sta binary automatically
=> add opensta build script

siliconcompiler/report/dashboard/cli/__init__.py, tests/core/test_cli_dashboard.py
@Ciprian167 I created a PR for us to discuss this in.
I like the log appears be correct, but if I down size the window and then upsize it the log doesn't return to full size (repeatedly doing this causes the log to shrink to almost nothing).
=> add a layout class and improve responsiveness

siliconcompiler/core.py
=> allow string in node index

siliconcompiler/report/dashboard/cli/__init__.py, tests/core/test_cli_dashboard.py
=> avoid accessing chip object inside the render loop

siliconcompiler/tools/openroad/_apr.py, siliconcompiler/tools/openroad/scripts/common/procs.tcl
Needs an update to OpenROAD to make this work correctly
=> add path groups automatically if not specified

siliconcompiler/report/dashboard/cli/__init__.py, siliconcompiler/report/dashboard/cli/board.py, tests/core/test_cli_dashboard.py
=> cli dashboard support mutliple runs in a single session

scripts/profile_sc.py, siliconcompiler/flowgraph.py, siliconcompiler/scheduler/__init__.py
=> Large flow profile example

siliconcompiler/scheduler/__init__.py
@Ciprian167 fyi, I'll take a look at it next week to see if I can fix the threading issue
=> disable caching for now as it appears to not be isolated for threading

.github/workflows/tools_ci.yml
This reverts commit ab53f16504df429e0dc5ce2599b3d00988e1c7f9.
=> Revert "switch to task scheduler branch"

siliconcompiler/report/dashboard/cli/__init__.py, siliconcompiler/report/dashboard/cli/board.py
The main update here is to keep the rendering loop open, and move to a common live display.
=> Improve cli rendering for multijob scenarios

siliconcompiler/apps/utils/replay.py, siliconcompiler/record.py, siliconcompiler/schema/schema_cfg.py, tests/core/data/defaults.json, tests/test_record.py
Adds the clarification of timezone used for record to help
=> record microseconds for start and end times to improve reporting times

siliconcompiler/tools/openroad/scripts/common/procs.tcl
=> check openroad version for path_group_names

docs/reference_manual/schema_api.rst, siliconcompiler/__init__.py, siliconcompiler/design.py, tests/test_design.py
Enables `.add_dep` to design class
=> make design a child of dependencyschema

.github/ISSUE_TEMPLATE/bug_report.yml, .github/workflows/daily_ci.yml, .github/workflows/python_ci.yml, .github/workflows/tools_ci.yml, .github/workflows/wheels.yml, README.md, pyproject.toml
=> remove support for python3.8

siliconcompiler/toolscripts/rhel8/install-xyce.sh, siliconcompiler/toolscripts/rhel9/install-xyce.sh, siliconcompiler/toolscripts/ubuntu22/install-xyce.sh, siliconcompiler/toolscripts/ubuntu24/install-xyce.sh
Reverts siliconcompiler/siliconcompiler#3714
Currently there is an issue with convergence in parallel runs.
=> Revert "build xyce for parallel"

siliconcompiler/remote/client.py, siliconcompiler/scheduler/schedulernode.py, siliconcompiler/scheduler/send_messages.py, siliconcompiler/tools/slang/__init__.py, tests/scheduler/test_schedulernode.py, tests/utils/test_issue.py
@Ciprian167 FYI
Reimplements the changes previously reverted out, but preserves the server API calls.
=> fix step index use

siliconcompiler/core.py, siliconcompiler/scheduler/schedulernode.py, siliconcompiler/tool.py, siliconcompiler/utils/__init__.py
logger information does not provide much useful information and this leverages the python handling.
=> remove custom handling of errors and just to default codecs behavior

siliconcompiler/core.py, siliconcompiler/scheduler/schedulernode.py
=> remove add_file_logger

siliconcompiler/core.py, siliconcompiler/remote/client.py, siliconcompiler/report/dashboard/cli/__init__.py, siliconcompiler/scheduler/docker.py, siliconcompiler/scheduler/run_node.py, siliconcompiler/scheduler/schedulernode.py, siliconcompiler/scheduler/slurm.py, siliconcompiler/utils/logging.py, tests/core/test_cli_dashboard.py, tests/scheduler/test_schedulernode.py
=> simplify logger init

Changes, siliconcompiler/_metadata.py
https://github.com/siliconcompiler/siliconcompiler/actions/runs/16119068942
https://github.com/siliconcompiler/siliconcompiler/actions/runs/16119071474
=> version 0.34.1

siliconcompiler/tool.py, tests/test_tool.py
Error noticed on failed CI in other repo
=> ensure tool arguments are handled as strings

siliconcompiler/scheduler/docker.py, siliconcompiler/scheduler/scheduler.py, siliconcompiler/scheduler/schedulernode.py, siliconcompiler/tool.py, tests/scheduler/test_schedulernode.py, tests/test_tool.py
=> avoid direct chip accesses in scheduler

siliconcompiler/design.py, siliconcompiler/package/__init__.py, siliconcompiler/pathschema.py, siliconcompiler/schema/baseschema.py, siliconcompiler/schema_obj.py, tests/schema/test_baseschema.py, tests/test_design.py, tests/test_pathschema.py
=> rename dataref to dataroot

siliconcompiler/__init__.py, siliconcompiler/project.py, siliconcompiler/schema/schema_cfg.py, tests/test_project.py
API will be reviewed separately
=> add initial version of project class

docs/reference_manual/schema_api.rst, siliconcompiler/__init__.py, siliconcompiler/library.py, tests/test_library.py
Library schema class, currently just an extension of the design class
StdCellLibrary provides the basic additional information needed (so far)
=> add library schema v0

tests/flows/test_fpgaflow.py
@AlexandreSinger FYI, lets see how this goes
=> preload fpga archs

.github/workflows/bin/generate_cache.py, .github/workflows/daily_ci.yml, .github/workflows/tools_ci.yml, pyproject.toml, tests/conftest.py, tests/core/test_check_filepaths.py, tests/core/test_hash_files.py, tests/flows/test_fpgaflow.py, tests/package/test_package.py, tests/tools/test_klayout.py
https://github.com/siliconcompiler/siliconcompiler/actions/runs/16389664133
=> generate CI cache to avoid repeated accesses during testing

siliconcompiler/__init__.py, siliconcompiler/design.py, tests/test_design.py
This completes added package information to the design object
=> make design contain package information

Changes, siliconcompiler/_metadata.py
https://github.com/siliconcompiler/siliconcompiler/actions/runs/16418412080
https://github.com/siliconcompiler/siliconcompiler/actions/runs/16418414629
=> version 0.34.2

siliconcompiler/checklist.py, siliconcompiler/constraints/asic_component.py, siliconcompiler/constraints/asic_pins.py, siliconcompiler/constraints/asic_timing.py, siliconcompiler/dependencyschema.py, siliconcompiler/design.py, siliconcompiler/flowgraph.py, siliconcompiler/project.py, siliconcompiler/scheduler/scheduler.py, siliconcompiler/scheduler/schedulernode.py, siliconcompiler/schema/namedschema.py, tests/constraints/test_asic_component.py, tests/constraints/test_asic_pins.py, tests/constraints/test_asic_timing.py, tests/schema/test_namedschema.py, tests/test_dependencyschema.py, tests/test_flowgraph.py, tests/test_pdk.py
=> rework namedschema name

siliconcompiler/__init__.py, siliconcompiler/project.py, siliconcompiler/tool.py, tests/test_tool.py
More testing needed, but functional starting point
=> add show to project

siliconcompiler/report/dashboard/cli/board.py, siliconcompiler/scheduler/taskscheduler.py, siliconcompiler/utils/multiprocessing.py, tests/core/test_cli_dashboard.py
Avoids using Queue directly for logging which is causing lockups on multipleprocessing runs
=> create mpmanger singleton

.github/workflows/wheels.yml, siliconcompiler/flows/showflow.py, siliconcompiler/project.py, tests/utils/test_showtools.py
https://github.com/siliconcompiler/siliconcompiler/actions/runs/17238570051
=> fix wheels CI test

siliconcompiler/demos/asic_demo.py, siliconcompiler/demos/fpga_demo.py, siliconcompiler/project.py, tests/test_project.py
Fixes summary getting masked by dashboard
=> stop dashboard when calling summary

siliconcompiler/tools/yosys/scripts/sc_synth_asic.tcl, siliconcompiler/tools/yosys/syn_asic.py
https://github.com/siliconcompiler/siliconcompiler/actions/runs/17474303606
Resolves ABC assert for now
=> avoid passing macros to abc

siliconcompiler/design.py, siliconcompiler/schema_support/filesetschema.py, siliconcompiler/tools/bambu/convert.py, siliconcompiler/tools/bluespec/convert.py, siliconcompiler/tools/chisel/convert.py, siliconcompiler/tools/ghdl/convert.py, siliconcompiler/tools/icarus/compile.py, siliconcompiler/tools/klayout/export.py, siliconcompiler/tools/magic/__init__.py, siliconcompiler/tools/netgen/lvs.py, siliconcompiler/tools/nextpnr/apr.py, siliconcompiler/tools/openroad/_apr.py, siliconcompiler/tools/openroad/rdlroute.py, siliconcompiler/tools/slang/__init__.py, siliconcompiler/tools/surelog/parse.py, siliconcompiler/tools/verilator/__init__.py, siliconcompiler/tools/verilator/compile.py, siliconcompiler/tools/vpr/__init__.py, siliconcompiler/tools/vpr/place.py, siliconcompiler/tools/xdm/convert.py, siliconcompiler/tools/xyce/simulate.py, tests/schema_support/test_filesetschema.py, tests/test_design.py
Avoids resolving filepaths during setup() which is not needed during remote runs or runs on slurm
=> use has_file in setup()

examples/heartbeat_migen/heartbeat_migen.py, siliconcompiler/design.py, siliconcompiler/schema_support/filesetschema.py, siliconcompiler/schema_support/packageschema.py, siliconcompiler/schema_support/pathschema.py, siliconcompiler/tool.py, siliconcompiler/tools/openroad/__init__.py, siliconcompiler/tools/openroad/rdlroute.py, siliconcompiler/tools/vpr/__init__.py, siliconcompiler/tools/yosys/__init__.py, tests/schema_support/test_pathschema.py, tests/test_design.py, tests/tools/test_vpr.py
* add_depfileset will infer the depfileset if not specified
* dataroot will be inferred when possible
=> allow filesets and dataroots to be inferred

siliconcompiler/schema/baseschema.py, tests/schema/test_baseschema.py
=> add search paths to filenotfound error

siliconcompiler/project.py, siliconcompiler/report/dashboard/cli/board.py, siliconcompiler/report/dashboard/web/state.py, siliconcompiler/scheduler/docker.py, siliconcompiler/scheduler/schedulernode.py, siliconcompiler/scheduler/slurm.py, siliconcompiler/utils/issue.py, tests/test_design.py, tests/test_project.py
move towards reduced API methods on `Project`
=> remove .cwd from project
